all: clean copyconstructor memberwise407 Array474

Array474:
	$(CXX) Array474.cpp Array474_main.cpp -o Array474

memberwise407:
	$(CXX) memberwise407.cpp memberwise407_main.cpp -o memberwise407

clean:
	rm -f copyconstructor
	rm -f memberwise407
	rm -f Array474
