#!/bin/sh




curl -X POST http://127.0.0.1:5984/_replicate   \
    -H "Content-Type: application/json"         \
    -d '{"source":"http://example.org/database", "target":"http://admin:password@127.0.0.1:5984/database"}'


curl -X POST http://127.0.0.1:5984/_replicate   \
    -H "Content-Type: application/json"         \
    -d '{"source":"db", "target":"db-replica", "continuous":true}' 
