CXX = g++

all: clean BasePlusCommissionEmployee520

BasePlusCommissionEmployee520:
	$(CXX) CommissionEmployee520.cpp BasePlusCommissionEmployee520.cpp BasePlusCommissionEmployee520_main.cpp -o BasePlusCommissionEmployee520

clean:
	rm -f BasePlusCommissionEmployee520
