#!/bin/sh -x




# You need to specify the type, so the browser can render it when downloaded
# 6e1295ed6c29495e54cc05947f18c8af is the document you want to attach the file to
# 2-2739352689 is the revision of that document
# profile.jpg is the fiel to be attached
# profile.jpg is a JPEG file

printf "\nOFFLINE ATTACHiMENT OF AN IMAGE  (profile.jpg)\n"
#curl -vX PUT ${COUCH_URI}/employees/johnlennon/profile.jpg?rev=1-263755682bbbebb54ca288f011e1f381                      \

curl -vX PUT ${COUCH_URI}/employees/johnlennon/                             \
    profile.jpg?rev=1-263755682bbbebb54ca288f011e1f381                      \
    --data-binary @profile.jpg                                              \
    -H "Content-Type: image/jpg" 


#Attached with the document
printf "\nPUT A TEXT INLINE ATTACHMENT (foo.txt)\n"

curl -X PUT ${COUCH_URI}/employees/johnattach -H "Content-Type: application/json" -d @attach_01.json

printf "\nGET INLINE ATTACHMENT (foo.txt)\n"
curl -X GET http://username:password@127.0.0.1:5984/employees/johnattach/foo.txt

echo



