INSTALL_DIR	=	/etc/init.d

FILES		+=	mysqld

#----------------------------------------------------------------------
CP	=	cp -ar
#----------------------------------------------------------------------
all: build test_build install test_install
build:
test_build:
install:
	$(CP) $(FILES)  $(INSTALL_DIR)/
test_install:

