all:  clean BasePlusCommissionEmployee548

BasePlusCommissionEmployee548:
	$(CXX) BasePlusCommissionEmployee548.cpp BasePlusCommissionEmployee548_main.cpp CommissionEmployee548.cpp -o BasePlusCommissionEmployee548

clean:
	rm -f BasePlusCommissionEmployee548
