all: clean Increment421 Employee427

Employee427:
	$(CXX) Date427.cpp Employee427.cpp Employee427_main.cpp -o Employee427


Increment421:
	$(CXX) Increment421.cpp Increment421_main.cpp -o Increment421

clean:
	rm -f Increment421
	rm -f Employee427
