all: clean Date427 Employee427

Date427:
	$(CXX) Date427.cpp Date427_main.cpp -o Date427

Employee427:
	$(CXX) Date427.cpp Employee427.cpp Employee427_main.cpp -o Employee427

clean:
	rm -f Date427
	rm -f Employee427
