#!/usr/bin/python



"""
Example: simple line plot.
Show how to make and save a simple line plot with labels, title and grid
"""
import pylab as plt

plt.plot([1,3,2,4])

#decoration
plt.xlabel('time (s)')
plt.ylabel('voltage (mV)')
plt.title('About as simple as it gets, folks')
plt.grid(False)

#save png
#plt.savefig('/tmp/simple_plot')

plt.show()

