#!/usr/bin/python



"""
Example: simple line plot.
Show how to make and save a simple line plot with labels, title and grid
"""
import numpy 
#import numpy as np
import pylab as lab

pi=numpy.pi
x = numpy.arange(0.0, 1.0+0.01, 0.01) #<- 100 elements
x1 = numpy.arange(0.0, 1.0+0.1, 0.1) #<- 10 elements
y = numpy.sin(2*pi*x)
y = numpy.cos(2*2*numpy.pi*x)
lab.plot(x, y, 'b--',label="Sin")
lab.plot(x, x, 'g:',label="Straight line")
lab.plot(x, -x, 'r-.',label="Straight line")
pi=numpy.pi
lab.plot(x1, numpy.sin(x1*5*4*pi), 'y-o',label="Straight line")
#lab.plot(y+1,'y',label='toto')	#<- x=1 for element 1 , etc,

lab.legend(loc='lower center')


#lab.xticks(range(0,100,5)) #, ['a','b','c'])
lab.xticks([1,2] , ['a','b','c'])

lab.text(1.2,0.44 , 'sin(0)=0')

lab.annotate('this is an arrow', xy=(0.5,-.4), xytext=(1.7,-.5), arrowprops=dict(facecolor='black', shrink=0.05))

#decoration
lab.xlabel('time (s)')
lab.ylabel('voltage (mV)')
lab.title('About as simple as it gets, folks')
lab.grid(True)

#Figure
fig2=lab.figure()
ax=fig2.add_subplot(111)
l, = lab.plot(x,y)

#Doesn't work that well!!! or doesn't work at all...
#ax.text(0.4,0.4,r"$ \lim_{x \rightarrow 0} \frac{2}{x} \sum_{i=1}^{\infty}\ x_i^2 $")

#Figure
fig3=lab.figure()
#ax=fig3.add_subplot(111)
#ax=fig3.add_subplot(121)
ax=fig3.add_subplot(324)
lab.plot(x, y, 'b--',label="Sin")
ax=fig3.add_subplot(321)
lab.plot(x, -x, 'r-.',label="Straight line")
ax=fig3.add_subplot(325)
lab.plot(x, x, 'g:',label="Straight line")


#save png file
#lab.savefig('simple_plot')

lab.show()

