#!/bin/bash

sudo apt-get -y install apt-file
apt-file update                         # Update database of files

sudo apt-get -y install git
sudo apt-get -y install make

#Utilities
sudo apt-get -y install xpdf

# Python
sudo apt-get -y install python-setuptools
sudo apt-get -y install python2.7-dev

#Couchdb
sudo apt-get -y install couchdb
sudo apt-get -y install simplejson

sudo easy_install  couchapp
