#!/bin/sh -x

printf "\nMAP REDUCE 1 (error: wrong method!)\n"
curl -X GET http://127.0.0.1:5984/contacts/_temp_view -H "Content-Type: application/json" -d @mapreduce_01.json
# {"error":"method_not_allowed","reason":"Only POST allowed"}

printf "\nMAP REDUCE 1 (test)\n"
curl -X POST http://127.0.0.1:5984/contacts/_temp_view -H "Content-Type: application/json" -d @mapreduce_01.json

printf "\nMAP REDUCE (advanced map)\n"
curl -X POST http://127.0.0.1:5984/contacts/_temp_view -H "Content-Type: application/json" -d @mapreduce_02_advancedmap.json

printf "\nMAP REDUCE (map and reduce!)\n"
curl -X POST http://127.0.0.1:5984/contacts/_temp_view -H "Content-Type: application/json" -d @mapreduce_03_mapreduce.json

printf "\nMAP REDUCE (with ...?group=true!)\n"
curl -X POST http://127.0.0.1:5984/contacts/_temp_view?group=true -H "Content-Type: application/json" -d @mapreduce_03_mapreduce.json

printf "\nMAP REDUCE (word count)\n"
curl -X POST http://127.0.0.1:5984/speeches/_temp_view -H "Content-Type: application/json" -d @mapreduce_04_wordcount.json

printf "\nMAP REDUCE (word count with grouping)\n"
curl -X POST http://127.0.0.1:5984/speeches/_temp_view?group=true -H "Content-Type: application/json" -d @mapreduce_04_wordcount.json

printf "\nMAP REDUCE (grouped by starting letter)\n"
curl -X POST http://127.0.0.1:5984/speeches/_temp_view?group=true -H "Content-Type: application/json" -d @mapreduce_05_startingletter.json

printf "\n***ADVANCED***\n"
printf "\nMAP REDUCE (group by department)\n"
curl -X GET http://127.0.0.1:5984/employees/_all_docs?include_docs=true

printf "\n ADVANCED MAP REDUCE\n"
curl -X POST http://127.0.0.1:5984/employees/_temp_view?group=true -H "Content-Type: application/json" -d @mapreduce_10_employeesbydepartment.json
curl -X POST http://127.0.0.1:5984/employees/_temp_view?group=true -H "Content-Type: application/json" -d @mapreduce_11_totalsalarybydepartment.json
curl -X POST http://127.0.0.1:5984/employees/_temp_view?group=true -H "Content-Type: application/json" -d @mapreduce_12_averagesalarybydepartment.json
curl -X POST http://127.0.0.1:5984/employees/_temp_view?group=true -H "Content-Type: application/json" -d @mapreduce_13_averagesalaryforallemployees.json
curl -X POST http://127.0.0.1:5984/employees/_temp_view?group=true -H "Content-Type: application/json" -d @mapreduce_14_minmaxsalary.json
curl -X POST http://127.0.0.1:5984/employees/_temp_view -H "Content-Type: application/json" -d @mapreduce_14_minmaxsalary.json

#NOT WORKING !???
curl -X POST http://127.0.0.1:5984/employees/_temp_view?group=true -H "Content-Type: application/json" -d @mapreduce_20_minmaxsalarywithname.json
curl -X POST http://127.0.0.1:5984/employees/_temp_view -H "Content-Type: application/json" -d @mapreduce_20_minmaxsalarywithname.json
