#!/bin/sh



#python appcfg.py --email=emayssat.gae@gmail.com update 003_blog
#python appcfg.py --email=emayssat.gae@gmail.com update 004_cookie
python appcfg.py --email=emayssat.gae@gmail.com update 005_urllib
