all: clean constructor Array485

Array485:
	$(CXX) Array485_main.cpp Array474.cpp -o Array485

constructor:
	$(CXX) constructor.cpp constructor_main.cpp -o constructor

clean:
	rm -f constructor
	rm -f Array485
