#!/usr/bin/sudo /bin/sh

opt="-y"

yum $opt install freemind
yum $opt install xmms
yum $opt install xmms-mp3
yum $opt install vlc
yum $opt install youtube-dl
yum $opt install choqok

yum $opt python-numpy

