"""""
" VIMRC and VIM Help file
"
" .                 : redo last sequence (except undo)
" u                 : undo 
" Ctrl-W n          : horizontal split with new file
" Ctrl-W Ctrl-W     : jump to next window
" Ctrl-r            : undo undo !
"
" :e filename       : In current window open filename (read/write)
" :r filename       : In current window open filename (read only)
" :set all          : view all configruation parameters
" :help
"
"input mapping (shortcuts) BEWARE: wait for completion
"im #-       #----------------------------------------------------------------------
"
" More @ http://vimdoc.sourceforge.net/htmldoc/options.html


"""""""""""""""""""""
" Vundle
"""""""""""""""""""""
" Vundle = easy installation of vim pluggin from github !
" To install Vundle: 
" git clone https://github.com/gmarik/vundle.git ~/.vim/bundle/vundle

set nocompatible                    " be iMproved (vim ok, but not vi !)
filetype off                        " required
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

" let Vundle manage Vundle
" required! 
" Project at https://github.com/gmarik/vundle URL
" (same as) Bundle  'http://github.com/gmarik/vundle.git'
Bundle 'gmarik/vundle'              

" My Bundles here:
"
" original repos on github
Bundle 'tpope/vim-fugitive'
Bundle 'Lokaltog/vim-easymotion'
Bundle 'rstacruz/sparkup', {'rtp': 'vim/'}
Bundle 'tpope/vim-rails.git'
" vim-scripts repos
Bundle 'L9'
Bundle 'FuzzyFinder'
" non github repos
" (no access) Bundle 'git://git.wincent.com/command-t.git'

"
" Brief help
" :BundleInstall unite.vim      - installation by name
" :BundleInstall!               - install or updates configured scripts
" :BundleSearch foo             - 
" :BundleList                   - list all installed bundles
" :BundleSearch(!) foo - search(or refresh cache first) for foo
" :BundleClean(!)      - confirm(or auto-approve) removal of unused bundles
" let g:vundle_default_git_proto = 'git'    - use git proto instead of https
" see :h vundle for more details or wiki for FAQ
" NOTE: comments after Bundle command are not allowed..

"""""""""""""""""""""
" Keyboard shortcuts
"""""""""""""""""""""
"Note that everything on the map line is executed
"including spaces and comments if not careful

"in insert mode F2 will exit insert, save, enters insert again
"map <F2> <ESC>:w<CR>i

"In all modes
"Comments cannot be on the same line
"map <F1> <C-W>:r  ~/.vimrc
"map <F3> ^Wn
":r  ~/.vimrc
"map <F3> <C-W>
"F2 will save the file
"map <F2> :w<CR>

" With a map leader it's possible to do extra key combinations
" like <leader>w saves the current file
""let mapleader = ","
""let g:mapleader = ","

" Fast saving with ,w
""nmap <leader>w :w!<cr>

"Tab configuration
""map <leader>tn :tabnew<cr>
""map <leader>te :tabedit
""map <leader>tc :tabclose<cr>
""map <leader>tm :tabmove


"Windows
""map <C-j> <C-W>j
""map <C-k> <C-W>k
""map <C-h> <C-W>h
""map <C-l> <C-W>l

"In normal mode
"nmap
"In visual/select mode
"vmap
"In operator pending mode
"omap

"
" By File type
"
" :set filetype?            - to see the current filetype
" :set filetype=python      - to manually set the current filetype
" Note that the filetype is set automatically by vim 

"""""""""""""""
" PYTHON FILES
"""""""""""""""

" @ OPEN
"automatically increase indentation after those keywords
autocmd BufRead *.py set autoindent          "Use indentation of previous line
autocmd BufRead *.py set smartindent cinwords=if,elif,else,for,while,try,except,finally,def,class

" @ SAVE
"remove final spaces
autocmd BufWritePre *.py normal m`:%s/\s\+$//e ``

" insert mode abraviations (in insert mode only)
autocmd FileType python inoremap <buffer> $r return
autocmd FileType python inoremap <buffer> $i import
autocmd FileType python inoremap <buffer> $p print
autocmd FileType python inoremap <buffer> $f #--- PH ----------------------------------------------<esc>FP2xi

" normal mode
autocmd FileType python map <buffer> <leader>1 /class
autocmd FileType python map <buffer> <leader>2 /def
autocmd FileType python map <buffer> <leader>C ?class
autocmd FileType python map <buffer> <leader>D ?def


"""""""""""""""
" C FILES
"""""""""""""""

" @ OPEN
"automatically increase indentation after those keywords
""autocmd BufRead *.c set autoindent          "Use indentation of previous line
""autocmd BufRead *.c set smartindent cinwords=if,elif,else,for,while,try,except,finally,def,class

"""""""""""""""
" C++ FILES
"""""""""""""""

" @ OPEN
"automatically increase indentation after those keywords
""autocmd BufRead *.cpp set autoindent          "Use indentation of previous line
""autocmd BufRead *.cpp set smartindent cinwords=if,elif,else,for,while,try,except,finally,def,class

"""""""""""""""
" abbreviations
" corrections
"""""""""""""""
" If you type the lhs + <space>, vim insert the rhs (right hand side)
ab sefl     self
ab w/       with
ab #-       #----------------------------------------------------------------------

"""""""""""""""""
" Tab/Space/Shift
"""""""""""""""""

set expandtab           "turn tabs into spaces
set tabstop=4           "tab are 4 spaces
set softtabstop=4       "delete pseudo tab (4 spaces at once)
set shiftwidth=4        " Typing >> indent 4 spaces (<< does opposite)

"""""""""""""""""
" spell checking
"""""""""""""""""

"set automated spell checking in English
:setlocal spell spelllang=en
set spell               " activate spell check by default

" Toggle spell check with <F7>
nn <F7> :setlocal spell! spell?<CR>

"Pressing ,ss will toggle and un-toggle spell checking
"<leader> has been configured above as the , char
""map <leader>ss :setlocal spell!<cr>
""map <leader>sn ]s         " Go to next misspelled word
""map <leader>sp [s         " Go to previous misspelled word
" make suggestion
""map <leader>s? z=         " Make suggestion for misspelled word
""map <leader>sa zg
" add in dictionary spellfile
set spellfile=~/.vim/spellfile.add

" Meta up down for jump to next correction
""map <M-Down> ]s
""map <M-Up> [s

""""""""""""""""
" Appearances
""""""""""""""""

syntax on               "use color
""colorscheme evening     "ls -1 /usr/share/vim/vim72/colors/ for list!
"overwrite color scheme
highlight LineNr        ctermfg=blue
"highlight LineNr       ctermfg=white ctermbg=blue cterm=reverse
"highlight link Define          LineNr
"set bg=light           "char background is white: adjust FONT colors (darken them)
set bg=dark            "term background is dark: adjust FONT colors (lighten them)

""set cursorline          "display an annoying line under cursor

set scrolloff=3         "3 lines offset at top and bottom when scrolling up/down

set number              "line numbering on 
"set nonumber           "line numbering off

set wrap!               "turn off word wrapping
"set wrap               "turn on word wrapping
""set wrapmargin=2        "wrap is less that 2 char away from margin

""set mouse=a             "allow mouse in term (may not work!)

set showmatch           "show closing bracket when on a bracket, etc
set vb t_vb=            "visual bell

""set lines=80            "reset terminal size
""set columns=100         "reset terminal size

set ruler               "show current position

" Format the statusline
"set statusline=\ %{HasPaste()}%F%m%r%h\ %w\ \ CWD:\ %r%{CurDir()}%h\ \ \ Line:\ %l/%L:%c
""set laststatus=2

"function! CurDir()
"    let curdir = substitute(getcwd(), '/Users/emayssat/', "~/", "g")
"    return curdir
"endfunction

"function! HasPaste()
"    if &paste
"        return 'PASTE MODE  '
"    else
"        return ''
"    endif
"endfunction


""""""""""""""
" SEARCHES
""""""""""""""

set hlsearch            "highlight search
set incsearch           "real-time/incremental search
set noignorecase        "Case for search
set wrapscan            "If at bottom, start from the top

"space for forward search
map <space> /<CR>
"control space for forward search
""map <C-space> ?<CR>   " (Doesn't seem to work!)

""""""""""""""""""
" Temporary Files
""""""""""""""""""
set backup              "keep a backup file
"vim backup files and temporaries
set backupdir=~/.vim/vim-tmp,~/.tmp,~/tmp,~/var/tmp,/tmp
"location of swap files
set directory=~/.vim/vim-tmp,~/.tmp,~/tmp,~/var/tmp,/tmp

"""""""""""""""
" Legacy
"""""""""""""""

"remove emulation of old bugs
set nocompatible

