all: clean string455 PhoneNumber460 Date468 Array474 Array485 String487


String487:
	$(CXX) String487.cpp String487_main.cpp -o String487

Array485:
	$(CXX) Array474.cpp Array485_main.cpp -o Array485

Array474:
	$(CXX) Array474.cpp Array474_main.cpp -o Array474

Date468:
	$(CXX) Date468.cpp Date468_main.cpp -o Date468

PhoneNumber460:
	$(CXX) PhoneNumber460.cpp PhoneNumber460_main.cpp -o PhoneNumber460

clean:
	rm -f string455
	rm -f PhoneNumber460
	rm -f Array474
	rm -f Array485
	rm -f String487
