/*
 * Interface wrapper code.
 *
 * Generated by SIP 4.10.2 on Fri Apr 22 17:31:55 2011
 */

#include "sipAPICaFramework.h"

#line 6 "CaObject.sip"
#include <CaObject.h>
#line 18 "CaObject.sip"
#include <CaObject.h>
#line 14 "sipCaFrameworkcaobjectCaObject.cpp"

#line 6 "CaObject.sip"
#include <CaObject.h>
#line 18 "CaObject.sip"
#include <CaObject.h>
#line 20 "sipCaFrameworkcaobjectCaObject.cpp"
#line 4 "Generic.sip"
#include <Generic.h>
#line 12 "Generic.sip"
#include <Generic.h>
#line 25 "sipCaFrameworkcaobjectCaObject.cpp"
#line 4 "MappedType.sip"
#include <string>
#line 28 "sipCaFrameworkcaobjectCaObject.cpp"


class sipcaobject_CaObject : public caobject::CaObject
{
public:
    sipcaobject_CaObject();
    sipcaobject_CaObject(const caobject::CaObject&);
    virtual ~sipcaobject_CaObject();

    /*
     * There is a public method for every protected method visible from
     * this class.
     */
    bool sipProtect_isFirstUpdate();
    void * sipProtect_getRecordCopyPtr();
    int sipProtect_getEnumStateCount();
    std::string sipProtect_getEnumState(int);
    int sipProtect_getPrecision();
    double sipProtect_getDisplayUpper();
    double sipProtect_getDisplayLower();
    double sipProtect_getAlarmUpper();
    double sipProtect_getAlarmLower();
    double sipProtect_getWarningUpper();
    double sipProtect_getWarningLower();
    double sipProtect_getControlUpper();
    double sipProtect_getControlLower();
    std::string sipProtect_getUnits();
    generic::generic_types sipProtect_getType();
    unsigned long sipProtect_getTimeStampSeconds();
    unsigned long sipProtect_getTimeStampNanoseconds();
    short sipProtect_getAlarmStatus();
    short sipProtect_getAlarmSeverity();

    /*
     * There is a protected method for every virtual method visible from
     * this class.
     */
protected:
    void signalCallback(caobject::callback_reasons);

public:
    sipSimpleWrapper *sipPySelf;

private:
    sipcaobject_CaObject(const sipcaobject_CaObject &);
    sipcaobject_CaObject &operator = (const sipcaobject_CaObject &);

    char sipPyMethods[1];
};

sipcaobject_CaObject::sipcaobject_CaObject(): caobject::CaObject(), sipPySelf(0)
{
    memset(sipPyMethods, 0, sizeof (sipPyMethods));
}

sipcaobject_CaObject::sipcaobject_CaObject(const caobject::CaObject& a0): caobject::CaObject(a0), sipPySelf(0)
{
    memset(sipPyMethods, 0, sizeof (sipPyMethods));
}

sipcaobject_CaObject::~sipcaobject_CaObject()
{
    sipCommonDtor(sipPySelf);
}

void sipcaobject_CaObject::signalCallback(caobject::callback_reasons a0)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[0],sipPySelf,sipName_CaObject,sipName_signalCallback);

    if (!meth)
        return;

    extern void sipVH_CaFramework_1(sip_gilstate_t,PyObject *,caobject::callback_reasons);

    sipVH_CaFramework_1(sipGILState,meth,a0);
}

bool sipcaobject_CaObject::sipProtect_isFirstUpdate()
{
    return caobject::CaObject::isFirstUpdate();
}

void * sipcaobject_CaObject::sipProtect_getRecordCopyPtr()
{
    return caobject::CaObject::getRecordCopyPtr();
}

int sipcaobject_CaObject::sipProtect_getEnumStateCount()
{
    return caobject::CaObject::getEnumStateCount();
}

std::string sipcaobject_CaObject::sipProtect_getEnumState(int a0)
{
    return caobject::CaObject::getEnumState(a0);
}

int sipcaobject_CaObject::sipProtect_getPrecision()
{
    return caobject::CaObject::getPrecision();
}

double sipcaobject_CaObject::sipProtect_getDisplayUpper()
{
    return caobject::CaObject::getDisplayUpper();
}

double sipcaobject_CaObject::sipProtect_getDisplayLower()
{
    return caobject::CaObject::getDisplayLower();
}

double sipcaobject_CaObject::sipProtect_getAlarmUpper()
{
    return caobject::CaObject::getAlarmUpper();
}

double sipcaobject_CaObject::sipProtect_getAlarmLower()
{
    return caobject::CaObject::getAlarmLower();
}

double sipcaobject_CaObject::sipProtect_getWarningUpper()
{
    return caobject::CaObject::getWarningUpper();
}

double sipcaobject_CaObject::sipProtect_getWarningLower()
{
    return caobject::CaObject::getWarningLower();
}

double sipcaobject_CaObject::sipProtect_getControlUpper()
{
    return caobject::CaObject::getControlUpper();
}

double sipcaobject_CaObject::sipProtect_getControlLower()
{
    return caobject::CaObject::getControlLower();
}

std::string sipcaobject_CaObject::sipProtect_getUnits()
{
    return caobject::CaObject::getUnits();
}

generic::generic_types sipcaobject_CaObject::sipProtect_getType()
{
    return caobject::CaObject::getType();
}

unsigned long sipcaobject_CaObject::sipProtect_getTimeStampSeconds()
{
    return caobject::CaObject::getTimeStampSeconds();
}

unsigned long sipcaobject_CaObject::sipProtect_getTimeStampNanoseconds()
{
    return caobject::CaObject::getTimeStampNanoseconds();
}

short sipcaobject_CaObject::sipProtect_getAlarmStatus()
{
    return caobject::CaObject::getAlarmStatus();
}

short sipcaobject_CaObject::sipProtect_getAlarmSeverity()
{
    return caobject::CaObject::getAlarmSeverity();
}


extern "C" {static PyObject *meth_caobject_CaObject_setWriteWithCallback(PyObject *, PyObject *);}
static PyObject *meth_caobject_CaObject_setWriteWithCallback(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        bool a0;
        caobject::CaObject *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bb", &sipSelf, sipType_caobject_CaObject, &sipCpp, &a0))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp->setWriteWithCallback(a0);
            Py_END_ALLOW_THREADS

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_CaObject, sipName_setWriteWithCallback, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_caobject_CaObject_getWriteWithCallback(PyObject *, PyObject *);}
static PyObject *meth_caobject_CaObject_getWriteWithCallback(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        caobject::CaObject *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_caobject_CaObject, &sipCpp))
        {
            bool sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = sipCpp->getWriteWithCallback();
            Py_END_ALLOW_THREADS

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_CaObject, sipName_getWriteWithCallback, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_caobject_CaObject_initialise(PyObject *, PyObject *);}
static PyObject *meth_caobject_CaObject_initialise(PyObject *, PyObject *)
{

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(NULL, sipName_CaObject, sipName_initialise, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_caobject_CaObject_shutdown(PyObject *, PyObject *);}
static PyObject *meth_caobject_CaObject_shutdown(PyObject *, PyObject *)
{

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(NULL, sipName_CaObject, sipName_shutdown, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_caobject_CaObject_isFirstUpdate(PyObject *, PyObject *);}
static PyObject *meth_caobject_CaObject_isFirstUpdate(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        sipcaobject_CaObject *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_caobject_CaObject, &sipCpp))
        {
            bool sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = sipCpp->sipProtect_isFirstUpdate();
            Py_END_ALLOW_THREADS

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_CaObject, sipName_isFirstUpdate, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_caobject_CaObject_getRecordCopyPtr(PyObject *, PyObject *);}
static PyObject *meth_caobject_CaObject_getRecordCopyPtr(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        sipcaobject_CaObject *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_caobject_CaObject, &sipCpp))
        {
            void *sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = sipCpp->sipProtect_getRecordCopyPtr();
            Py_END_ALLOW_THREADS

            return sipConvertFromVoidPtr(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_CaObject, sipName_getRecordCopyPtr, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_caobject_CaObject_getEnumStateCount(PyObject *, PyObject *);}
static PyObject *meth_caobject_CaObject_getEnumStateCount(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        sipcaobject_CaObject *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_caobject_CaObject, &sipCpp))
        {
            int sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = sipCpp->sipProtect_getEnumStateCount();
            Py_END_ALLOW_THREADS

            return SIPLong_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_CaObject, sipName_getEnumStateCount, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_caobject_CaObject_getEnumState(PyObject *, PyObject *);}
static PyObject *meth_caobject_CaObject_getEnumState(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        int a0;
        sipcaobject_CaObject *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bi", &sipSelf, sipType_caobject_CaObject, &sipCpp, &a0))
        {
            std::string *sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = new std::string(sipCpp->sipProtect_getEnumState(a0));
            Py_END_ALLOW_THREADS

            return sipConvertFromNewType(sipRes,sipType_std_string,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_CaObject, sipName_getEnumState, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_caobject_CaObject_getPrecision(PyObject *, PyObject *);}
static PyObject *meth_caobject_CaObject_getPrecision(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        sipcaobject_CaObject *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_caobject_CaObject, &sipCpp))
        {
            int sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = sipCpp->sipProtect_getPrecision();
            Py_END_ALLOW_THREADS

            return SIPLong_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_CaObject, sipName_getPrecision, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_caobject_CaObject_getDisplayUpper(PyObject *, PyObject *);}
static PyObject *meth_caobject_CaObject_getDisplayUpper(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        sipcaobject_CaObject *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_caobject_CaObject, &sipCpp))
        {
            double sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = sipCpp->sipProtect_getDisplayUpper();
            Py_END_ALLOW_THREADS

            return PyFloat_FromDouble(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_CaObject, sipName_getDisplayUpper, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_caobject_CaObject_getDisplayLower(PyObject *, PyObject *);}
static PyObject *meth_caobject_CaObject_getDisplayLower(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        sipcaobject_CaObject *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_caobject_CaObject, &sipCpp))
        {
            double sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = sipCpp->sipProtect_getDisplayLower();
            Py_END_ALLOW_THREADS

            return PyFloat_FromDouble(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_CaObject, sipName_getDisplayLower, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_caobject_CaObject_getAlarmUpper(PyObject *, PyObject *);}
static PyObject *meth_caobject_CaObject_getAlarmUpper(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        sipcaobject_CaObject *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_caobject_CaObject, &sipCpp))
        {
            double sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = sipCpp->sipProtect_getAlarmUpper();
            Py_END_ALLOW_THREADS

            return PyFloat_FromDouble(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_CaObject, sipName_getAlarmUpper, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_caobject_CaObject_getAlarmLower(PyObject *, PyObject *);}
static PyObject *meth_caobject_CaObject_getAlarmLower(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        sipcaobject_CaObject *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_caobject_CaObject, &sipCpp))
        {
            double sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = sipCpp->sipProtect_getAlarmLower();
            Py_END_ALLOW_THREADS

            return PyFloat_FromDouble(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_CaObject, sipName_getAlarmLower, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_caobject_CaObject_getWarningUpper(PyObject *, PyObject *);}
static PyObject *meth_caobject_CaObject_getWarningUpper(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        sipcaobject_CaObject *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_caobject_CaObject, &sipCpp))
        {
            double sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = sipCpp->sipProtect_getWarningUpper();
            Py_END_ALLOW_THREADS

            return PyFloat_FromDouble(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_CaObject, sipName_getWarningUpper, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_caobject_CaObject_getWarningLower(PyObject *, PyObject *);}
static PyObject *meth_caobject_CaObject_getWarningLower(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        sipcaobject_CaObject *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_caobject_CaObject, &sipCpp))
        {
            double sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = sipCpp->sipProtect_getWarningLower();
            Py_END_ALLOW_THREADS

            return PyFloat_FromDouble(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_CaObject, sipName_getWarningLower, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_caobject_CaObject_getControlUpper(PyObject *, PyObject *);}
static PyObject *meth_caobject_CaObject_getControlUpper(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        sipcaobject_CaObject *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_caobject_CaObject, &sipCpp))
        {
            double sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = sipCpp->sipProtect_getControlUpper();
            Py_END_ALLOW_THREADS

            return PyFloat_FromDouble(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_CaObject, sipName_getControlUpper, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_caobject_CaObject_getControlLower(PyObject *, PyObject *);}
static PyObject *meth_caobject_CaObject_getControlLower(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        sipcaobject_CaObject *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_caobject_CaObject, &sipCpp))
        {
            double sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = sipCpp->sipProtect_getControlLower();
            Py_END_ALLOW_THREADS

            return PyFloat_FromDouble(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_CaObject, sipName_getControlLower, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_caobject_CaObject_getUnits(PyObject *, PyObject *);}
static PyObject *meth_caobject_CaObject_getUnits(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        sipcaobject_CaObject *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_caobject_CaObject, &sipCpp))
        {
            std::string *sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = new std::string(sipCpp->sipProtect_getUnits());
            Py_END_ALLOW_THREADS

            return sipConvertFromNewType(sipRes,sipType_std_string,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_CaObject, sipName_getUnits, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_caobject_CaObject_getType(PyObject *, PyObject *);}
static PyObject *meth_caobject_CaObject_getType(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        sipcaobject_CaObject *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_caobject_CaObject, &sipCpp))
        {
            generic::generic_types sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = sipCpp->sipProtect_getType();
            Py_END_ALLOW_THREADS

            return sipConvertFromEnum(sipRes,sipType_generic_generic_types);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_CaObject, sipName_getType, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_caobject_CaObject_getTimeStampSeconds(PyObject *, PyObject *);}
static PyObject *meth_caobject_CaObject_getTimeStampSeconds(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        sipcaobject_CaObject *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_caobject_CaObject, &sipCpp))
        {
            unsigned long sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = sipCpp->sipProtect_getTimeStampSeconds();
            Py_END_ALLOW_THREADS

            return PyLong_FromUnsignedLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_CaObject, sipName_getTimeStampSeconds, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_caobject_CaObject_getTimeStampNanoseconds(PyObject *, PyObject *);}
static PyObject *meth_caobject_CaObject_getTimeStampNanoseconds(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        sipcaobject_CaObject *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_caobject_CaObject, &sipCpp))
        {
            unsigned long sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = sipCpp->sipProtect_getTimeStampNanoseconds();
            Py_END_ALLOW_THREADS

            return PyLong_FromUnsignedLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_CaObject, sipName_getTimeStampNanoseconds, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_caobject_CaObject_getAlarmStatus(PyObject *, PyObject *);}
static PyObject *meth_caobject_CaObject_getAlarmStatus(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        sipcaobject_CaObject *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_caobject_CaObject, &sipCpp))
        {
            short sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = sipCpp->sipProtect_getAlarmStatus();
            Py_END_ALLOW_THREADS

            return SIPLong_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_CaObject, sipName_getAlarmStatus, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_caobject_CaObject_getAlarmSeverity(PyObject *, PyObject *);}
static PyObject *meth_caobject_CaObject_getAlarmSeverity(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        sipcaobject_CaObject *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_caobject_CaObject, &sipCpp))
        {
            short sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = sipCpp->sipProtect_getAlarmSeverity();
            Py_END_ALLOW_THREADS

            return SIPLong_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_CaObject, sipName_getAlarmSeverity, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_caobject_CaObject_signalCallback(PyObject *, PyObject *);}
static PyObject *meth_caobject_CaObject_signalCallback(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    PyObject *sipOrigSelf = sipSelf;

    {
        caobject::callback_reasons a0;
        caobject::CaObject *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BE", &sipSelf, sipType_caobject_CaObject, &sipCpp, sipType_caobject_callback_reasons, &a0))
        {
            if (!sipOrigSelf)
            {
                sipAbstractMethod(sipName_CaObject, sipName_signalCallback);
                return NULL;
            }

            Py_BEGIN_ALLOW_THREADS
            sipCpp->signalCallback(a0);
            Py_END_ALLOW_THREADS

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_CaObject, sipName_signalCallback, NULL);

    return NULL;
}


/* Cast a pointer to a type somewhere in its superclass hierarchy. */
extern "C" {static void *cast_caobject_CaObject(void *, const sipTypeDef *);}
static void *cast_caobject_CaObject(void *ptr, const sipTypeDef *targetType)
{
    if (targetType == sipType_caobject_CaObject)
        return ptr;

    return NULL;
}


/* Call the instance's destructor. */
extern "C" {static void release_caobject_CaObject(void *, int);}
static void release_caobject_CaObject(void *sipCppV,int sipState)
{
    Py_BEGIN_ALLOW_THREADS

    if (sipState & SIP_DERIVED_CLASS)
        delete reinterpret_cast<sipcaobject_CaObject *>(sipCppV);
    else
        delete reinterpret_cast<caobject::CaObject *>(sipCppV);

    Py_END_ALLOW_THREADS
}


extern "C" {static void dealloc_caobject_CaObject(sipSimpleWrapper *);}
static void dealloc_caobject_CaObject(sipSimpleWrapper *sipSelf)
{
    if (sipIsDerived(sipSelf))
        reinterpret_cast<sipcaobject_CaObject *>(sipSelf->u.cppPtr)->sipPySelf = NULL;

    if (sipIsPyOwned(sipSelf))
    {
        release_caobject_CaObject(sipSelf->u.cppPtr,sipSelf->flags);
    }
}


extern "C" {static void *init_caobject_CaObject(sipSimpleWrapper *, PyObject *, PyObject *, PyObject **, PyObject **, PyObject **);}
static void *init_caobject_CaObject(sipSimpleWrapper *sipSelf, PyObject *sipArgs, PyObject *sipKwds, PyObject **sipUnused, PyObject **, PyObject **sipParseErr)
{
    sipcaobject_CaObject *sipCpp = 0;

    {
        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, NULL, sipUnused, ""))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp = new sipcaobject_CaObject();
            Py_END_ALLOW_THREADS

            sipCpp->sipPySelf = sipSelf;

            return sipCpp;
        }
    }

    {
        const caobject::CaObject * a0;

        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, NULL, sipUnused, "J9", sipType_caobject_CaObject, &a0))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp = new sipcaobject_CaObject(*a0);
            Py_END_ALLOW_THREADS

            sipCpp->sipPySelf = sipSelf;

            return sipCpp;
        }
    }

    return NULL;
}


static PyMethodDef methods_caobject_CaObject[] = {
    {SIP_MLNAME_CAST(sipName_getAlarmLower), meth_caobject_CaObject_getAlarmLower, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_getAlarmSeverity), meth_caobject_CaObject_getAlarmSeverity, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_getAlarmStatus), meth_caobject_CaObject_getAlarmStatus, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_getAlarmUpper), meth_caobject_CaObject_getAlarmUpper, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_getControlLower), meth_caobject_CaObject_getControlLower, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_getControlUpper), meth_caobject_CaObject_getControlUpper, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_getDisplayLower), meth_caobject_CaObject_getDisplayLower, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_getDisplayUpper), meth_caobject_CaObject_getDisplayUpper, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_getEnumState), meth_caobject_CaObject_getEnumState, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_getEnumStateCount), meth_caobject_CaObject_getEnumStateCount, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_getPrecision), meth_caobject_CaObject_getPrecision, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_getRecordCopyPtr), meth_caobject_CaObject_getRecordCopyPtr, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_getTimeStampNanoseconds), meth_caobject_CaObject_getTimeStampNanoseconds, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_getTimeStampSeconds), meth_caobject_CaObject_getTimeStampSeconds, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_getType), meth_caobject_CaObject_getType, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_getUnits), meth_caobject_CaObject_getUnits, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_getWarningLower), meth_caobject_CaObject_getWarningLower, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_getWarningUpper), meth_caobject_CaObject_getWarningUpper, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_getWriteWithCallback), meth_caobject_CaObject_getWriteWithCallback, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_initialise), meth_caobject_CaObject_initialise, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_isFirstUpdate), meth_caobject_CaObject_isFirstUpdate, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_setWriteWithCallback), meth_caobject_CaObject_setWriteWithCallback, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_shutdown), meth_caobject_CaObject_shutdown, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_signalCallback), meth_caobject_CaObject_signalCallback, METH_VARARGS, NULL}
};


extern "C" {static PyObject *varget_caobject_CaObject_priPtr(void *, PyObject *);}
static PyObject *varget_caobject_CaObject_priPtr(void *sipSelf, PyObject *)
{
    void *sipVal;
    caobject::CaObject *sipCpp = reinterpret_cast<caobject::CaObject *>(sipSelf);

    sipVal = sipCpp->priPtr;

    return sipConvertFromVoidPtr(sipVal);
}


extern "C" {static int varset_caobject_CaObject_priPtr(void *, PyObject *, PyObject *);}
static int varset_caobject_CaObject_priPtr(void *sipSelf, PyObject *sipPy, PyObject *)
{
    void *sipVal;
    caobject::CaObject *sipCpp = reinterpret_cast<caobject::CaObject *>(sipSelf);

    sipVal = sipConvertToVoidPtr(sipPy);

    if (PyErr_Occurred() != NULL)
        return -1;

    sipCpp->priPtr = sipVal;

    return 0;
}

sipVariableDef variables_caobject_CaObject[] = {
    {sipName_priPtr, varget_caobject_CaObject_priPtr, varset_caobject_CaObject_priPtr, 0},
};


pyqt4ClassTypeDef sipTypeDef_CaFramework_caobject_CaObject = {
{
    {
        -1,
        0,
        0,
        SIP_TYPE_ABSTRACT|SIP_TYPE_CLASS,
        sipNameNr_caobject__CaObject,
        {0}
    },
    {
        sipNameNr_CaObject,
        {22, 255, 0},
        24, methods_caobject_CaObject,
        0, 0,
        1, variables_caobject_CaObject,
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    },
    0,
    sipNameNr_PyQt4_QtCore_pyqtWrapperType,
    -1,
    0,
    0,
    init_caobject_CaObject,
    0,
    0,
#if PY_MAJOR_VERSION >= 3
    0,
    0,
#else
    0,
    0,
    0,
    0,
#endif
    dealloc_caobject_CaObject,
    0,
    0,
    0,
    release_caobject_CaObject,
    cast_caobject_CaObject,
    0,
    0,
    0
},
    0,
    0,
    0
};
