/*
 * Interface wrapper code.
 *
 * Generated by SIP 4.10.2 on Fri Apr 22 17:31:55 2011
 */

#include "sipAPICaFramework.h"

#line 4 "Generic.sip"
#include <Generic.h>
#line 12 "Generic.sip"
#include <Generic.h>
#line 14 "sipCaFrameworkgeneric.cpp"


static sipEnumMemberDef enummembers_generic[] = {
    {sipName_CHAR, generic::CHAR, 32},
    {sipName_DOUBLE, generic::DOUBLE, 32},
    {sipName_SHORT, generic::SHORT, 32},
    {sipName_STRING, generic::STRING, 32},
    {sipName_UNKNOWN, generic::UNKNOWN, 32},
    {sipName_UNSIGNED_LONG, generic::UNSIGNED_LONG, 32},
};


pyqt4ClassTypeDef sipTypeDef_CaFramework_generic = {
{
    {
        -1,
        0,
        0,
        SIP_TYPE_NAMESPACE,
        sipNameNr_generic,
        {0}
    },
    {
        sipNameNr_generic,
        {0, 0, 1},
        0, 0,
        6, enummembers_generic,
        0, 0,
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    },
    0,
    -1,
    -1,
    0,
    0,
    0,
    0,
    0,
#if PY_MAJOR_VERSION >= 3
    0,
    0,
#else
    0,
    0,
    0,
    0,
#endif
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0
},
    0,
    0,
    0
};
