all: clean  BasePlusCommissionEmployee564

BasePlusCommissionEmployee564:
	$(CXX) BasePlusCommissionEmployee564.cpp CommissionEmployee564.cpp BasePlusCommissionEmployee564_main.cpp Employee564.cpp SalariedEmployee564.cpp -o BasePlusCommissionEmployee564

clean:
	rm -f BasePlusCommissionEmployee564:
