/*
 * Interface wrapper code.
 *
 * Generated by SIP 4.10.2 on Mon Mar 28 16:23:16 2011
 *
 * Copyright (c) 2007
 * 	Riverbank Computing Limited <info@riverbankcomputing.co.uk>
 * 
 * This file is part of PyQt.
 * 
 * This copy of PyQt is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the Free
 * Software Foundation; either version 2, or (at your option) any later
 * version.
 * 
 * PyQt is supplied in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
 * details.
 * 
 * You should have received a copy of the GNU General Public License along with
 * PyQt; see the file LICENSE.  If not, write to the Free Software Foundation,
 * Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 */

#include "sipAPIqt.h"

#line 1024 "/usr/share/sip/qt/qevent.sip"
#include <qevent.h>
#line 31 "sipqtQDropEvent.cc"

#line 57 "/usr/share/sip/qt/qpoint.sip"
#include <qpoint.h>
#line 35 "sipqtQDropEvent.cc"
#line 324 "/usr/share/sip/qt/qevent.sip"
#include <qevent.h>
#line 38 "sipqtQDropEvent.cc"
#line 98 "/usr/share/sip/qt/qbytearray.sip"
#include <qstring.h>
#line 41 "sipqtQDropEvent.cc"
#line 63 "/usr/share/sip/qt/qwidget.sip"
#include <qwidget.h>
#line 44 "sipqtQDropEvent.cc"


class sipQDropEvent : public QDropEvent
{
public:
    sipQDropEvent(const QPoint&,QEvent::Type);
    sipQDropEvent(const QDropEvent&);
    virtual ~sipQDropEvent();

    /*
     * There is a protected method for every virtual method visible from
     * this class.
     */
protected:
    const char * format(int) const;
    bool provides(const char *) const;
    QByteArray encodedData(const char *) const;

public:
    sipSimpleWrapper *sipPySelf;

private:
    sipQDropEvent(const sipQDropEvent &);
    sipQDropEvent &operator = (const sipQDropEvent &);

    char sipPyMethods[3];
};

sipQDropEvent::sipQDropEvent(const QPoint& a0,QEvent::Type a1): QDropEvent(a0,a1), sipPySelf(0)
{
    memset(sipPyMethods, 0, sizeof (sipPyMethods));
}

sipQDropEvent::sipQDropEvent(const QDropEvent& a0): QDropEvent(a0), sipPySelf(0)
{
    memset(sipPyMethods, 0, sizeof (sipPyMethods));
}

sipQDropEvent::~sipQDropEvent()
{
    sipCommonDtor(sipPySelf);
}

const char * sipQDropEvent::format(int a0) const
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[0]),sipPySelf,NULL,sipName_format);

    if (!meth)
        return QDropEvent::format(a0);

    extern const char * sipVH_qt_196(sip_gilstate_t,PyObject *,int,int,sipSimpleWrapper *);

    return sipVH_qt_196(sipGILState,meth,a0,6,sipPySelf);
}

bool sipQDropEvent::provides(const char *a0) const
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[1]),sipPySelf,NULL,sipName_provides);

    if (!meth)
        return QDropEvent::provides(a0);

    extern bool sipVH_qt_195(sip_gilstate_t,PyObject *,const char *);

    return sipVH_qt_195(sipGILState,meth,a0);
}

QByteArray sipQDropEvent::encodedData(const char *a0) const
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[2]),sipPySelf,NULL,sipName_encodedData);

    if (!meth)
        return QDropEvent::encodedData(a0);

    extern QByteArray sipVH_qt_194(sip_gilstate_t,PyObject *,const char *);

    return sipVH_qt_194(sipGILState,meth,a0);
}


extern "C" {static PyObject *meth_QDropEvent_pos(PyObject *, PyObject *);}
static PyObject *meth_QDropEvent_pos(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QDropEvent *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QDropEvent, &sipCpp))
        {
            QPoint *sipRes;

            sipRes = new QPoint(sipCpp->pos());

            return sipConvertFromNewType(sipRes,sipType_QPoint,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QDropEvent, sipName_pos, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QDropEvent_isAccepted(PyObject *, PyObject *);}
static PyObject *meth_QDropEvent_isAccepted(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QDropEvent *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QDropEvent, &sipCpp))
        {
            bool sipRes;

            sipRes = sipCpp->isAccepted();

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QDropEvent, sipName_isAccepted, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QDropEvent_accept(PyObject *, PyObject *);}
static PyObject *meth_QDropEvent_accept(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        bool a0 = 1;
        QDropEvent *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B|b", &sipSelf, sipType_QDropEvent, &sipCpp, &a0))
        {
            sipCpp->accept(a0);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QDropEvent, sipName_accept, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QDropEvent_ignore(PyObject *, PyObject *);}
static PyObject *meth_QDropEvent_ignore(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QDropEvent *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QDropEvent, &sipCpp))
        {
            sipCpp->ignore();

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QDropEvent, sipName_ignore, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QDropEvent_isActionAccepted(PyObject *, PyObject *);}
static PyObject *meth_QDropEvent_isActionAccepted(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QDropEvent *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QDropEvent, &sipCpp))
        {
            bool sipRes;

            sipRes = sipCpp->isActionAccepted();

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QDropEvent, sipName_isActionAccepted, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QDropEvent_acceptAction(PyObject *, PyObject *);}
static PyObject *meth_QDropEvent_acceptAction(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        bool a0 = 1;
        QDropEvent *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B|b", &sipSelf, sipType_QDropEvent, &sipCpp, &a0))
        {
            sipCpp->acceptAction(a0);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QDropEvent, sipName_acceptAction, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QDropEvent_setAction(PyObject *, PyObject *);}
static PyObject *meth_QDropEvent_setAction(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QDropEvent::Action a0;
        QDropEvent *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BE", &sipSelf, sipType_QDropEvent, &sipCpp, sipType_QDropEvent_Action, &a0))
        {
            sipCpp->setAction(a0);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QDropEvent, sipName_setAction, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QDropEvent_action(PyObject *, PyObject *);}
static PyObject *meth_QDropEvent_action(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QDropEvent *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QDropEvent, &sipCpp))
        {
            QDropEvent::Action sipRes;

            sipRes = sipCpp->action();

            return sipConvertFromEnum(sipRes,sipType_QDropEvent_Action);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QDropEvent, sipName_action, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QDropEvent_source(PyObject *, PyObject *);}
static PyObject *meth_QDropEvent_source(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QDropEvent *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QDropEvent, &sipCpp))
        {
            QWidget *sipRes;

            sipRes = sipCpp->source();

            return sipConvertFromType(sipRes,sipType_QWidget,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QDropEvent, sipName_source, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QDropEvent_format(PyObject *, PyObject *);}
static PyObject *meth_QDropEvent_format(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        int a0 = 0;
        QDropEvent *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B|i", &sipSelf, sipType_QDropEvent, &sipCpp, &a0))
        {
            const char *sipRes;

            sipRes = (sipSelfWasArg ? sipCpp->QDropEvent::format(a0) : sipCpp->format(a0));

            if (sipRes == NULL)
            {
                Py_INCREF(Py_None);
                return Py_None;
            }

            return SIPBytes_FromString(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QDropEvent, sipName_format, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QDropEvent_encodedData(PyObject *, PyObject *);}
static PyObject *meth_QDropEvent_encodedData(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        const char * a0;
        QDropEvent *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bs", &sipSelf, sipType_QDropEvent, &sipCpp, &a0))
        {
            QByteArray *sipRes;

            sipRes = new QByteArray((sipSelfWasArg ? sipCpp->QDropEvent::encodedData(a0) : sipCpp->encodedData(a0)));

            return sipConvertFromNewType(sipRes,sipType_QByteArray,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QDropEvent, sipName_encodedData, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QDropEvent_provides(PyObject *, PyObject *);}
static PyObject *meth_QDropEvent_provides(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        const char * a0;
        QDropEvent *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bs", &sipSelf, sipType_QDropEvent, &sipCpp, &a0))
        {
            bool sipRes;

            sipRes = (sipSelfWasArg ? sipCpp->QDropEvent::provides(a0) : sipCpp->provides(a0));

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QDropEvent, sipName_provides, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QDropEvent_data(PyObject *, PyObject *);}
static PyObject *meth_QDropEvent_data(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const char * a0;
        QDropEvent *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bs", &sipSelf, sipType_QDropEvent, &sipCpp, &a0))
        {
            QByteArray *sipRes;

            sipRes = new QByteArray(sipCpp->data(a0));

            return sipConvertFromNewType(sipRes,sipType_QByteArray,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QDropEvent, sipName_data, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QDropEvent_setPoint(PyObject *, PyObject *);}
static PyObject *meth_QDropEvent_setPoint(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const QPoint * a0;
        QDropEvent *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ9", &sipSelf, sipType_QDropEvent, &sipCpp, sipType_QPoint, &a0))
        {
            sipCpp->setPoint(*a0);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QDropEvent, sipName_setPoint, NULL);

    return NULL;
}


/* Cast a pointer to a type somewhere in its superclass hierarchy. */
extern "C" {static void *cast_QDropEvent(void *, const sipTypeDef *);}
static void *cast_QDropEvent(void *ptr, const sipTypeDef *targetType)
{
    void *res;

    if (targetType == sipType_QDropEvent)
        return ptr;

    if ((res = ((const sipClassTypeDef *)sipType_QEvent)->ctd_cast((QEvent *)(QDropEvent *)ptr,targetType)) != NULL)
        return res;

    if ((res = ((const sipClassTypeDef *)sipType_QMimeSource)->ctd_cast((QMimeSource *)(QDropEvent *)ptr,targetType)) != NULL)
        return res;

    return NULL;
}


/* Call the instance's destructor. */
extern "C" {static void release_QDropEvent(void *, int);}
static void release_QDropEvent(void *sipCppV,int sipState)
{
    if (sipState & SIP_DERIVED_CLASS)
        delete reinterpret_cast<sipQDropEvent *>(sipCppV);
    else
        delete reinterpret_cast<QDropEvent *>(sipCppV);
}


extern "C" {static void dealloc_QDropEvent(sipSimpleWrapper *);}
static void dealloc_QDropEvent(sipSimpleWrapper *sipSelf)
{
    if (sipIsDerived(sipSelf))
        reinterpret_cast<sipQDropEvent *>(sipSelf->u.cppPtr)->sipPySelf = NULL;

    if (sipIsPyOwned(sipSelf))
    {
        release_QDropEvent(sipSelf->u.cppPtr,sipSelf->flags);
    }
}


extern "C" {static void *init_QDropEvent(sipSimpleWrapper *, PyObject *, PyObject *, PyObject **, PyObject **, PyObject **);}
static void *init_QDropEvent(sipSimpleWrapper *sipSelf, PyObject *sipArgs, PyObject *sipKwds, PyObject **sipUnused, PyObject **, PyObject **sipParseErr)
{
    sipQDropEvent *sipCpp = 0;

    {
        const QPoint * a0;
        QEvent::Type a1 = QEvent::Drop;

        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, NULL, sipUnused, "J9|E", sipType_QPoint, &a0, sipType_QEvent_Type, &a1))
        {
            sipCpp = new sipQDropEvent(*a0,a1);

            sipCpp->sipPySelf = sipSelf;

            return sipCpp;
        }
    }

    {
        const QDropEvent * a0;

        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, NULL, sipUnused, "J9", sipType_QDropEvent, &a0))
        {
            sipCpp = new sipQDropEvent(*a0);

            sipCpp->sipPySelf = sipSelf;

            return sipCpp;
        }
    }

    return NULL;
}


/* Define this type's super-types. */
static sipEncodedTypeDef supers_QDropEvent[] = {{76, 255, 0}, {184, 255, 1}};


static PyMethodDef methods_QDropEvent[] = {
    {SIP_MLNAME_CAST(sipName_accept), meth_QDropEvent_accept, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_acceptAction), meth_QDropEvent_acceptAction, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_action), meth_QDropEvent_action, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_data), meth_QDropEvent_data, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_encodedData), meth_QDropEvent_encodedData, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_format), meth_QDropEvent_format, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_ignore), meth_QDropEvent_ignore, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_isAccepted), meth_QDropEvent_isAccepted, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_isActionAccepted), meth_QDropEvent_isActionAccepted, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_pos), meth_QDropEvent_pos, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_provides), meth_QDropEvent_provides, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_setAction), meth_QDropEvent_setAction, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_setPoint), meth_QDropEvent_setPoint, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_source), meth_QDropEvent_source, METH_VARARGS, NULL}
};

static sipEnumMemberDef enummembers_QDropEvent[] = {
    {sipName_Copy, QDropEvent::Copy, 73},
    {sipName_Link, QDropEvent::Link, 73},
    {sipName_Move, QDropEvent::Move, 73},
    {sipName_Private, QDropEvent::Private, 73},
    {sipName_UserAction, QDropEvent::UserAction, 73},
};


pyqt3ClassTypeDef sipTypeDef_qt_QDropEvent = {
{
    {
        -1,
        0,
        0,
        SIP_TYPE_SCC|SIP_TYPE_CLASS,
        sipNameNr_QDropEvent,
        {0}
    },
    {
        sipNameNr_QDropEvent,
        {0, 0, 1},
        14, methods_QDropEvent,
        5, enummembers_QDropEvent,
        0, 0,
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    },
    0,
    -1,
    -1,
    supers_QDropEvent,
    0,
    init_QDropEvent,
    0,
    0,
#if PY_MAJOR_VERSION >= 3
    0,
    0,
#else
    0,
    0,
    0,
    0,
#endif
    dealloc_QDropEvent,
    0,
    0,
    0,
    release_QDropEvent,
    cast_QDropEvent,
    0,
    0,
    0
},
    0
};
