/*
 * Interface wrapper code.
 *
 * Generated by SIP 4.10.2 on Mon Mar 28 16:23:16 2011
 *
 * Copyright (c) 2007
 * 	Riverbank Computing Limited <info@riverbankcomputing.co.uk>
 * 
 * This file is part of PyQt.
 * 
 * This copy of PyQt is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the Free
 * Software Foundation; either version 2, or (at your option) any later
 * version.
 * 
 * PyQt is supplied in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
 * details.
 * 
 * You should have received a copy of the GNU General Public License along with
 * PyQt; see the file LICENSE.  If not, write to the Free Software Foundation,
 * Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 */

#include "sipAPIqt.h"

#line 489 "/usr/share/sip/qt/qlayout.sip"
#include <qlayout.h>
#line 31 "sipqtQBoxLayout.cc"

#line 63 "/usr/share/sip/qt/qwidget.sip"
#include <qwidget.h>
#line 35 "sipqtQBoxLayout.cc"
#line 267 "/usr/share/sip/qt/qlayout.sip"
#include <qabstractlayout.h>
#line 38 "sipqtQBoxLayout.cc"
#line 53 "/usr/share/sip/qt/qmetaobject.sip"
#include <qmetaobject.h>
#line 41 "sipqtQBoxLayout.cc"
#line 180 "/usr/share/sip/qt/qlayout.sip"
#include <qabstractlayout.h>
#line 44 "sipqtQBoxLayout.cc"
#line 93 "/usr/share/sip/qt/qrect.sip"
#include <qrect.h>
#line 47 "sipqtQBoxLayout.cc"
#line 157 "/usr/share/sip/qt/qlayout.sip"
#include <qabstractlayout.h>
#line 50 "sipqtQBoxLayout.cc"
#line 37 "/usr/share/sip/qt/qsizepolicy.sip"
#include <qsizepolicy.h>
#line 53 "sipqtQBoxLayout.cc"
#line 57 "/usr/share/sip/qt/qsize.sip"
#include <qsize.h>
#line 56 "sipqtQBoxLayout.cc"
#line 1138 "/usr/share/sip/qt/qevent.sip"
#include <qevent.h>
#line 59 "sipqtQBoxLayout.cc"
#line 66 "/usr/share/sip/qt/qobject.sip"
#include <qobject.h>
#include <qapplication.h>
#line 63 "sipqtQBoxLayout.cc"
#line 324 "/usr/share/sip/qt/qevent.sip"
#include <qevent.h>
#line 66 "sipqtQBoxLayout.cc"
#line 35 "/usr/share/sip/qt/qmenubar.sip"
#include <qmenubar.h>
#line 69 "sipqtQBoxLayout.cc"
#line 1163 "/usr/share/sip/qt/qevent.sip"
#include <qevent.h>
#line 72 "sipqtQBoxLayout.cc"
#line 582 "/usr/share/sip/qt/qevent.sip"
#include <qevent.h>
#line 75 "sipqtQBoxLayout.cc"
#line 201 "/usr/share/sip/qt/qvariant.sip"
#include <qvariant.h>
#line 78 "sipqtQBoxLayout.cc"
#line 37 "/usr/share/sip/qt/qobjectlist.sip"
#include <qobjectlist.h>
#line 81 "sipqtQBoxLayout.cc"
#line 449 "/usr/share/sip/qt/qstring.sip"
#include <qstring.h>
#line 84 "sipqtQBoxLayout.cc"
#line 221 "/usr/share/sip/qt/qlayout.sip"
#include <qabstractlayout.h>
#line 87 "sipqtQBoxLayout.cc"


class sipQBoxLayout : public QBoxLayout
{
public:
    sipQBoxLayout(QWidget *,QBoxLayout::Direction,int,int,const char *);
    sipQBoxLayout(QLayout *,QBoxLayout::Direction,int,const char *);
    sipQBoxLayout(QBoxLayout::Direction,int,const char *);
    virtual ~sipQBoxLayout();

    /*
     * There is a public method for every protected method visible from
     * this class.
     */
    void sipProtectVirt_timerEvent(bool,QTimerEvent *);
    void sipProtectVirt_customEvent(bool,QCustomEvent *);
    bool sipProtectVirt_eventFilter(bool,QObject *,QEvent *);
    void sipProtectVirt_childEvent(bool,QChildEvent *);
    void sipProtect_addChildLayout(QLayout *);
    void sipProtect_deleteAllItems();
    void sipProtect_setSupportsMargin(bool);
    QRect sipProtect_alignmentRect(const QRect&) const;
    void sipProtect_insertItem(int,QLayoutItem *);

    /*
     * There is a public method for every Qt signal that can be emitted
     * by this object.  This function is called by Python to emit the
     * signal.
     */
    int sipEmit_destroyed(PyObject *);

    /*
     * There is a protected method for every virtual method visible from
     * this class.
     */
protected:
    QMetaObject * metaObject() const;
    void setMargin(int);
    void setSpacing(int);
    void setMenuBar(QMenuBar *);
    void setAutoAdd(bool);
    void addItem(QLayoutItem *);
    bool event(QEvent *);
    bool eventFilter(QObject *,QEvent *);
    void setName(const char *);
    void insertChild(QObject *);
    void removeChild(QObject *);
    bool setProperty(const char *,const QVariant&);
    QVariant property(const char *) const;
    void timerEvent(QTimerEvent *);
    void childEvent(QChildEvent *);
    void customEvent(QCustomEvent *);
    QSize sizeHint() const;
    QSize minimumSize() const;
    QSize maximumSize() const;
    QSizePolicy::ExpandData expanding() const;
    void setGeometry(const QRect&);
    QRect geometry() const;
    bool isEmpty() const;
    bool hasHeightForWidth() const;
    int heightForWidth(int) const;
    void invalidate();
    QWidget * widget();
    QLayoutIterator iterator();
    QLayout * layout();
    QSpacerItem * spacerItem();
    void setAlignment(int);

public:
    sipSimpleWrapper *sipPySelf;

private:
    sipQBoxLayout(const sipQBoxLayout &);
    sipQBoxLayout &operator = (const sipQBoxLayout &);

    char sipPyMethods[31];
};

sipQBoxLayout::sipQBoxLayout(QWidget *a0,QBoxLayout::Direction a1,int a2,int a3,const char *a4): QBoxLayout(a0,a1,a2,a3,a4), sipPySelf(0)
{
    memset(sipPyMethods, 0, sizeof (sipPyMethods));
}

sipQBoxLayout::sipQBoxLayout(QLayout *a0,QBoxLayout::Direction a1,int a2,const char *a3): QBoxLayout(a0,a1,a2,a3), sipPySelf(0)
{
    memset(sipPyMethods, 0, sizeof (sipPyMethods));
}

sipQBoxLayout::sipQBoxLayout(QBoxLayout::Direction a0,int a1,const char *a2): QBoxLayout(a0,a1,a2), sipPySelf(0)
{
    memset(sipPyMethods, 0, sizeof (sipPyMethods));
}

sipQBoxLayout::~sipQBoxLayout()
{
    sipCommonDtor(sipPySelf);
}

QMetaObject * sipQBoxLayout::metaObject() const
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[0]),sipPySelf,NULL,sipName_metaObject);

    if (!meth)
        return QBoxLayout::metaObject();

    extern QMetaObject * sipVH_qt_179(sip_gilstate_t,PyObject *);

    return sipVH_qt_179(sipGILState,meth);
}

void sipQBoxLayout::setMargin(int a0)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[1],sipPySelf,NULL,sipName_setMargin);

    if (!meth)
    {
        QLayout::setMargin(a0);
        return;
    }

    extern void sipVH_qt_68(sip_gilstate_t,PyObject *,int);

    sipVH_qt_68(sipGILState,meth,a0);
}

void sipQBoxLayout::setSpacing(int a0)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[2],sipPySelf,NULL,sipName_setSpacing);

    if (!meth)
    {
        QLayout::setSpacing(a0);
        return;
    }

    extern void sipVH_qt_68(sip_gilstate_t,PyObject *,int);

    sipVH_qt_68(sipGILState,meth,a0);
}

void sipQBoxLayout::setMenuBar(QMenuBar *a0)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[3],sipPySelf,NULL,sipName_setMenuBar);

    if (!meth)
    {
        QLayout::setMenuBar(a0);
        return;
    }

    extern void sipVH_qt_236(sip_gilstate_t,PyObject *,QMenuBar *);

    sipVH_qt_236(sipGILState,meth,a0);
}

void sipQBoxLayout::setAutoAdd(bool a0)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[4],sipPySelf,NULL,sipName_setAutoAdd);

    if (!meth)
    {
        QLayout::setAutoAdd(a0);
        return;
    }

    extern void sipVH_qt_10(sip_gilstate_t,PyObject *,bool);

    sipVH_qt_10(sipGILState,meth,a0);
}

void sipQBoxLayout::addItem(QLayoutItem *a0)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[5],sipPySelf,NULL,sipName_addItem);

    if (!meth)
    {
        QBoxLayout::addItem(a0);
        return;
    }

    extern void sipVH_qt_235(sip_gilstate_t,PyObject *,QLayoutItem *);

    sipVH_qt_235(sipGILState,meth,a0);
}

bool sipQBoxLayout::event(QEvent *a0)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[6],sipPySelf,NULL,sipName_event);

    if (!meth)
        return QObject::event(a0);

    extern bool sipVH_qt_178(sip_gilstate_t,PyObject *,QEvent *);

    return sipVH_qt_178(sipGILState,meth,a0);
}

bool sipQBoxLayout::eventFilter(QObject *a0,QEvent *a1)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[7],sipPySelf,NULL,sipName_eventFilter);

    if (!meth)
        return QLayout::eventFilter(a0,a1);

    extern bool sipVH_qt_177(sip_gilstate_t,PyObject *,QObject *,QEvent *);

    return sipVH_qt_177(sipGILState,meth,a0,a1);
}

void sipQBoxLayout::setName(const char *a0)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[8],sipPySelf,NULL,sipName_setName);

    if (!meth)
    {
        QObject::setName(a0);
        return;
    }

    extern void sipVH_qt_176(sip_gilstate_t,PyObject *,const char *);

    sipVH_qt_176(sipGILState,meth,a0);
}

void sipQBoxLayout::insertChild(QObject *a0)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[9],sipPySelf,NULL,sipName_insertChild);

    if (!meth)
    {
        QObject::insertChild(a0);
        return;
    }

    extern void sipVH_qt_175(sip_gilstate_t,PyObject *,QObject *);

    sipVH_qt_175(sipGILState,meth,a0);
}

void sipQBoxLayout::removeChild(QObject *a0)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[10],sipPySelf,NULL,sipName_removeChild);

    if (!meth)
    {
        QObject::removeChild(a0);
        return;
    }

    extern void sipVH_qt_175(sip_gilstate_t,PyObject *,QObject *);

    sipVH_qt_175(sipGILState,meth,a0);
}

bool sipQBoxLayout::setProperty(const char *a0,const QVariant& a1)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[11],sipPySelf,NULL,sipName_setProperty);

    if (!meth)
        return QObject::setProperty(a0,a1);

    extern bool sipVH_qt_174(sip_gilstate_t,PyObject *,const char *,const QVariant&);

    return sipVH_qt_174(sipGILState,meth,a0,a1);
}

QVariant sipQBoxLayout::property(const char *a0) const
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[12]),sipPySelf,NULL,sipName_property);

    if (!meth)
        return QObject::property(a0);

    extern QVariant sipVH_qt_173(sip_gilstate_t,PyObject *,const char *);

    return sipVH_qt_173(sipGILState,meth,a0);
}

void sipQBoxLayout::timerEvent(QTimerEvent *a0)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[13],sipPySelf,NULL,sipName_timerEvent);

    if (!meth)
    {
        QObject::timerEvent(a0);
        return;
    }

    extern void sipVH_qt_172(sip_gilstate_t,PyObject *,QTimerEvent *);

    sipVH_qt_172(sipGILState,meth,a0);
}

void sipQBoxLayout::childEvent(QChildEvent *a0)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[14],sipPySelf,NULL,sipName_childEvent);

    if (!meth)
    {
        QLayout::childEvent(a0);
        return;
    }

    extern void sipVH_qt_171(sip_gilstate_t,PyObject *,QChildEvent *);

    sipVH_qt_171(sipGILState,meth,a0);
}

void sipQBoxLayout::customEvent(QCustomEvent *a0)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[15],sipPySelf,NULL,sipName_customEvent);

    if (!meth)
    {
        QObject::customEvent(a0);
        return;
    }

    extern void sipVH_qt_170(sip_gilstate_t,PyObject *,QCustomEvent *);

    sipVH_qt_170(sipGILState,meth,a0);
}

QSize sipQBoxLayout::sizeHint() const
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[16]),sipPySelf,NULL,sipName_sizeHint);

    if (!meth)
        return QBoxLayout::sizeHint();

    extern QSize sipVH_qt_47(sip_gilstate_t,PyObject *);

    return sipVH_qt_47(sipGILState,meth);
}

QSize sipQBoxLayout::minimumSize() const
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[17]),sipPySelf,NULL,sipName_minimumSize);

    if (!meth)
        return QBoxLayout::minimumSize();

    extern QSize sipVH_qt_47(sip_gilstate_t,PyObject *);

    return sipVH_qt_47(sipGILState,meth);
}

QSize sipQBoxLayout::maximumSize() const
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[18]),sipPySelf,NULL,sipName_maximumSize);

    if (!meth)
        return QBoxLayout::maximumSize();

    extern QSize sipVH_qt_47(sip_gilstate_t,PyObject *);

    return sipVH_qt_47(sipGILState,meth);
}

QSizePolicy::ExpandData sipQBoxLayout::expanding() const
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[19]),sipPySelf,NULL,sipName_expanding);

    if (!meth)
        return QBoxLayout::expanding();

    extern QSizePolicy::ExpandData sipVH_qt_242(sip_gilstate_t,PyObject *);

    return sipVH_qt_242(sipGILState,meth);
}

void sipQBoxLayout::setGeometry(const QRect& a0)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[20],sipPySelf,NULL,sipName_setGeometry);

    if (!meth)
    {
        QBoxLayout::setGeometry(a0);
        return;
    }

    extern void sipVH_qt_36(sip_gilstate_t,PyObject *,const QRect&);

    sipVH_qt_36(sipGILState,meth,a0);
}

QRect sipQBoxLayout::geometry() const
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[21]),sipPySelf,NULL,sipName_geometry);

    if (!meth)
        return QLayout::geometry();

    extern QRect sipVH_qt_241(sip_gilstate_t,PyObject *);

    return sipVH_qt_241(sipGILState,meth);
}

bool sipQBoxLayout::isEmpty() const
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[22]),sipPySelf,NULL,sipName_isEmpty);

    if (!meth)
        return QLayout::isEmpty();

    extern bool sipVH_qt_42(sip_gilstate_t,PyObject *);

    return sipVH_qt_42(sipGILState,meth);
}

bool sipQBoxLayout::hasHeightForWidth() const
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[23]),sipPySelf,NULL,sipName_hasHeightForWidth);

    if (!meth)
        return QBoxLayout::hasHeightForWidth();

    extern bool sipVH_qt_42(sip_gilstate_t,PyObject *);

    return sipVH_qt_42(sipGILState,meth);
}

int sipQBoxLayout::heightForWidth(int a0) const
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[24]),sipPySelf,NULL,sipName_heightForWidth);

    if (!meth)
        return QBoxLayout::heightForWidth(a0);

    extern int sipVH_qt_44(sip_gilstate_t,PyObject *,int);

    return sipVH_qt_44(sipGILState,meth,a0);
}

void sipQBoxLayout::invalidate()
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[25],sipPySelf,NULL,sipName_invalidate);

    if (!meth)
    {
        QBoxLayout::invalidate();
        return;
    }

    extern void sipVH_qt_2(sip_gilstate_t,PyObject *);

    sipVH_qt_2(sipGILState,meth);
}

QWidget * sipQBoxLayout::widget()
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[26],sipPySelf,NULL,sipName_widget);

    if (!meth)
        return QLayoutItem::widget();

    extern QWidget * sipVH_qt_237(sip_gilstate_t,PyObject *);

    return sipVH_qt_237(sipGILState,meth);
}

QLayoutIterator sipQBoxLayout::iterator()
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[27],sipPySelf,NULL,sipName_iterator);

    if (!meth)
        return QBoxLayout::iterator();

    extern QLayoutIterator sipVH_qt_240(sip_gilstate_t,PyObject *);

    return sipVH_qt_240(sipGILState,meth);
}

QLayout * sipQBoxLayout::layout()
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[28],sipPySelf,NULL,sipName_layout);

    if (!meth)
        return QLayout::layout();

    extern QLayout * sipVH_qt_239(sip_gilstate_t,PyObject *);

    return sipVH_qt_239(sipGILState,meth);
}

QSpacerItem * sipQBoxLayout::spacerItem()
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[29],sipPySelf,NULL,sipName_spacerItem);

    if (!meth)
        return QLayoutItem::spacerItem();

    extern QSpacerItem * sipVH_qt_238(sip_gilstate_t,PyObject *);

    return sipVH_qt_238(sipGILState,meth);
}

void sipQBoxLayout::setAlignment(int a0)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[30],sipPySelf,NULL,sipName_setAlignment);

    if (!meth)
    {
        QLayoutItem::setAlignment(a0);
        return;
    }

    extern void sipVH_qt_68(sip_gilstate_t,PyObject *,int);

    sipVH_qt_68(sipGILState,meth,a0);
}

void sipQBoxLayout::sipProtectVirt_timerEvent(bool sipSelfWasArg,QTimerEvent *a0)
{
    (sipSelfWasArg ? QObject::timerEvent(a0) : timerEvent(a0));
}

void sipQBoxLayout::sipProtectVirt_customEvent(bool sipSelfWasArg,QCustomEvent *a0)
{
    (sipSelfWasArg ? QObject::customEvent(a0) : customEvent(a0));
}

bool sipQBoxLayout::sipProtectVirt_eventFilter(bool sipSelfWasArg,QObject *a0,QEvent *a1)
{
    return (sipSelfWasArg ? QLayout::eventFilter(a0,a1) : eventFilter(a0,a1));
}

void sipQBoxLayout::sipProtectVirt_childEvent(bool sipSelfWasArg,QChildEvent *a0)
{
    (sipSelfWasArg ? QLayout::childEvent(a0) : childEvent(a0));
}

void sipQBoxLayout::sipProtect_addChildLayout(QLayout *a0)
{
    QLayout::addChildLayout(a0);
}

void sipQBoxLayout::sipProtect_deleteAllItems()
{
    QLayout::deleteAllItems();
}

void sipQBoxLayout::sipProtect_setSupportsMargin(bool a0)
{
    QLayout::setSupportsMargin(a0);
}

QRect sipQBoxLayout::sipProtect_alignmentRect(const QRect& a0) const
{
    return QLayout::alignmentRect(a0);
}

void sipQBoxLayout::sipProtect_insertItem(int a0,QLayoutItem *a1)
{
    QBoxLayout::insertItem(a0,a1);
}

int sipQBoxLayout::sipEmit_destroyed(PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        if (sipParseArgs(&sipParseErr, sipArgs, ""))
        {
            emit destroyed();

            return 0;
        }
    }

    {
        QObject * a0;

        if (sipParseArgs(&sipParseErr, sipArgs, "J8", sipType_QObject, &a0))
        {
            emit destroyed(a0);

            return 0;
        }
    }

    sipNoMethod(sipParseErr, sipName_QBoxLayout, sipName_destroyed, NULL);

    return -1;
}

extern "C" {static int QBoxLayout_emit_destroyed(sipSimpleWrapper *, PyObject *);}
static int QBoxLayout_emit_destroyed(sipSimpleWrapper *sw,PyObject *sipArgs)
{
    sipQBoxLayout *ptr = reinterpret_cast<sipQBoxLayout *>(sipGetComplexCppPtr(sw));

    return (ptr ? ptr->sipEmit_destroyed(sipArgs) : -1);
}

static pyqt3QtSignal signals_QBoxLayout[] = {
    {sipName_destroyed, QBoxLayout_emit_destroyed},
    {NULL, NULL}
};


extern "C" {static PyObject *meth_QBoxLayout_timerEvent(PyObject *, PyObject *);}
static PyObject *meth_QBoxLayout_timerEvent(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        QTimerEvent * a0;
        sipQBoxLayout *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ8", &sipSelf, sipType_QBoxLayout, &sipCpp, sipType_QTimerEvent, &a0))
        {
            sipCpp->sipProtectVirt_timerEvent(sipSelfWasArg,a0);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QBoxLayout, sipName_timerEvent, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QBoxLayout_customEvent(PyObject *, PyObject *);}
static PyObject *meth_QBoxLayout_customEvent(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        QCustomEvent * a0;
        sipQBoxLayout *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ8", &sipSelf, sipType_QBoxLayout, &sipCpp, sipType_QCustomEvent, &a0))
        {
            sipCpp->sipProtectVirt_customEvent(sipSelfWasArg,a0);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QBoxLayout, sipName_customEvent, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QBoxLayout_eventFilter(PyObject *, PyObject *);}
static PyObject *meth_QBoxLayout_eventFilter(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        QObject * a0;
        QEvent * a1;
        sipQBoxLayout *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ8J8", &sipSelf, sipType_QBoxLayout, &sipCpp, sipType_QObject, &a0, sipType_QEvent, &a1))
        {
            bool sipRes;

            sipRes = sipCpp->sipProtectVirt_eventFilter(sipSelfWasArg,a0,a1);

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QBoxLayout, sipName_eventFilter, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QBoxLayout_childEvent(PyObject *, PyObject *);}
static PyObject *meth_QBoxLayout_childEvent(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        QChildEvent * a0;
        sipQBoxLayout *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ8", &sipSelf, sipType_QBoxLayout, &sipCpp, sipType_QChildEvent, &a0))
        {
            sipCpp->sipProtectVirt_childEvent(sipSelfWasArg,a0);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QBoxLayout, sipName_childEvent, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QBoxLayout_addChildLayout(PyObject *, PyObject *);}
static PyObject *meth_QBoxLayout_addChildLayout(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QLayout * a0;
        sipQBoxLayout *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ8", &sipSelf, sipType_QBoxLayout, &sipCpp, sipType_QLayout, &a0))
        {
            sipCpp->sipProtect_addChildLayout(a0);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QBoxLayout, sipName_addChildLayout, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QBoxLayout_deleteAllItems(PyObject *, PyObject *);}
static PyObject *meth_QBoxLayout_deleteAllItems(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        sipQBoxLayout *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QBoxLayout, &sipCpp))
        {
            sipCpp->sipProtect_deleteAllItems();

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QBoxLayout, sipName_deleteAllItems, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QBoxLayout_setSupportsMargin(PyObject *, PyObject *);}
static PyObject *meth_QBoxLayout_setSupportsMargin(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        bool a0;
        sipQBoxLayout *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bb", &sipSelf, sipType_QBoxLayout, &sipCpp, &a0))
        {
            sipCpp->sipProtect_setSupportsMargin(a0);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QBoxLayout, sipName_setSupportsMargin, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QBoxLayout_alignmentRect(PyObject *, PyObject *);}
static PyObject *meth_QBoxLayout_alignmentRect(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const QRect * a0;
        sipQBoxLayout *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ9", &sipSelf, sipType_QBoxLayout, &sipCpp, sipType_QRect, &a0))
        {
            QRect *sipRes;

            sipRes = new QRect(sipCpp->sipProtect_alignmentRect(*a0));

            return sipConvertFromNewType(sipRes,sipType_QRect,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QBoxLayout, sipName_alignmentRect, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QBoxLayout_direction(PyObject *, PyObject *);}
static PyObject *meth_QBoxLayout_direction(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QBoxLayout *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QBoxLayout, &sipCpp))
        {
            QBoxLayout::Direction sipRes;

            sipRes = sipCpp->direction();

            return sipConvertFromEnum(sipRes,sipType_QBoxLayout_Direction);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QBoxLayout, sipName_direction, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QBoxLayout_setDirection(PyObject *, PyObject *);}
static PyObject *meth_QBoxLayout_setDirection(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QBoxLayout::Direction a0;
        QBoxLayout *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BE", &sipSelf, sipType_QBoxLayout, &sipCpp, sipType_QBoxLayout_Direction, &a0))
        {
            sipCpp->setDirection(a0);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QBoxLayout, sipName_setDirection, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QBoxLayout_addSpacing(PyObject *, PyObject *);}
static PyObject *meth_QBoxLayout_addSpacing(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        int a0;
        QBoxLayout *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bi", &sipSelf, sipType_QBoxLayout, &sipCpp, &a0))
        {
            sipCpp->addSpacing(a0);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QBoxLayout, sipName_addSpacing, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QBoxLayout_addStretch(PyObject *, PyObject *);}
static PyObject *meth_QBoxLayout_addStretch(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        int a0 = 0;
        QBoxLayout *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B|i", &sipSelf, sipType_QBoxLayout, &sipCpp, &a0))
        {
            sipCpp->addStretch(a0);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QBoxLayout, sipName_addStretch, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QBoxLayout_addLayout(PyObject *, PyObject *);}
static PyObject *meth_QBoxLayout_addLayout(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QLayout * a0;
        int a1 = 0;
        QBoxLayout *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ:|i", &sipSelf, sipType_QBoxLayout, &sipCpp, sipType_QLayout, &a0, &a1))
        {
            sipCpp->addLayout(a0,a1);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QBoxLayout, sipName_addLayout, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QBoxLayout_addStrut(PyObject *, PyObject *);}
static PyObject *meth_QBoxLayout_addStrut(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        int a0;
        QBoxLayout *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bi", &sipSelf, sipType_QBoxLayout, &sipCpp, &a0))
        {
            sipCpp->addStrut(a0);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QBoxLayout, sipName_addStrut, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QBoxLayout_addItem(PyObject *, PyObject *);}
static PyObject *meth_QBoxLayout_addItem(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        QLayoutItem * a0;
        QBoxLayout *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ:", &sipSelf, sipType_QBoxLayout, &sipCpp, sipType_QLayoutItem, &a0))
        {
            (sipSelfWasArg ? sipCpp->QBoxLayout::addItem(a0) : sipCpp->addItem(a0));

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QBoxLayout, sipName_addItem, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QBoxLayout_addWidget(PyObject *, PyObject *);}
static PyObject *meth_QBoxLayout_addWidget(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QWidget * a0;
        int a1 = 0;
        int a2 = 0;
        QBoxLayout *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ8|ii", &sipSelf, sipType_QBoxLayout, &sipCpp, sipType_QWidget, &a0, &a1, &a2))
        {
            sipCpp->addWidget(a0,a1,a2);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QBoxLayout, sipName_addWidget, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QBoxLayout_insertSpacing(PyObject *, PyObject *);}
static PyObject *meth_QBoxLayout_insertSpacing(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        int a0;
        int a1;
        QBoxLayout *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bii", &sipSelf, sipType_QBoxLayout, &sipCpp, &a0, &a1))
        {
            sipCpp->insertSpacing(a0,a1);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QBoxLayout, sipName_insertSpacing, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QBoxLayout_insertStretch(PyObject *, PyObject *);}
static PyObject *meth_QBoxLayout_insertStretch(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        int a0;
        int a1 = 0;
        QBoxLayout *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bi|i", &sipSelf, sipType_QBoxLayout, &sipCpp, &a0, &a1))
        {
            sipCpp->insertStretch(a0,a1);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QBoxLayout, sipName_insertStretch, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QBoxLayout_insertWidget(PyObject *, PyObject *);}
static PyObject *meth_QBoxLayout_insertWidget(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        int a0;
        QWidget * a1;
        int a2 = 0;
        int a3 = 0;
        QBoxLayout *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BiJ8|ii", &sipSelf, sipType_QBoxLayout, &sipCpp, &a0, sipType_QWidget, &a1, &a2, &a3))
        {
            sipCpp->insertWidget(a0,a1,a2,a3);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QBoxLayout, sipName_insertWidget, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QBoxLayout_insertLayout(PyObject *, PyObject *);}
static PyObject *meth_QBoxLayout_insertLayout(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        int a0;
        QLayout * a1;
        int a2 = 0;
        QBoxLayout *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BiJ:|i", &sipSelf, sipType_QBoxLayout, &sipCpp, &a0, sipType_QLayout, &a1, &a2))
        {
            sipCpp->insertLayout(a0,a1,a2);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QBoxLayout, sipName_insertLayout, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QBoxLayout_findWidget(PyObject *, PyObject *);}
static PyObject *meth_QBoxLayout_findWidget(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QWidget * a0;
        QBoxLayout *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ8", &sipSelf, sipType_QBoxLayout, &sipCpp, sipType_QWidget, &a0))
        {
            int sipRes;

            sipRes = sipCpp->findWidget(a0);

            return SIPLong_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QBoxLayout, sipName_findWidget, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QBoxLayout_setStretchFactor(PyObject *, PyObject *);}
static PyObject *meth_QBoxLayout_setStretchFactor(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QWidget * a0;
        int a1;
        QBoxLayout *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ8i", &sipSelf, sipType_QBoxLayout, &sipCpp, sipType_QWidget, &a0, &a1))
        {
            bool sipRes;

            sipRes = sipCpp->setStretchFactor(a0,a1);

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QBoxLayout, sipName_setStretchFactor, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QBoxLayout_sizeHint(PyObject *, PyObject *);}
static PyObject *meth_QBoxLayout_sizeHint(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        QBoxLayout *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QBoxLayout, &sipCpp))
        {
            QSize *sipRes;

            sipRes = new QSize((sipSelfWasArg ? sipCpp->QBoxLayout::sizeHint() : sipCpp->sizeHint()));

            return sipConvertFromNewType(sipRes,sipType_QSize,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QBoxLayout, sipName_sizeHint, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QBoxLayout_minimumSize(PyObject *, PyObject *);}
static PyObject *meth_QBoxLayout_minimumSize(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        QBoxLayout *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QBoxLayout, &sipCpp))
        {
            QSize *sipRes;

            sipRes = new QSize((sipSelfWasArg ? sipCpp->QBoxLayout::minimumSize() : sipCpp->minimumSize()));

            return sipConvertFromNewType(sipRes,sipType_QSize,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QBoxLayout, sipName_minimumSize, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QBoxLayout_maximumSize(PyObject *, PyObject *);}
static PyObject *meth_QBoxLayout_maximumSize(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        QBoxLayout *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QBoxLayout, &sipCpp))
        {
            QSize *sipRes;

            sipRes = new QSize((sipSelfWasArg ? sipCpp->QBoxLayout::maximumSize() : sipCpp->maximumSize()));

            return sipConvertFromNewType(sipRes,sipType_QSize,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QBoxLayout, sipName_maximumSize, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QBoxLayout_hasHeightForWidth(PyObject *, PyObject *);}
static PyObject *meth_QBoxLayout_hasHeightForWidth(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        QBoxLayout *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QBoxLayout, &sipCpp))
        {
            bool sipRes;

            sipRes = (sipSelfWasArg ? sipCpp->QBoxLayout::hasHeightForWidth() : sipCpp->hasHeightForWidth());

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QBoxLayout, sipName_hasHeightForWidth, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QBoxLayout_heightForWidth(PyObject *, PyObject *);}
static PyObject *meth_QBoxLayout_heightForWidth(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        int a0;
        QBoxLayout *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bi", &sipSelf, sipType_QBoxLayout, &sipCpp, &a0))
        {
            int sipRes;

            sipRes = (sipSelfWasArg ? sipCpp->QBoxLayout::heightForWidth(a0) : sipCpp->heightForWidth(a0));

            return SIPLong_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QBoxLayout, sipName_heightForWidth, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QBoxLayout_minimumHeightForWidth(PyObject *, PyObject *);}
static PyObject *meth_QBoxLayout_minimumHeightForWidth(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        int a0;
        QBoxLayout *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bi", &sipSelf, sipType_QBoxLayout, &sipCpp, &a0))
        {
            int sipRes;

            sipRes = sipCpp->minimumHeightForWidth(a0);

            return SIPLong_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QBoxLayout, sipName_minimumHeightForWidth, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QBoxLayout_expanding(PyObject *, PyObject *);}
static PyObject *meth_QBoxLayout_expanding(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        QBoxLayout *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QBoxLayout, &sipCpp))
        {
            QSizePolicy::ExpandData sipRes;

            sipRes = (sipSelfWasArg ? sipCpp->QBoxLayout::expanding() : sipCpp->expanding());

            return sipConvertFromEnum(sipRes,sipType_QSizePolicy_ExpandData);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QBoxLayout, sipName_expanding, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QBoxLayout_invalidate(PyObject *, PyObject *);}
static PyObject *meth_QBoxLayout_invalidate(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        QBoxLayout *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QBoxLayout, &sipCpp))
        {
            (sipSelfWasArg ? sipCpp->QBoxLayout::invalidate() : sipCpp->invalidate());

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QBoxLayout, sipName_invalidate, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QBoxLayout_iterator(PyObject *, PyObject *);}
static PyObject *meth_QBoxLayout_iterator(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        QBoxLayout *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QBoxLayout, &sipCpp))
        {
            QLayoutIterator *sipRes;

            sipRes = new QLayoutIterator((sipSelfWasArg ? sipCpp->QBoxLayout::iterator() : sipCpp->iterator()));

            return sipConvertFromNewType(sipRes,sipType_QLayoutIterator,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QBoxLayout, sipName_iterator, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QBoxLayout_setGeometry(PyObject *, PyObject *);}
static PyObject *meth_QBoxLayout_setGeometry(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        const QRect * a0;
        QBoxLayout *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ9", &sipSelf, sipType_QBoxLayout, &sipCpp, sipType_QRect, &a0))
        {
            (sipSelfWasArg ? sipCpp->QBoxLayout::setGeometry(*a0) : sipCpp->setGeometry(*a0));

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QBoxLayout, sipName_setGeometry, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QBoxLayout_insertItem(PyObject *, PyObject *);}
static PyObject *meth_QBoxLayout_insertItem(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        int a0;
        QLayoutItem * a1;
        sipQBoxLayout *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BiJ:", &sipSelf, sipType_QBoxLayout, &sipCpp, &a0, sipType_QLayoutItem, &a1))
        {
            sipCpp->sipProtect_insertItem(a0,a1);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QBoxLayout, sipName_insertItem, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QBoxLayout_metaObject(PyObject *, PyObject *);}
static PyObject *meth_QBoxLayout_metaObject(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        QBoxLayout *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QBoxLayout, &sipCpp))
        {
            QMetaObject *sipRes;

            sipRes = (sipSelfWasArg ? sipCpp->QBoxLayout::metaObject() : sipCpp->metaObject());

            return sipConvertFromType(sipRes,sipType_QMetaObject,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QBoxLayout, sipName_metaObject, NULL);

    return NULL;
}


/* Cast a pointer to a type somewhere in its superclass hierarchy. */
extern "C" {static void *cast_QBoxLayout(void *, const sipTypeDef *);}
static void *cast_QBoxLayout(void *ptr, const sipTypeDef *targetType)
{
    void *res;

    if (targetType == sipType_QBoxLayout)
        return ptr;

    if ((res = ((const sipClassTypeDef *)sipType_QLayout)->ctd_cast((QLayout *)(QBoxLayout *)ptr,targetType)) != NULL)
        return res;

    return NULL;
}


/* Call the instance's destructor. */
extern "C" {static void release_QBoxLayout(void *, int);}
static void release_QBoxLayout(void *sipCppV,int sipState)
{
    if (sipState & SIP_DERIVED_CLASS)
        delete reinterpret_cast<sipQBoxLayout *>(sipCppV);
    else
        delete reinterpret_cast<QBoxLayout *>(sipCppV);
}


extern "C" {static void dealloc_QBoxLayout(sipSimpleWrapper *);}
static void dealloc_QBoxLayout(sipSimpleWrapper *sipSelf)
{
    if (sipIsDerived(sipSelf))
        reinterpret_cast<sipQBoxLayout *>(sipSelf->u.cppPtr)->sipPySelf = NULL;

    if (sipIsPyOwned(sipSelf))
    {
        release_QBoxLayout(sipSelf->u.cppPtr,sipSelf->flags);
    }
}


extern "C" {static void *init_QBoxLayout(sipSimpleWrapper *, PyObject *, PyObject *, PyObject **, PyObject **, PyObject **);}
static void *init_QBoxLayout(sipSimpleWrapper *sipSelf, PyObject *sipArgs, PyObject *sipKwds, PyObject **sipUnused, PyObject **sipOwner, PyObject **sipParseErr)
{
    sipQBoxLayout *sipCpp = 0;

    {
        QWidget * a0;
        QBoxLayout::Direction a1;
        int a2 = 0;
        int a3 = -1;
        const char * a4 = 0;

        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, NULL, sipUnused, "JHE|iis", sipType_QWidget, &a0, sipOwner, sipType_QBoxLayout_Direction, &a1, &a2, &a3, &a4))
        {
            sipCpp = new sipQBoxLayout(a0,a1,a2,a3,a4);

            sipCpp->sipPySelf = sipSelf;

            return sipCpp;
        }
    }

    {
        QLayout * a0;
        QBoxLayout::Direction a1;
        int a2 = -1;
        const char * a3 = 0;

        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, NULL, sipUnused, "JHE|is", sipType_QLayout, &a0, sipOwner, sipType_QBoxLayout_Direction, &a1, &a2, &a3))
        {
            sipCpp = new sipQBoxLayout(a0,a1,a2,a3);

            sipCpp->sipPySelf = sipSelf;

            return sipCpp;
        }
    }

    {
        QBoxLayout::Direction a0;
        int a1 = -1;
        const char * a2 = 0;

        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, NULL, sipUnused, "E|is", sipType_QBoxLayout_Direction, &a0, &a1, &a2))
        {
            sipCpp = new sipQBoxLayout(a0,a1,a2);

            sipCpp->sipPySelf = sipSelf;

            return sipCpp;
        }
    }

    return NULL;
}


/* Define this type's super-types. */
static sipEncodedTypeDef supers_QBoxLayout[] = {{148, 255, 1}};


static PyMethodDef methods_QBoxLayout[] = {
    {SIP_MLNAME_CAST(sipName_addChildLayout), meth_QBoxLayout_addChildLayout, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_addItem), meth_QBoxLayout_addItem, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_addLayout), meth_QBoxLayout_addLayout, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_addSpacing), meth_QBoxLayout_addSpacing, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_addStretch), meth_QBoxLayout_addStretch, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_addStrut), meth_QBoxLayout_addStrut, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_addWidget), meth_QBoxLayout_addWidget, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_alignmentRect), meth_QBoxLayout_alignmentRect, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_childEvent), meth_QBoxLayout_childEvent, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_customEvent), meth_QBoxLayout_customEvent, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_deleteAllItems), meth_QBoxLayout_deleteAllItems, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_direction), meth_QBoxLayout_direction, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_eventFilter), meth_QBoxLayout_eventFilter, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_expanding), meth_QBoxLayout_expanding, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_findWidget), meth_QBoxLayout_findWidget, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_hasHeightForWidth), meth_QBoxLayout_hasHeightForWidth, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_heightForWidth), meth_QBoxLayout_heightForWidth, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_insertItem), meth_QBoxLayout_insertItem, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_insertLayout), meth_QBoxLayout_insertLayout, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_insertSpacing), meth_QBoxLayout_insertSpacing, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_insertStretch), meth_QBoxLayout_insertStretch, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_insertWidget), meth_QBoxLayout_insertWidget, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_invalidate), meth_QBoxLayout_invalidate, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_iterator), meth_QBoxLayout_iterator, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_maximumSize), meth_QBoxLayout_maximumSize, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_metaObject), meth_QBoxLayout_metaObject, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_minimumHeightForWidth), meth_QBoxLayout_minimumHeightForWidth, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_minimumSize), meth_QBoxLayout_minimumSize, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_setDirection), meth_QBoxLayout_setDirection, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_setGeometry), meth_QBoxLayout_setGeometry, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_setStretchFactor), meth_QBoxLayout_setStretchFactor, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_setSupportsMargin), meth_QBoxLayout_setSupportsMargin, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_sizeHint), meth_QBoxLayout_sizeHint, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_timerEvent), meth_QBoxLayout_timerEvent, METH_VARARGS, NULL}
};

static sipEnumMemberDef enummembers_QBoxLayout[] = {
    {sipName_BottomToTop, QBoxLayout::BottomToTop, 10},
    {sipName_Down, QBoxLayout::Down, 10},
    {sipName_LeftToRight, QBoxLayout::LeftToRight, 10},
    {sipName_RightToLeft, QBoxLayout::RightToLeft, 10},
    {sipName_TopToBottom, QBoxLayout::TopToBottom, 10},
    {sipName_Up, QBoxLayout::Up, 10},
};


pyqt3ClassTypeDef sipTypeDef_qt_QBoxLayout = {
{
    {
        -1,
        0,
        0,
        SIP_TYPE_SCC|SIP_TYPE_CLASS,
        sipNameNr_QBoxLayout,
        {0}
    },
    {
        sipNameNr_QBoxLayout,
        {0, 0, 1},
        34, methods_QBoxLayout,
        6, enummembers_QBoxLayout,
        0, 0,
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    },
    0,
    -1,
    -1,
    supers_QBoxLayout,
    0,
    init_QBoxLayout,
    0,
    0,
#if PY_MAJOR_VERSION >= 3
    0,
    0,
#else
    0,
    0,
    0,
    0,
#endif
    dealloc_QBoxLayout,
    0,
    0,
    0,
    release_QBoxLayout,
    cast_QBoxLayout,
    0,
    0,
    0
},
    signals_QBoxLayout
};
