/*
 * Interface wrapper code.
 *
 * Generated by SIP 4.10.2 on Mon Mar 28 16:23:15 2011
 *
 * Copyright (c) 2007
 * 	Riverbank Computing Limited <info@riverbankcomputing.co.uk>
 * 
 * This file is part of PyQt.
 * 
 * This copy of PyQt is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the Free
 * Software Foundation; either version 2, or (at your option) any later
 * version.
 * 
 * PyQt is supplied in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
 * details.
 * 
 * You should have received a copy of the GNU General Public License along with
 * PyQt; see the file LICENSE.  If not, write to the Free Software Foundation,
 * Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 */

#include "sipAPIqt.h"

#line 57 "/usr/share/sip/qt/qstringlist.sip"
#include <qstringlist.h>
#line 31 "sipqtQStringList.cc"

#line 449 "/usr/share/sip/qt/qstring.sip"
#include <qstring.h>
#line 35 "sipqtQStringList.cc"
#line 60 "/usr/share/sip/qt/qregexp.sip"
#include <qregexp.h>
#line 38 "sipqtQStringList.cc"
#line 180 "/usr/share/sip/qt/qstring.sip"
#include <qstring.h>
#line 41 "sipqtQStringList.cc"
#line 37 "/usr/share/sip/qt/qstrlist.sip"
#include <qstrlist.h>
#line 44 "sipqtQStringList.cc"


extern "C" {static PyObject *meth_QStringList_sort(PyObject *, PyObject *);}
static PyObject *meth_QStringList_sort(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QStringList *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QStringList, &sipCpp))
        {
            sipCpp->sort();

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QStringList, sipName_sort, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QStringList_fromStrList(PyObject *, PyObject *);}
static PyObject *meth_QStringList_fromStrList(PyObject *, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const QStrList * a0;
        int a0State = 0;

        if (sipParseArgs(&sipParseErr, sipArgs, "J1", sipType_QStrList,&a0, &a0State))
        {
            QStringList *sipRes;

            sipRes = new QStringList(QStringList::fromStrList(*a0));
            sipReleaseType(const_cast<QStrList *>(a0),sipType_QStrList,a0State);

            return sipConvertFromNewType(sipRes,sipType_QStringList,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QStringList, sipName_fromStrList, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QStringList_split(PyObject *, PyObject *);}
static PyObject *meth_QStringList_split(PyObject *, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const QString * a0;
        int a0State = 0;
        const QString * a1;
        int a1State = 0;
        bool a2 = 0;

        if (sipParseArgs(&sipParseErr, sipArgs, "J1J1|b", sipType_QString, &a0, &a0State, sipType_QString, &a1, &a1State, &a2))
        {
            QStringList *sipRes;

            sipRes = new QStringList(QStringList::split(*a0,*a1,a2));
            sipReleaseType(const_cast<QString *>(a0),sipType_QString,a0State);
            sipReleaseType(const_cast<QString *>(a1),sipType_QString,a1State);

            return sipConvertFromNewType(sipRes,sipType_QStringList,NULL);
        }
    }

    {
        const QChar * a0;
        const QString * a1;
        int a1State = 0;
        bool a2 = 0;

        if (sipParseArgs(&sipParseErr, sipArgs, "J9J1|b", sipType_QChar, &a0, sipType_QString, &a1, &a1State, &a2))
        {
            QStringList *sipRes;

            sipRes = new QStringList(QStringList::split(*a0,*a1,a2));
            sipReleaseType(const_cast<QString *>(a1),sipType_QString,a1State);

            return sipConvertFromNewType(sipRes,sipType_QStringList,NULL);
        }
    }

    {
        const QRegExp * a0;
        const QString * a1;
        int a1State = 0;
        bool a2 = 0;

        if (sipParseArgs(&sipParseErr, sipArgs, "J9J1|b", sipType_QRegExp, &a0, sipType_QString, &a1, &a1State, &a2))
        {
            QStringList *sipRes;

            sipRes = new QStringList(QStringList::split(*a0,*a1,a2));
            sipReleaseType(const_cast<QString *>(a1),sipType_QString,a1State);

            return sipConvertFromNewType(sipRes,sipType_QStringList,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QStringList, sipName_split, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QStringList_join(PyObject *, PyObject *);}
static PyObject *meth_QStringList_join(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const QString * a0;
        int a0State = 0;
        QStringList *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ1", &sipSelf, sipType_QStringList, &sipCpp, sipType_QString, &a0, &a0State))
        {
            QString *sipRes;

            sipRes = new QString(sipCpp->join(*a0));
            sipReleaseType(const_cast<QString *>(a0),sipType_QString,a0State);

            return sipConvertFromNewType(sipRes,sipType_QString,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QStringList, sipName_join, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QStringList_grep(PyObject *, PyObject *);}
static PyObject *meth_QStringList_grep(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const QString * a0;
        int a0State = 0;
        bool a1 = 1;
        QStringList *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ1|b", &sipSelf, sipType_QStringList, &sipCpp, sipType_QString, &a0, &a0State, &a1))
        {
            QStringList *sipRes;

            sipRes = new QStringList(sipCpp->grep(*a0,a1));
            sipReleaseType(const_cast<QString *>(a0),sipType_QString,a0State);

            return sipConvertFromNewType(sipRes,sipType_QStringList,NULL);
        }
    }

    {
        const QRegExp * a0;
        QStringList *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ9", &sipSelf, sipType_QStringList, &sipCpp, sipType_QRegExp, &a0))
        {
            QStringList *sipRes;

            sipRes = new QStringList(sipCpp->grep(*a0));

            return sipConvertFromNewType(sipRes,sipType_QStringList,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QStringList, sipName_grep, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QStringList_gres(PyObject *, PyObject *);}
static PyObject *meth_QStringList_gres(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const QString * a0;
        int a0State = 0;
        const QString * a1;
        int a1State = 0;
        bool a2 = 1;
        QStringList *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ1J1|b", &sipSelf, sipType_QStringList, &sipCpp, sipType_QString, &a0, &a0State, sipType_QString, &a1, &a1State, &a2))
        {
            QStringList *sipRes;

            sipRes = &sipCpp->gres(*a0,*a1,a2);
            sipReleaseType(const_cast<QString *>(a0),sipType_QString,a0State);
            sipReleaseType(const_cast<QString *>(a1),sipType_QString,a1State);

            return sipConvertFromType(sipRes,sipType_QStringList,NULL);
        }
    }

    {
        const QRegExp * a0;
        const QString * a1;
        int a1State = 0;
        QStringList *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ9J1", &sipSelf, sipType_QStringList, &sipCpp, sipType_QRegExp, &a0, sipType_QString, &a1, &a1State))
        {
            QStringList *sipRes;

            sipRes = &sipCpp->gres(*a0,*a1);
            sipReleaseType(const_cast<QString *>(a1),sipType_QString,a1State);

            return sipConvertFromType(sipRes,sipType_QStringList,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QStringList, sipName_gres, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QStringList_isEmpty(PyObject *, PyObject *);}
static PyObject *meth_QStringList_isEmpty(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QStringList *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QStringList, &sipCpp))
        {
            bool sipRes;

            sipRes = sipCpp->isEmpty();

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QStringList, sipName_isEmpty, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QStringList_append(PyObject *, PyObject *);}
static PyObject *meth_QStringList_append(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const QString * a0;
        int a0State = 0;
        QStringList *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ1", &sipSelf, sipType_QStringList, &sipCpp, sipType_QString, &a0, &a0State))
        {
            sipCpp->append(*a0);
            sipReleaseType(const_cast<QString *>(a0),sipType_QString,a0State);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QStringList, sipName_append, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QStringList_prepend(PyObject *, PyObject *);}
static PyObject *meth_QStringList_prepend(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const QString * a0;
        int a0State = 0;
        QStringList *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ1", &sipSelf, sipType_QStringList, &sipCpp, sipType_QString, &a0, &a0State))
        {
            sipCpp->prepend(*a0);
            sipReleaseType(const_cast<QString *>(a0),sipType_QString,a0State);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QStringList, sipName_prepend, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QStringList_remove(PyObject *, PyObject *);}
static PyObject *meth_QStringList_remove(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const QString * a0;
        int a0State = 0;
        QStringList *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ1", &sipSelf, sipType_QStringList, &sipCpp, sipType_QString, &a0, &a0State))
        {
            sipCpp->remove(*a0);
            sipReleaseType(const_cast<QString *>(a0),sipType_QString,a0State);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QStringList, sipName_remove, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QStringList_first(PyObject *, PyObject *);}
static PyObject *meth_QStringList_first(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QStringList *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QStringList, &sipCpp))
        {
            QString *sipRes;

            sipRes = new QString(sipCpp->first());

            return sipConvertFromNewType(sipRes,sipType_QString,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QStringList, sipName_first, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QStringList_last(PyObject *, PyObject *);}
static PyObject *meth_QStringList_last(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QStringList *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QStringList, &sipCpp))
        {
            QString *sipRes;

            sipRes = new QString(sipCpp->last());

            return sipConvertFromNewType(sipRes,sipType_QString,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QStringList, sipName_last, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QStringList_findIndex(PyObject *, PyObject *);}
static PyObject *meth_QStringList_findIndex(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const QString * a0;
        int a0State = 0;
        QStringList *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ1", &sipSelf, sipType_QStringList, &sipCpp, sipType_QString, &a0, &a0State))
        {
            int sipRes;

            sipRes = sipCpp->findIndex(*a0);
            sipReleaseType(const_cast<QString *>(a0),sipType_QString,a0State);

            return SIPLong_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QStringList, sipName_findIndex, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QStringList_contains(PyObject *, PyObject *);}
static PyObject *meth_QStringList_contains(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const QString * a0;
        int a0State = 0;
        QStringList *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ1", &sipSelf, sipType_QStringList, &sipCpp, sipType_QString, &a0, &a0State))
        {
            uint sipRes;

            sipRes = sipCpp->contains(*a0);
            sipReleaseType(const_cast<QString *>(a0),sipType_QString,a0State);

            return PyLong_FromUnsignedLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QStringList, sipName_contains, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QStringList_count(PyObject *, PyObject *);}
static PyObject *meth_QStringList_count(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QStringList *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QStringList, &sipCpp))
        {
            uint sipRes;

            sipRes = sipCpp->count();

            return PyLong_FromUnsignedLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QStringList, sipName_count, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QStringList_clear(PyObject *, PyObject *);}
static PyObject *meth_QStringList_clear(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QStringList *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QStringList, &sipCpp))
        {
            sipCpp->clear();

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QStringList, sipName_clear, NULL);

    return NULL;
}


extern "C" {static PyObject *slot_QStringList___ne__(PyObject *sipSelf,PyObject *sipArg);}
static PyObject *slot_QStringList___ne__(PyObject *sipSelf,PyObject *sipArg)
{
    QStringList *sipCpp = reinterpret_cast<QStringList *>(sipGetCppPtr((sipSimpleWrapper *)sipSelf,sipType_QStringList));

    if (!sipCpp)
        return 0;

    PyObject *sipParseErr = NULL;

    {
        const QStringList * a0;

        if (sipParseArgs(&sipParseErr, sipArg, "1J9", sipType_QStringList, &a0))
        {
            bool sipRes;

            sipRes = sipCpp->QStringList::operator!=(*a0);

            return PyBool_FromLong(sipRes);
        }
    }

    Py_XDECREF(sipParseErr);

    if (sipParseErr == Py_None)
        return NULL;

    return sipPySlotExtend(&sipModuleAPI_qt,ne_slot,sipType_QStringList,sipSelf,sipArg);
}


extern "C" {static PyObject *slot_QStringList___eq__(PyObject *sipSelf,PyObject *sipArg);}
static PyObject *slot_QStringList___eq__(PyObject *sipSelf,PyObject *sipArg)
{
    QStringList *sipCpp = reinterpret_cast<QStringList *>(sipGetCppPtr((sipSimpleWrapper *)sipSelf,sipType_QStringList));

    if (!sipCpp)
        return 0;

    PyObject *sipParseErr = NULL;

    {
        const QStringList * a0;

        if (sipParseArgs(&sipParseErr, sipArg, "1J9", sipType_QStringList, &a0))
        {
            bool sipRes;

            sipRes = sipCpp->QStringList::operator==(*a0);

            return PyBool_FromLong(sipRes);
        }
    }

    Py_XDECREF(sipParseErr);

    if (sipParseErr == Py_None)
        return NULL;

    return sipPySlotExtend(&sipModuleAPI_qt,eq_slot,sipType_QStringList,sipSelf,sipArg);
}


extern "C" {static PyObject *slot_QStringList___imul__(PyObject *sipSelf,int a0);}
static PyObject *slot_QStringList___imul__(PyObject *sipSelf,int a0)
{
    QStringList *sipCpp = reinterpret_cast<QStringList *>(sipGetCppPtr((sipSimpleWrapper *)sipSelf,sipType_QStringList));

    if (!sipCpp)
        return 0;


    {
        {
#line 235 "/usr/share/sip/qt/qstringlist.sip"
		QStringList orig(*sipCpp);

		sipCpp -> clear();

		while (a0-- > 0)
			*sipCpp += orig;
#line 626 "sipqtQStringList.cc"

            Py_INCREF(sipSelf);
            return sipSelf;
        }
    }
}


extern "C" {static PyObject *slot_QStringList___mul__(PyObject *sipSelf,int a0);}
static PyObject *slot_QStringList___mul__(PyObject *sipSelf,int a0)
{
    QStringList *sipCpp = reinterpret_cast<QStringList *>(sipGetCppPtr((sipSimpleWrapper *)sipSelf,sipType_QStringList));

    if (!sipCpp)
        return 0;


    {
        {
            QStringList *sipRes = 0;

#line 227 "/usr/share/sip/qt/qstringlist.sip"
		sipRes = new QStringList();

		while (a0-- > 0)
			*sipRes += *sipCpp;
#line 653 "sipqtQStringList.cc"

            return sipConvertFromNewType(sipRes,sipType_QStringList,NULL);
        }
    }
}


extern "C" {static PyObject *slot_QStringList___iadd__(PyObject *sipSelf,PyObject *sipArg);}
static PyObject *slot_QStringList___iadd__(PyObject *sipSelf,PyObject *sipArg)
{
    QStringList *sipCpp = reinterpret_cast<QStringList *>(sipGetCppPtr((sipSimpleWrapper *)sipSelf,sipType_QStringList));

    if (!sipCpp)
        return 0;

    PyObject *sipParseErr = NULL;

    {
        const QStringList * a0;

        if (sipParseArgs(&sipParseErr, sipArg, "1J9", sipType_QStringList, &a0))
        {
            sipCpp->QStringList::operator+=(*a0);

            Py_INCREF(sipSelf);
            return sipSelf;
        }
    }

    {
        const QString * a0;
        int a0State = 0;

        if (sipParseArgs(&sipParseErr, sipArg, "1J1", sipType_QString, &a0, &a0State))
        {
            sipCpp->QStringList::operator+=(*a0);
            sipReleaseType(const_cast<QString *>(a0),sipType_QString,a0State);

            Py_INCREF(sipSelf);
            return sipSelf;
        }
    }

    /* Raise an exception if the argument couldn't be parsed. */
    sipBadOperatorArg(sipSelf,sipArg,iconcat_slot);

    return NULL;
}


extern "C" {static PyObject *slot_QStringList___add__(PyObject *sipSelf,PyObject *sipArg);}
static PyObject *slot_QStringList___add__(PyObject *sipSelf,PyObject *sipArg)
{
    QStringList *sipCpp = reinterpret_cast<QStringList *>(sipGetCppPtr((sipSimpleWrapper *)sipSelf,sipType_QStringList));

    if (!sipCpp)
        return 0;

    PyObject *sipParseErr = NULL;

    {
        const QStringList * a0;

        if (sipParseArgs(&sipParseErr, sipArg, "1J9", sipType_QStringList, &a0))
        {
            QStringList *sipRes;

            sipRes = new QStringList(sipCpp->QStringList::operator+(*a0));

            return sipConvertFromNewType(sipRes,sipType_QStringList,NULL);
        }
    }

    /* Raise an exception if the argument couldn't be parsed. */
    sipBadOperatorArg(sipSelf,sipArg,concat_slot);

    return NULL;
}


extern "C" {static int slot_QStringList___contains__(PyObject *sipSelf,PyObject *sipArg);}
static int slot_QStringList___contains__(PyObject *sipSelf,PyObject *sipArg)
{
    QStringList *sipCpp = reinterpret_cast<QStringList *>(sipGetCppPtr((sipSimpleWrapper *)sipSelf,sipType_QStringList));

    if (!sipCpp)
        return -1;

    PyObject *sipParseErr = NULL;

    {
        const QString * a0;
        int a0State = 0;

        if (sipParseArgs(&sipParseErr, sipArg, "1J1", sipType_QString, &a0, &a0State))
        {
            int sipRes = 0;

#line 217 "/usr/share/sip/qt/qstringlist.sip"
		sipRes = (sipCpp -> findIndex(*a0) >= 0);
#line 754 "sipqtQStringList.cc"
            sipReleaseType(const_cast<QString *>(a0),sipType_QString,a0State);

            return sipRes;
        }
    }

    Py_XDECREF(sipParseErr);

    if (sipParseErr == Py_None)
        return NULL;

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QStringList, sipName___contains__, NULL);

    return -1;
}


extern "C" {static PyObject *slot_QStringList___getitem__(PyObject *sipSelf,PyObject *sipArg);}
static PyObject *slot_QStringList___getitem__(PyObject *sipSelf,PyObject *sipArg)
{
    QStringList *sipCpp = reinterpret_cast<QStringList *>(sipGetCppPtr((sipSimpleWrapper *)sipSelf,sipType_QStringList));

    if (!sipCpp)
        return 0;

    PyObject *sipParseErr = NULL;

    {
        int a0;

        if (sipParseArgs(&sipParseErr, sipArg, "1i", &a0))
        {
            QString *sipRes = 0;
            int sipIsErr = 0;

#line 181 "/usr/share/sip/qt/qstringlist.sip"
		int len;

		len = sipCpp -> count();

		if ((a0 = (int)sipConvertFromSequenceIndex(a0,len)) < 0)
			sipIsErr = 1;
		else
			sipRes = new QString((*sipCpp)[a0]);
#line 800 "sipqtQStringList.cc"

            if (sipIsErr)
                return 0;

            return sipConvertFromNewType(sipRes,sipType_QString,NULL);
        }
    }

    {
        PyObject * a0;

        if (sipParseArgs(&sipParseErr, sipArg, "1T", &PySlice_Type, &a0))
        {
            QStringList *sipRes = 0;
            int sipIsErr = 0;

#line 193 "/usr/share/sip/qt/qstringlist.sip"
#if PY_VERSION_HEX >= 0x02050000
		Py_ssize_t len, start, stop, step, slicelength, i;
#else
		int len, start, stop, step, slicelength, i;
#endif

		len = sipCpp -> count();

		if (sipConvertFromSliceObject(a0,len,&start,&stop,&step,&slicelength) < 0)
			sipIsErr = 1;
		else
		{
			sipRes = new QStringList();

			for (i = 0; i < slicelength; ++i)
			{
				(*sipRes) += (*sipCpp)[start];
				start += step;
			}
		}
#line 838 "sipqtQStringList.cc"

            if (sipIsErr)
                return 0;

            return sipConvertFromNewType(sipRes,sipType_QStringList,NULL);
        }
    }

    Py_XDECREF(sipParseErr);

    if (sipParseErr == Py_None)
        return NULL;

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QStringList, sipName___getitem__, NULL);

    return 0;
}


extern "C" {static int slot_QStringList___delitem__(PyObject *sipSelf,PyObject *sipArg);}
static int slot_QStringList___delitem__(PyObject *sipSelf,PyObject *sipArg)
{
    QStringList *sipCpp = reinterpret_cast<QStringList *>(sipGetCppPtr((sipSimpleWrapper *)sipSelf,sipType_QStringList));

    if (!sipCpp)
        return -1;

    PyObject *sipParseErr = NULL;

    {
        int a0;

        if (sipParseArgs(&sipParseErr, sipArg, "1i", &a0))
        {
            int sipIsErr = 0;

#line 149 "/usr/share/sip/qt/qstringlist.sip"
		int len;

		len = sipCpp -> count();

		if ((a0 = (int)sipConvertFromSequenceIndex(a0,len)) < 0)
			sipIsErr = 1;
		else
			sipCpp -> remove(sipCpp -> at(a0));
#line 885 "sipqtQStringList.cc"

            if (sipIsErr)
                return -1;

            return 0;
        }
    }

    {
        PyObject * a0;

        if (sipParseArgs(&sipParseErr, sipArg, "1T", &PySlice_Type, &a0))
        {
            int sipIsErr = 0;

#line 161 "/usr/share/sip/qt/qstringlist.sip"
#if PY_VERSION_HEX >= 0x02050000
		Py_ssize_t len, start, stop, step, slicelength, i;
#else
		int len, start, stop, step, slicelength, i;
#endif

		len = sipCpp -> count();

		if (sipConvertFromSliceObject(a0,len,&start,&stop,&step,&slicelength) < 0)
			sipIsErr = 1;
		else
			for (i = 0; i < slicelength; ++i)
			{
				sipCpp -> remove(sipCpp -> at(start));
				start += step - 1;
			}
#line 918 "sipqtQStringList.cc"

            if (sipIsErr)
                return -1;

            return 0;
        }
    }

    Py_XDECREF(sipParseErr);

    if (sipParseErr == Py_None)
        return NULL;

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QStringList, sipName___delitem__, NULL);

    return -1;
}


extern "C" {static int slot_QStringList___setitem__(PyObject *sipSelf,PyObject *sipArgs);}
static int slot_QStringList___setitem__(PyObject *sipSelf,PyObject *sipArgs)
{
    QStringList *sipCpp = reinterpret_cast<QStringList *>(sipGetCppPtr((sipSimpleWrapper *)sipSelf,sipType_QStringList));

    if (!sipCpp)
        return -1;

    PyObject *sipParseErr = NULL;

    {
        int a0;
        const QString * a1;
        int a1State = 0;

        if (sipParseArgs(&sipParseErr, sipArgs, "iJ1", &a0, sipType_QString, &a1, &a1State))
        {
            int sipIsErr = 0;

#line 102 "/usr/share/sip/qt/qstringlist.sip"
		int len;

		len = sipCpp -> count();

		if ((a0 = (int)sipConvertFromSequenceIndex(a0,len)) < 0)
			sipIsErr = 1;
		else
			(*sipCpp)[a0] = *a1;
#line 967 "sipqtQStringList.cc"
            sipReleaseType(const_cast<QString *>(a1),sipType_QString,a1State);

            if (sipIsErr)
                return -1;

            return 0;
        }
    }

    {
        PyObject * a0;
        const QStringList * a1;

        if (sipParseArgs(&sipParseErr, sipArgs, "TJ9", &PySlice_Type, &a0, sipType_QStringList, &a1))
        {
            int sipIsErr = 0;

#line 114 "/usr/share/sip/qt/qstringlist.sip"
#if PY_VERSION_HEX >= 0x02050000
		Py_ssize_t len, start, stop, step, slicelength, i;
#else
		int len, start, stop, step, slicelength, i;
#endif

		len = sipCpp -> count();

		if (sipConvertFromSliceObject(a0,len,&start,&stop,&step,&slicelength) < 0)
			sipIsErr = 1;
		else
		{
			int vlen = a1 -> count();

			if (vlen != slicelength)
			{
				sipBadLengthForSlice(vlen,slicelength);
				sipIsErr = 1;
			}
			else
			{
				QStringList::ConstIterator it = a1 -> begin();

				for (i = 0; i < slicelength; ++i)
				{
					(*sipCpp)[start] = *it;
					start += step;
					++it;
				}
			}
		}
#line 1017 "sipqtQStringList.cc"

            if (sipIsErr)
                return -1;

            return 0;
        }
    }

    Py_XDECREF(sipParseErr);

    if (sipParseErr == Py_None)
        return NULL;

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QStringList, sipName___setitem__, NULL);

    return -1;
}


extern "C" {static int slot_QStringList___len__(PyObject *sipSelf);}
static int slot_QStringList___len__(PyObject *sipSelf)
{
    QStringList *sipCpp = reinterpret_cast<QStringList *>(sipGetCppPtr((sipSimpleWrapper *)sipSelf,sipType_QStringList));

    if (!sipCpp)
        return -1;


    {
        {
            int sipRes = 0;

#line 97 "/usr/share/sip/qt/qstringlist.sip"
		sipRes = sipCpp -> count();
#line 1053 "sipqtQStringList.cc"

            return sipRes;
        }
    }
}


/* Cast a pointer to a type somewhere in its superclass hierarchy. */
extern "C" {static void *cast_QStringList(void *, const sipTypeDef *);}
static void *cast_QStringList(void *ptr, const sipTypeDef *targetType)
{
    if (targetType == sipType_QStringList)
        return ptr;

    return NULL;
}


/* Call the instance's destructor. */
extern "C" {static void release_QStringList(void *, int);}
static void release_QStringList(void *sipCppV,int)
{
    delete reinterpret_cast<QStringList *>(sipCppV);
}


extern "C" {static void assign_QStringList(void *, SIP_SSIZE_T, const void *);}
static void assign_QStringList(void *sipDst, SIP_SSIZE_T sipDstIdx, const void *sipSrc)
{
    reinterpret_cast<QStringList *>(sipDst)[sipDstIdx] = *reinterpret_cast<const QStringList *>(sipSrc);
}


extern "C" {static void *array_QStringList(SIP_SSIZE_T);}
static void *array_QStringList(SIP_SSIZE_T sipNrElem)
{
    return new QStringList[sipNrElem];
}


extern "C" {static void *copy_QStringList(const void *, SIP_SSIZE_T);}
static void *copy_QStringList(const void *sipSrc, SIP_SSIZE_T sipSrcIdx)
{
    return new QStringList(reinterpret_cast<const QStringList *>(sipSrc)[sipSrcIdx]);
}


extern "C" {static void dealloc_QStringList(sipSimpleWrapper *);}
static void dealloc_QStringList(sipSimpleWrapper *sipSelf)
{
    if (sipIsPyOwned(sipSelf))
    {
        release_QStringList(sipSelf->u.cppPtr,0);
    }
}


extern "C" {static void *init_QStringList(sipSimpleWrapper *, PyObject *, PyObject *, PyObject **, PyObject **, PyObject **);}
static void *init_QStringList(sipSimpleWrapper *, PyObject *sipArgs, PyObject *sipKwds, PyObject **sipUnused, PyObject **, PyObject **sipParseErr)
{
    QStringList *sipCpp = 0;

    {
        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, NULL, sipUnused, ""))
        {
            sipCpp = new QStringList();

            return sipCpp;
        }
    }

    {
        const QStringList * a0;

        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, NULL, sipUnused, "J9", sipType_QStringList, &a0))
        {
            sipCpp = new QStringList(*a0);

            return sipCpp;
        }
    }

    {
        const QString * a0;
        int a0State = 0;

        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, NULL, sipUnused, "J1", sipType_QString, &a0, &a0State))
        {
            sipCpp = new QStringList(*a0);
            sipReleaseType(const_cast<QString *>(a0),sipType_QString,a0State);

            return sipCpp;
        }
    }

    return NULL;
}


/* Define this type's Python slots. */
static sipPySlotDef slots_QStringList[] = {
    {(void *)slot_QStringList___ne__, ne_slot},
    {(void *)slot_QStringList___eq__, eq_slot},
    {(void *)slot_QStringList___imul__, irepeat_slot},
    {(void *)slot_QStringList___mul__, repeat_slot},
    {(void *)slot_QStringList___iadd__, iconcat_slot},
    {(void *)slot_QStringList___add__, concat_slot},
    {(void *)slot_QStringList___contains__, contains_slot},
    {(void *)slot_QStringList___getitem__, getitem_slot},
    {(void *)slot_QStringList___delitem__, delitem_slot},
    {(void *)slot_QStringList___setitem__, setitem_slot},
    {(void *)slot_QStringList___len__, len_slot},
    {0, (sipPySlotType)0}
};


static PyMethodDef methods_QStringList[] = {
    {SIP_MLNAME_CAST(sipName_append), meth_QStringList_append, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_clear), meth_QStringList_clear, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_contains), meth_QStringList_contains, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_count), meth_QStringList_count, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_findIndex), meth_QStringList_findIndex, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_first), meth_QStringList_first, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_fromStrList), meth_QStringList_fromStrList, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_grep), meth_QStringList_grep, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_gres), meth_QStringList_gres, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_isEmpty), meth_QStringList_isEmpty, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_join), meth_QStringList_join, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_last), meth_QStringList_last, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_prepend), meth_QStringList_prepend, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_remove), meth_QStringList_remove, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_sort), meth_QStringList_sort, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_split), meth_QStringList_split, METH_VARARGS, NULL}
};


pyqt3ClassTypeDef sipTypeDef_qt_QStringList = {
{
    {
        -1,
        0,
        0,
        SIP_TYPE_CLASS,
        sipNameNr_QStringList,
        {0}
    },
    {
        sipNameNr_QStringList,
        {0, 0, 1},
        16, methods_QStringList,
        0, 0,
        0, 0,
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    },
    0,
    sipNameNr_qt_pyqtWrapperType,
    sipNameNr_qt_pyqtWrapper,
    0,
    slots_QStringList,
    init_QStringList,
    0,
    0,
#if PY_MAJOR_VERSION >= 3
    0,
    0,
#else
    0,
    0,
    0,
    0,
#endif
    dealloc_QStringList,
    assign_QStringList,
    array_QStringList,
    copy_QStringList,
    release_QStringList,
    cast_QStringList,
    0,
    0,
    0
},
    0
};
