/*
 * Interface wrapper code.
 *
 * Generated by SIP 4.10.2 on Mon Mar 28 16:23:15 2011
 *
 * Copyright (c) 2007
 * 	Riverbank Computing Limited <info@riverbankcomputing.co.uk>
 * 
 * This file is part of PyQt.
 * 
 * This copy of PyQt is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the Free
 * Software Foundation; either version 2, or (at your option) any later
 * version.
 * 
 * PyQt is supplied in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
 * details.
 * 
 * You should have received a copy of the GNU General Public License along with
 * PyQt; see the file LICENSE.  If not, write to the Free Software Foundation,
 * Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 */

#include "sipAPIqt.h"

#line 81 "/usr/share/sip/qt/qtextstream.sip"
#include <qtextstream.h>
#line 31 "sipqtQTextStream.cc"

#line 83 "/usr/share/sip/qt/qiodevice.sip"
#include <qiodevice.h>
#line 35 "sipqtQTextStream.cc"
#line 449 "/usr/share/sip/qt/qstring.sip"
#include <qstring.h>
#line 38 "sipqtQTextStream.cc"
#line 98 "/usr/share/sip/qt/qbytearray.sip"
#include <qstring.h>
#line 41 "sipqtQTextStream.cc"
#line 71 "/usr/share/sip/qt/qmainwindow.sip"
#include <qmainwindow.h>
#line 44 "sipqtQTextStream.cc"
#line 43 "/usr/share/sip/qt/qdockarea.sip"
#include <qdockarea.h>
#line 47 "sipqtQTextStream.cc"
#line 84 "/usr/share/sip/qt/qtextcodec.sip"
#include <qtextcodec.h>
#line 50 "sipqtQTextStream.cc"


extern "C" {static PyObject *meth_QTextStream_setEncoding(PyObject *, PyObject *);}
static PyObject *meth_QTextStream_setEncoding(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QTextStream::Encoding a0;
        QTextStream *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BE", &sipSelf, sipType_QTextStream, &sipCpp, sipType_QTextStream_Encoding, &a0))
        {
            sipCpp->setEncoding(a0);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QTextStream, sipName_setEncoding, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QTextStream_setCodec(PyObject *, PyObject *);}
static PyObject *meth_QTextStream_setCodec(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QTextCodec * a0;
        QTextStream *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ8", &sipSelf, sipType_QTextStream, &sipCpp, sipType_QTextCodec, &a0))
        {
            sipCpp->setCodec(a0);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QTextStream, sipName_setCodec, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QTextStream_codec(PyObject *, PyObject *);}
static PyObject *meth_QTextStream_codec(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QTextStream *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QTextStream, &sipCpp))
        {
            QTextCodec *sipRes;

            sipRes = sipCpp->codec();

            return sipConvertFromType(sipRes,sipType_QTextCodec,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QTextStream, sipName_codec, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QTextStream_device(PyObject *, PyObject *);}
static PyObject *meth_QTextStream_device(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QTextStream *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QTextStream, &sipCpp))
        {
            QIODevice *sipRes;

            sipRes = sipCpp->device();

            return sipConvertFromType(sipRes,sipType_QIODevice,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QTextStream, sipName_device, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QTextStream_setDevice(PyObject *, PyObject *);}
static PyObject *meth_QTextStream_setDevice(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QIODevice * a0;
        QTextStream *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ8", &sipSelf, sipType_QTextStream, &sipCpp, sipType_QIODevice, &a0))
        {
            sipCpp->setDevice(a0);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QTextStream, sipName_setDevice, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QTextStream_unsetDevice(PyObject *, PyObject *);}
static PyObject *meth_QTextStream_unsetDevice(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QTextStream *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QTextStream, &sipCpp))
        {
            sipCpp->unsetDevice();

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QTextStream, sipName_unsetDevice, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QTextStream_atEnd(PyObject *, PyObject *);}
static PyObject *meth_QTextStream_atEnd(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QTextStream *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QTextStream, &sipCpp))
        {
            bool sipRes;

            sipRes = sipCpp->atEnd();

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QTextStream, sipName_atEnd, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QTextStream_eof(PyObject *, PyObject *);}
static PyObject *meth_QTextStream_eof(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QTextStream *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QTextStream, &sipCpp))
        {
            bool sipRes;

            sipRes = sipCpp->eof();

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QTextStream, sipName_eof, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QTextStream_readLine(PyObject *, PyObject *);}
static PyObject *meth_QTextStream_readLine(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QTextStream *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QTextStream, &sipCpp))
        {
            QString *sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = new QString(sipCpp->readLine());
            Py_END_ALLOW_THREADS

            return sipConvertFromNewType(sipRes,sipType_QString,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QTextStream, sipName_readLine, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QTextStream_read(PyObject *, PyObject *);}
static PyObject *meth_QTextStream_read(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QTextStream *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QTextStream, &sipCpp))
        {
            QString *sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = new QString(sipCpp->read());
            Py_END_ALLOW_THREADS

            return sipConvertFromNewType(sipRes,sipType_QString,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QTextStream, sipName_read, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QTextStream_skipWhiteSpace(PyObject *, PyObject *);}
static PyObject *meth_QTextStream_skipWhiteSpace(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QTextStream *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QTextStream, &sipCpp))
        {
            sipCpp->skipWhiteSpace();

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QTextStream, sipName_skipWhiteSpace, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QTextStream_flags(PyObject *, PyObject *);}
static PyObject *meth_QTextStream_flags(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QTextStream *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QTextStream, &sipCpp))
        {
            int sipRes;

            sipRes = sipCpp->flags();

            return SIPLong_FromLong(sipRes);
        }
    }

    {
        int a0;
        QTextStream *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bi", &sipSelf, sipType_QTextStream, &sipCpp, &a0))
        {
            int sipRes;

            sipRes = sipCpp->flags(a0);

            return SIPLong_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QTextStream, sipName_flags, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QTextStream_setf(PyObject *, PyObject *);}
static PyObject *meth_QTextStream_setf(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        int a0;
        QTextStream *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bi", &sipSelf, sipType_QTextStream, &sipCpp, &a0))
        {
            int sipRes;

            sipRes = sipCpp->setf(a0);

            return SIPLong_FromLong(sipRes);
        }
    }

    {
        int a0;
        int a1;
        QTextStream *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bii", &sipSelf, sipType_QTextStream, &sipCpp, &a0, &a1))
        {
            int sipRes;

            sipRes = sipCpp->setf(a0,a1);

            return SIPLong_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QTextStream, sipName_setf, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QTextStream_unsetf(PyObject *, PyObject *);}
static PyObject *meth_QTextStream_unsetf(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        int a0;
        QTextStream *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bi", &sipSelf, sipType_QTextStream, &sipCpp, &a0))
        {
            int sipRes;

            sipRes = sipCpp->unsetf(a0);

            return SIPLong_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QTextStream, sipName_unsetf, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QTextStream_reset(PyObject *, PyObject *);}
static PyObject *meth_QTextStream_reset(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QTextStream *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QTextStream, &sipCpp))
        {
            sipCpp->reset();

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QTextStream, sipName_reset, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QTextStream_width(PyObject *, PyObject *);}
static PyObject *meth_QTextStream_width(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QTextStream *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QTextStream, &sipCpp))
        {
            int sipRes;

            sipRes = sipCpp->width();

            return SIPLong_FromLong(sipRes);
        }
    }

    {
        int a0;
        QTextStream *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bi", &sipSelf, sipType_QTextStream, &sipCpp, &a0))
        {
            int sipRes;

            sipRes = sipCpp->width(a0);

            return SIPLong_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QTextStream, sipName_width, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QTextStream_fill(PyObject *, PyObject *);}
static PyObject *meth_QTextStream_fill(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QTextStream *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QTextStream, &sipCpp))
        {
            int sipRes;

            sipRes = sipCpp->fill();

            return SIPLong_FromLong(sipRes);
        }
    }

    {
        int a0;
        QTextStream *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bi", &sipSelf, sipType_QTextStream, &sipCpp, &a0))
        {
            int sipRes;

            sipRes = sipCpp->fill(a0);

            return SIPLong_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QTextStream, sipName_fill, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QTextStream_precision(PyObject *, PyObject *);}
static PyObject *meth_QTextStream_precision(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QTextStream *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QTextStream, &sipCpp))
        {
            int sipRes;

            sipRes = sipCpp->precision();

            return SIPLong_FromLong(sipRes);
        }
    }

    {
        int a0;
        QTextStream *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bi", &sipSelf, sipType_QTextStream, &sipCpp, &a0))
        {
            int sipRes;

            sipRes = sipCpp->precision(a0);

            return SIPLong_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QTextStream, sipName_precision, NULL);

    return NULL;
}


extern "C" {static PyObject *slot_QTextStream___rshift__(PyObject *sipArg0,PyObject *sipArg1);}
static PyObject *slot_QTextStream___rshift__(PyObject *sipArg0,PyObject *sipArg1)
{
    PyObject *sipParseErr = NULL;

    {
        QTextStream * a0;
        QMainWindow * a1;

        if (sipParsePair(&sipParseErr, sipArg0, sipArg1, "J9J9", sipType_QTextStream, &a0, sipType_QMainWindow, &a1))
        {
            QTextStream *sipRes;

            sipRes = &(*a0 >> *a1);

            return sipConvertFromType(sipRes,sipType_QTextStream,NULL);
        }
    }

    {
        QTextStream * a0;
        QDockArea * a1;

        if (sipParsePair(&sipParseErr, sipArg0, sipArg1, "J9J9", sipType_QTextStream, &a0, sipType_QDockArea, &a1))
        {
            QTextStream *sipRes;

            sipRes = &(*a0 >> *a1);

            return sipConvertFromType(sipRes,sipType_QTextStream,NULL);
        }
    }

    Py_XDECREF(sipParseErr);

    if (sipParseErr == Py_None)
        return NULL;

    return sipPySlotExtend(&sipModuleAPI_qt,rshift_slot,NULL,sipArg0,sipArg1);
}


extern "C" {static PyObject *slot_QTextStream___lshift__(PyObject *sipArg0,PyObject *sipArg1);}
static PyObject *slot_QTextStream___lshift__(PyObject *sipArg0,PyObject *sipArg1)
{
    PyObject *sipParseErr = NULL;

    {
        QTextStream * a0;
        const QMainWindow * a1;

        if (sipParsePair(&sipParseErr, sipArg0, sipArg1, "J9J9", sipType_QTextStream, &a0, sipType_QMainWindow, &a1))
        {
            QTextStream *sipRes;

            sipRes = &(*a0 << *a1);

            return sipConvertFromType(sipRes,sipType_QTextStream,NULL);
        }
    }

    {
        QTextStream * a0;
        const QDockArea * a1;

        if (sipParsePair(&sipParseErr, sipArg0, sipArg1, "J9J9", sipType_QTextStream, &a0, sipType_QDockArea, &a1))
        {
            QTextStream *sipRes;

            sipRes = &(*a0 << *a1);

            return sipConvertFromType(sipRes,sipType_QTextStream,NULL);
        }
    }

    Py_XDECREF(sipParseErr);

    if (sipParseErr == Py_None)
        return NULL;

    return sipPySlotExtend(&sipModuleAPI_qt,lshift_slot,NULL,sipArg0,sipArg1);
}


/* Cast a pointer to a type somewhere in its superclass hierarchy. */
extern "C" {static void *cast_QTextStream(void *, const sipTypeDef *);}
static void *cast_QTextStream(void *ptr, const sipTypeDef *targetType)
{
    if (targetType == sipType_QTextStream)
        return ptr;

    return NULL;
}


/* Call the instance's destructor. */
extern "C" {static void release_QTextStream(void *, int);}
static void release_QTextStream(void *sipCppV,int)
{
    delete reinterpret_cast<QTextStream *>(sipCppV);
}


extern "C" {static void dealloc_QTextStream(sipSimpleWrapper *);}
static void dealloc_QTextStream(sipSimpleWrapper *sipSelf)
{
    if (sipIsPyOwned(sipSelf))
    {
        release_QTextStream(sipSelf->u.cppPtr,0);
    }
}


extern "C" {static void *init_QTextStream(sipSimpleWrapper *, PyObject *, PyObject *, PyObject **, PyObject **, PyObject **);}
static void *init_QTextStream(sipSimpleWrapper *, PyObject *sipArgs, PyObject *sipKwds, PyObject **sipUnused, PyObject **, PyObject **sipParseErr)
{
    QTextStream *sipCpp = 0;

    {
        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, NULL, sipUnused, ""))
        {
            sipCpp = new QTextStream();

            return sipCpp;
        }
    }

    {
        QIODevice * a0;

        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, NULL, sipUnused, "J8", sipType_QIODevice, &a0))
        {
            sipCpp = new QTextStream(a0);

            return sipCpp;
        }
    }

    {
        QString * a0;
        int a0State = 0;
        int a1;

        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, NULL, sipUnused, "J0i", sipType_QString, &a0, &a0State, &a1))
        {
            sipCpp = new QTextStream(a0,a1);
            sipReleaseType(a0,sipType_QString,a0State);

            return sipCpp;
        }
    }

    {
        QByteArray * a0;
        int a0State = 0;
        int a1;

        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, NULL, sipUnused, "J1i", sipType_QByteArray, &a0, &a0State, &a1))
        {
            sipCpp = new QTextStream(*a0,a1);
            sipReleaseType(a0,sipType_QByteArray,a0State);

            return sipCpp;
        }
    }

    return NULL;
}


/* Define this type's Python slots. */
static sipPySlotDef slots_QTextStream[] = {
    {(void *)slot_QTextStream___rshift__, rshift_slot},
    {(void *)slot_QTextStream___lshift__, lshift_slot},
    {0, (sipPySlotType)0}
};


static PyMethodDef methods_QTextStream[] = {
    {SIP_MLNAME_CAST(sipName_atEnd), meth_QTextStream_atEnd, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_codec), meth_QTextStream_codec, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_device), meth_QTextStream_device, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_eof), meth_QTextStream_eof, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_fill), meth_QTextStream_fill, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_flags), meth_QTextStream_flags, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_precision), meth_QTextStream_precision, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_read), meth_QTextStream_read, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_readLine), meth_QTextStream_readLine, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_reset), meth_QTextStream_reset, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_setCodec), meth_QTextStream_setCodec, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_setDevice), meth_QTextStream_setDevice, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_setEncoding), meth_QTextStream_setEncoding, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_setf), meth_QTextStream_setf, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_skipWhiteSpace), meth_QTextStream_skipWhiteSpace, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_unsetDevice), meth_QTextStream_unsetDevice, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_unsetf), meth_QTextStream_unsetf, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_width), meth_QTextStream_width, METH_VARARGS, NULL}
};

static sipEnumMemberDef enummembers_QTextStream[] = {
    {sipName_Latin1, QTextStream::Latin1, 341},
    {sipName_Locale, QTextStream::Locale, 341},
    {sipName_RawUnicode, QTextStream::RawUnicode, 341},
    {sipName_Unicode, QTextStream::Unicode, 341},
    {sipName_UnicodeNetworkOrder, QTextStream::UnicodeNetworkOrder, 341},
    {sipName_UnicodeReverse, QTextStream::UnicodeReverse, 341},
    {sipName_UnicodeUTF8, QTextStream::UnicodeUTF8, 341},
    {sipName_bin, QTextStream::bin, -1},
    {sipName_dec, QTextStream::dec, -1},
    {sipName_fixed, QTextStream::fixed, -1},
    {sipName_hex, QTextStream::hex, -1},
    {sipName_internal, QTextStream::internal, -1},
    {sipName_left, QTextStream::left, -1},
    {sipName_oct, QTextStream::oct, -1},
    {sipName_right, QTextStream::right, -1},
    {sipName_scientific, QTextStream::scientific, -1},
    {sipName_showbase, QTextStream::showbase, -1},
    {sipName_showpoint, QTextStream::showpoint, -1},
    {sipName_showpos, QTextStream::showpos, -1},
    {sipName_skipws, QTextStream::skipws, -1},
    {sipName_uppercase, QTextStream::uppercase, -1},
};


extern "C" {static PyObject *varget_QTextStream_adjustfield(void *, PyObject *);}
static PyObject *varget_QTextStream_adjustfield(void *, PyObject *)
{
    int sipVal;
    sipVal = QTextStream::adjustfield;

    return SIPLong_FromLong(sipVal);
}


extern "C" {static PyObject *varget_QTextStream_basefield(void *, PyObject *);}
static PyObject *varget_QTextStream_basefield(void *, PyObject *)
{
    int sipVal;
    sipVal = QTextStream::basefield;

    return SIPLong_FromLong(sipVal);
}


extern "C" {static PyObject *varget_QTextStream_floatfield(void *, PyObject *);}
static PyObject *varget_QTextStream_floatfield(void *, PyObject *)
{
    int sipVal;
    sipVal = QTextStream::floatfield;

    return SIPLong_FromLong(sipVal);
}

sipVariableDef variables_QTextStream[] = {
    {sipName_adjustfield, varget_QTextStream_adjustfield, NULL, 1},
    {sipName_basefield, varget_QTextStream_basefield, NULL, 1},
    {sipName_floatfield, varget_QTextStream_floatfield, NULL, 1},
};


pyqt3ClassTypeDef sipTypeDef_qt_QTextStream = {
{
    {
        -1,
        0,
        0,
        SIP_TYPE_CLASS,
        sipNameNr_QTextStream,
        {0}
    },
    {
        sipNameNr_QTextStream,
        {0, 0, 1},
        18, methods_QTextStream,
        21, enummembers_QTextStream,
        3, variables_QTextStream,
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    },
    0,
    sipNameNr_qt_pyqtWrapperType,
    sipNameNr_qt_pyqtWrapper,
    0,
    slots_QTextStream,
    init_QTextStream,
    0,
    0,
#if PY_MAJOR_VERSION >= 3
    0,
    0,
#else
    0,
    0,
    0,
    0,
#endif
    dealloc_QTextStream,
    0,
    0,
    0,
    release_QTextStream,
    cast_QTextStream,
    0,
    0,
    0
},
    0
};
