/*
 * Interface wrapper code.
 *
 * Generated by SIP 4.10.2 on Mon Mar 28 16:23:14 2011
 *
 * Copyright (c) 2007
 * 	Riverbank Computing Limited <info@riverbankcomputing.co.uk>
 * 
 * This file is part of PyQt.
 * 
 * This copy of PyQt is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the Free
 * Software Foundation; either version 2, or (at your option) any later
 * version.
 * 
 * PyQt is supplied in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
 * details.
 * 
 * You should have received a copy of the GNU General Public License along with
 * PyQt; see the file LICENSE.  If not, write to the Free Software Foundation,
 * Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 */

#include "sipAPIqt.h"

#line 40 "/usr/share/sip/qt/qvaluelist.sip"
#include <qvaluelist.h>
#line 31 "sipqtQValueList0100QUrlInfo.cc"

#line 38 "/usr/share/sip/qt/qurlinfo.sip"
#include <qurlinfo.h>
#line 35 "sipqtQValueList0100QUrlInfo.cc"


extern "C" {static void assign_QValueList_0100QUrlInfo(void *, SIP_SSIZE_T, const void *);}
static void assign_QValueList_0100QUrlInfo(void *sipDst, SIP_SSIZE_T sipDstIdx, const void *sipSrc)
{
    reinterpret_cast<QValueList<QUrlInfo> *>(sipDst)[sipDstIdx] = *reinterpret_cast<const QValueList<QUrlInfo> *>(sipSrc);
}


extern "C" {static void *array_QValueList_0100QUrlInfo(SIP_SSIZE_T);}
static void *array_QValueList_0100QUrlInfo(SIP_SSIZE_T sipNrElem)
{
    return new QValueList<QUrlInfo>[sipNrElem];
}


extern "C" {static void *copy_QValueList_0100QUrlInfo(const void *, SIP_SSIZE_T);}
static void *copy_QValueList_0100QUrlInfo(const void *sipSrc, SIP_SSIZE_T sipSrcIdx)
{
    return new QValueList<QUrlInfo>(reinterpret_cast<const QValueList<QUrlInfo> *>(sipSrc)[sipSrcIdx]);
}


/* Call the mapped type's destructor. */
extern "C" {static void release_QValueList_0100QUrlInfo(void *, int);}
static void release_QValueList_0100QUrlInfo(void *ptr, int)
{
    delete reinterpret_cast<QValueList<QUrlInfo> *>(ptr);
}



extern "C" {static int convertTo_QValueList_0100QUrlInfo(PyObject *, void **, int *, PyObject *);}
static int convertTo_QValueList_0100QUrlInfo(PyObject *sipPy,void **sipCppPtrV,int *sipIsErr,PyObject *sipTransferObj)
{
    QValueList<QUrlInfo> **sipCppPtr = reinterpret_cast<QValueList<QUrlInfo> **>(sipCppPtrV);

#line 76 "/usr/share/sip/qt/qvaluelist.sip"
	if (sipIsErr == NULL)
	{
		if (!PyList_Check(sipPy))
			return 0;

		for (int i = 0; i < PyList_GET_SIZE(sipPy); ++i)
			if (!sipCanConvertToInstance(PyList_GET_ITEM(sipPy,i),sipClass_QUrlInfo,SIP_NOT_NONE))
				return 0;

		return 1;
	}

	QValueList<QUrlInfo> *qvl = new QValueList<QUrlInfo>;
 
	for (int i = 0; i < PyList_GET_SIZE(sipPy); ++i)
	{
		int iserr = 0, state;

		// We apply the transfer to the list itself, not the elements.
		QUrlInfo *itm = reinterpret_cast<QUrlInfo *>(sipConvertToInstance(PyList_GET_ITEM(sipPy,i),sipClass_QUrlInfo,0,SIP_NOT_NONE,&state,&iserr));

		if (iserr)
		{
			sipReleaseInstance(itm,sipClass_QUrlInfo,state);

			*sipIsErr = 1;
			delete qvl;

			return 0;
		}

		qvl -> append(*itm);

		sipReleaseInstance(itm,sipClass_QUrlInfo,state);
	}
 
	*sipCppPtr = qvl;
 
	return sipGetState(sipTransferObj);
#line 113 "sipqtQValueList0100QUrlInfo.cc"
}


extern "C" {static PyObject *convertFrom_QValueList_0100QUrlInfo(void *, PyObject *);}
static PyObject *convertFrom_QValueList_0100QUrlInfo(void *sipCppV,PyObject *sipTransferObj)
{
   QValueList<QUrlInfo> *sipCpp = reinterpret_cast<QValueList<QUrlInfo> *>(sipCppV);

#line 44 "/usr/share/sip/qt/qvaluelist.sip"
	int i;
	PyObject *l;

	// Create the list.

	if ((l = PyList_New(sipCpp -> count())) == NULL)
		return NULL;

	// Get it.

	i = 0;
	QValueListConstIterator<QUrlInfo> it;

	for (it = sipCpp -> begin(); it != sipCpp -> end(); ++it)
	{
		PyObject *tmobj;

		if ((tmobj = sipConvertFromNewInstance(new QUrlInfo(*it),sipClass_QUrlInfo,sipTransferObj)) == NULL || PyList_SetItem(l,i,tmobj) < 0)
		{
			Py_XDECREF(tmobj);
			Py_DECREF(l);

			return NULL;
		}

		++i;
	}

	return l;
#line 152 "sipqtQValueList0100QUrlInfo.cc"
}


sipMappedTypeDef sipTypeDef_qt_QValueList_0100QUrlInfo = {
    {
        -1,
        0,
        0,
        SIP_TYPE_MAPPED,
        sipNameNr_8154,
        {0}
    },
    {
        -1,
        {0, 0, 1},
        0, 0,
        0, 0,
        0, 0,
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
    },
    assign_QValueList_0100QUrlInfo,
    array_QValueList_0100QUrlInfo,
    copy_QValueList_0100QUrlInfo,
    release_QValueList_0100QUrlInfo,
    convertTo_QValueList_0100QUrlInfo,
    convertFrom_QValueList_0100QUrlInfo
};
