/*
 * Interface wrapper code.
 *
 * Generated by SIP 4.10.2 on Mon Mar 28 16:23:16 2011
 *
 * Copyright (c) 2007
 * 	Riverbank Computing Limited <info@riverbankcomputing.co.uk>
 * 
 * This file is part of PyQt.
 * 
 * This copy of PyQt is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the Free
 * Software Foundation; either version 2, or (at your option) any later
 * version.
 * 
 * PyQt is supplied in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
 * details.
 * 
 * You should have received a copy of the GNU General Public License along with
 * PyQt; see the file LICENSE.  If not, write to the Free Software Foundation,
 * Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 */

#include "sipAPIqt.h"

#line 729 "/usr/share/sip/qt/qlistview.sip"
#include <qlistview.h>
#line 31 "sipqtQListViewItemIterator.cc"

#line 147 "/usr/share/sip/qt/qlistview.sip"
#include <qlistview.h>
#line 35 "sipqtQListViewItemIterator.cc"
#line 298 "/usr/share/sip/qt/qlistview.sip"
#include <qlistview.h>
#line 38 "sipqtQListViewItemIterator.cc"


extern "C" {static PyObject *meth_QListViewItemIterator_current(PyObject *, PyObject *);}
static PyObject *meth_QListViewItemIterator_current(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QListViewItemIterator *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QListViewItemIterator, &sipCpp))
        {
            QListViewItem *sipRes;

            sipRes = sipCpp->current();

            return sipConvertFromType(sipRes,sipType_QListViewItem,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QListViewItemIterator, sipName_current, NULL);

    return NULL;
}


extern "C" {static PyObject *slot_QListViewItemIterator___isub__(PyObject *sipSelf,PyObject *sipArg);}
static PyObject *slot_QListViewItemIterator___isub__(PyObject *sipSelf,PyObject *sipArg)
{
    if (!PyObject_TypeCheck(sipSelf, sipTypeAsPyTypeObject(sipType_QListViewItemIterator)))
    {
        Py_INCREF(Py_NotImplemented);
        return Py_NotImplemented;
    }

    QListViewItemIterator *sipCpp = reinterpret_cast<QListViewItemIterator *>(sipGetCppPtr((sipSimpleWrapper *)sipSelf,sipType_QListViewItemIterator));

    if (!sipCpp)
        return 0;

    PyObject *sipParseErr = NULL;

    {
        int a0;

        if (sipParseArgs(&sipParseErr, sipArg, "1i", &a0))
        {
            sipCpp->QListViewItemIterator::operator-=(a0);

            Py_INCREF(sipSelf);
            return sipSelf;
        }
    }

    Py_XDECREF(sipParseErr);

    if (sipParseErr == Py_None)
        return NULL;

    PyErr_Clear();

    Py_INCREF(Py_NotImplemented);
    return Py_NotImplemented;
}


extern "C" {static PyObject *slot_QListViewItemIterator___iadd__(PyObject *sipSelf,PyObject *sipArg);}
static PyObject *slot_QListViewItemIterator___iadd__(PyObject *sipSelf,PyObject *sipArg)
{
    if (!PyObject_TypeCheck(sipSelf, sipTypeAsPyTypeObject(sipType_QListViewItemIterator)))
    {
        Py_INCREF(Py_NotImplemented);
        return Py_NotImplemented;
    }

    QListViewItemIterator *sipCpp = reinterpret_cast<QListViewItemIterator *>(sipGetCppPtr((sipSimpleWrapper *)sipSelf,sipType_QListViewItemIterator));

    if (!sipCpp)
        return 0;

    PyObject *sipParseErr = NULL;

    {
        int a0;

        if (sipParseArgs(&sipParseErr, sipArg, "1i", &a0))
        {
            sipCpp->QListViewItemIterator::operator+=(a0);

            Py_INCREF(sipSelf);
            return sipSelf;
        }
    }

    Py_XDECREF(sipParseErr);

    if (sipParseErr == Py_None)
        return NULL;

    PyErr_Clear();

    Py_INCREF(Py_NotImplemented);
    return Py_NotImplemented;
}


/* Cast a pointer to a type somewhere in its superclass hierarchy. */
extern "C" {static void *cast_QListViewItemIterator(void *, const sipTypeDef *);}
static void *cast_QListViewItemIterator(void *ptr, const sipTypeDef *targetType)
{
    if (targetType == sipType_QListViewItemIterator)
        return ptr;

    return NULL;
}


/* Call the instance's destructor. */
extern "C" {static void release_QListViewItemIterator(void *, int);}
static void release_QListViewItemIterator(void *sipCppV,int)
{
    delete reinterpret_cast<QListViewItemIterator *>(sipCppV);
}


extern "C" {static void assign_QListViewItemIterator(void *, SIP_SSIZE_T, const void *);}
static void assign_QListViewItemIterator(void *sipDst, SIP_SSIZE_T sipDstIdx, const void *sipSrc)
{
    reinterpret_cast<QListViewItemIterator *>(sipDst)[sipDstIdx] = *reinterpret_cast<const QListViewItemIterator *>(sipSrc);
}


extern "C" {static void *array_QListViewItemIterator(SIP_SSIZE_T);}
static void *array_QListViewItemIterator(SIP_SSIZE_T sipNrElem)
{
    return new QListViewItemIterator[sipNrElem];
}


extern "C" {static void *copy_QListViewItemIterator(const void *, SIP_SSIZE_T);}
static void *copy_QListViewItemIterator(const void *sipSrc, SIP_SSIZE_T sipSrcIdx)
{
    return new QListViewItemIterator(reinterpret_cast<const QListViewItemIterator *>(sipSrc)[sipSrcIdx]);
}


extern "C" {static void dealloc_QListViewItemIterator(sipSimpleWrapper *);}
static void dealloc_QListViewItemIterator(sipSimpleWrapper *sipSelf)
{
    if (sipIsPyOwned(sipSelf))
    {
        release_QListViewItemIterator(sipSelf->u.cppPtr,0);
    }
}


extern "C" {static void *init_QListViewItemIterator(sipSimpleWrapper *, PyObject *, PyObject *, PyObject **, PyObject **, PyObject **);}
static void *init_QListViewItemIterator(sipSimpleWrapper *, PyObject *sipArgs, PyObject *sipKwds, PyObject **sipUnused, PyObject **, PyObject **sipParseErr)
{
    QListViewItemIterator *sipCpp = 0;

    {
        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, NULL, sipUnused, ""))
        {
            sipCpp = new QListViewItemIterator();

            return sipCpp;
        }
    }

    {
        QListViewItem * a0;

        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, NULL, sipUnused, "J8", sipType_QListViewItem, &a0))
        {
            sipCpp = new QListViewItemIterator(a0);

            return sipCpp;
        }
    }

    {
        QListViewItem * a0;
        int a1;

        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, NULL, sipUnused, "J8i", sipType_QListViewItem, &a0, &a1))
        {
            sipCpp = new QListViewItemIterator(a0,a1);

            return sipCpp;
        }
    }

    {
        const QListViewItemIterator * a0;

        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, NULL, sipUnused, "J9", sipType_QListViewItemIterator, &a0))
        {
            sipCpp = new QListViewItemIterator(*a0);

            return sipCpp;
        }
    }

    {
        QListView * a0;

        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, NULL, sipUnused, "J8", sipType_QListView, &a0))
        {
            sipCpp = new QListViewItemIterator(a0);

            return sipCpp;
        }
    }

    {
        QListView * a0;
        int a1;

        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, NULL, sipUnused, "J8i", sipType_QListView, &a0, &a1))
        {
            sipCpp = new QListViewItemIterator(a0,a1);

            return sipCpp;
        }
    }

    return NULL;
}


/* Define this type's Python slots. */
static sipPySlotDef slots_QListViewItemIterator[] = {
    {(void *)slot_QListViewItemIterator___isub__, isub_slot},
    {(void *)slot_QListViewItemIterator___iadd__, iadd_slot},
    {0, (sipPySlotType)0}
};


static PyMethodDef methods_QListViewItemIterator[] = {
    {SIP_MLNAME_CAST(sipName_current), meth_QListViewItemIterator_current, METH_VARARGS, NULL}
};

static sipEnumMemberDef enummembers_QListViewItemIterator[] = {
    {sipName_Checked, QListViewItemIterator::Checked, 168},
    {sipName_DragDisabled, QListViewItemIterator::DragDisabled, 168},
    {sipName_DragEnabled, QListViewItemIterator::DragEnabled, 168},
    {sipName_DropDisabled, QListViewItemIterator::DropDisabled, 168},
    {sipName_DropEnabled, QListViewItemIterator::DropEnabled, 168},
    {sipName_Expandable, QListViewItemIterator::Expandable, 168},
    {sipName_Invisible, QListViewItemIterator::Invisible, 168},
    {sipName_NotChecked, QListViewItemIterator::NotChecked, 168},
    {sipName_NotExpandable, QListViewItemIterator::NotExpandable, 168},
    {sipName_NotSelectable, QListViewItemIterator::NotSelectable, 168},
    {sipName_Selectable, QListViewItemIterator::Selectable, 168},
    {sipName_Selected, QListViewItemIterator::Selected, 168},
    {sipName_Unselected, QListViewItemIterator::Unselected, 168},
    {sipName_Visible, QListViewItemIterator::Visible, 168},
};


pyqt3ClassTypeDef sipTypeDef_qt_QListViewItemIterator = {
{
    {
        -1,
        0,
        0,
        SIP_TYPE_CLASS,
        sipNameNr_QListViewItemIterator,
        {0}
    },
    {
        sipNameNr_QListViewItemIterator,
        {0, 0, 1},
        1, methods_QListViewItemIterator,
        14, enummembers_QListViewItemIterator,
        0, 0,
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    },
    0,
    sipNameNr_qt_pyqtWrapperType,
    sipNameNr_qt_pyqtWrapper,
    0,
    slots_QListViewItemIterator,
    init_QListViewItemIterator,
    0,
    0,
#if PY_MAJOR_VERSION >= 3
    0,
    0,
#else
    0,
    0,
    0,
    0,
#endif
    dealloc_QListViewItemIterator,
    assign_QListViewItemIterator,
    array_QListViewItemIterator,
    copy_QListViewItemIterator,
    release_QListViewItemIterator,
    cast_QListViewItemIterator,
    0,
    0,
    0
},
    0
};
