/*
 * Interface wrapper code.
 *
 * Generated by SIP 4.10.2 on Mon Mar 28 16:23:15 2011
 *
 * Copyright (c) 2007
 * 	Riverbank Computing Limited <info@riverbankcomputing.co.uk>
 * 
 * This file is part of PyQt.
 * 
 * This copy of PyQt is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the Free
 * Software Foundation; either version 2, or (at your option) any later
 * version.
 * 
 * PyQt is supplied in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
 * details.
 * 
 * You should have received a copy of the GNU General Public License along with
 * PyQt; see the file LICENSE.  If not, write to the Free Software Foundation,
 * Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 */

#include "sipAPIqt.h"

#line 449 "/usr/share/sip/qt/qstring.sip"
#include <qstring.h>
#line 31 "sipqtQString.cc"

#line 180 "/usr/share/sip/qt/qstring.sip"
#include <qstring.h>
#line 35 "sipqtQString.cc"
#line 98 "/usr/share/sip/qt/qbytearray.sip"
#include <qstring.h>
#line 38 "sipqtQString.cc"
#line 39 "/usr/share/sip/qt/qurl.sip"
#include <qurl.h>
#line 41 "sipqtQString.cc"
#line 40 "/usr/share/sip/qt/qkeysequence.sip"
#include <qkeysequence.h>
#line 44 "sipqtQString.cc"
#line 37 "/usr/share/sip/qt/quuid.sip"
#include <quuid.h>
#line 47 "sipqtQString.cc"
#line 120 "/usr/share/sip/qt/qcstring.sip"
#include <qcstring.h>
#line 50 "sipqtQString.cc"
#line 60 "/usr/share/sip/qt/qregexp.sip"
#include <qregexp.h>
#line 53 "sipqtQString.cc"
#line 822 "/usr/share/sip/qt/qstring.sip"
#include <qtextcodec.h>

#if PY_VERSION_HEX >= 0x01060000
// Convenience function for converting a QString to a Python Unicode object.
static PyObject *QStringToPyUnicode(QString *qs)
{
	PyObject *uobj;

	if ((uobj = PyUnicode_FromUnicode(NULL,qs -> length())) == NULL)
		return NULL;

	Py_UNICODE *pyu = PyUnicode_AS_UNICODE(uobj);

	for (uint i = 0; i < qs -> length(); ++i)
		*pyu++ = (qs -> at(i)).unicode();

	return uobj;
}
#endif

// Convenience function for converting a Python unicode or string object to a
// QString on the heap.
static QString *PyUnicodeStringToQString(PyObject *py)
{
#if PY_VERSION_HEX >= 0x01060000
	if (PyUnicode_Check(py))
	{
		QString *qs = new QString;

#if defined(Py_UNICODE_WIDE)
		PY_UNICODE_TYPE *ucode = PyUnicode_AS_UNICODE(py);
		int len = PyUnicode_GET_SIZE(py);

		for (int i = 0; i < len; ++i)
			qs->ref(i) = (uint)ucode[i];
#else
		qs -> setUnicodeCodes((ushort *)PyUnicode_AS_UNICODE(py),PyUnicode_GET_SIZE(py));
#endif

		return qs;
	}
#endif

	if (PyString_Check(py))
		return new QString(PyString_AS_STRING(py));

	return 0;
}
#line 103 "sipqtQString.cc"


extern "C" {static PyObject *meth_QString_isNull(PyObject *, PyObject *);}
static PyObject *meth_QString_isNull(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QString, &sipCpp))
        {
            bool sipRes;

            sipRes = sipCpp->isNull();

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QString, sipName_isNull, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QString_isEmpty(PyObject *, PyObject *);}
static PyObject *meth_QString_isEmpty(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QString, &sipCpp))
        {
            bool sipRes;

            sipRes = sipCpp->isEmpty();

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QString, sipName_isEmpty, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QString_length(PyObject *, PyObject *);}
static PyObject *meth_QString_length(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QString, &sipCpp))
        {
            uint sipRes;

            sipRes = sipCpp->length();

            return PyLong_FromUnsignedLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QString, sipName_length, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QString_truncate(PyObject *, PyObject *);}
static PyObject *meth_QString_truncate(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        uint a0;
        QString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bu", &sipSelf, sipType_QString, &sipCpp, &a0))
        {
            sipCpp->truncate(a0);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QString, sipName_truncate, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QString_fill(PyObject *, PyObject *);}
static PyObject *meth_QString_fill(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QChar * a0;
        int a1 = -1;
        QString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ9|i", &sipSelf, sipType_QString, &sipCpp, sipType_QChar, &a0, &a1))
        {
            QString *sipRes;

            sipRes = &sipCpp->fill(*a0,a1);

            return sipConvertFromType(sipRes,sipType_QString,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QString, sipName_fill, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QString_copy(PyObject *, PyObject *);}
static PyObject *meth_QString_copy(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QString, &sipCpp))
        {
            QString *sipRes;

            sipRes = new QString(sipCpp->copy());

            return sipConvertFromNewType(sipRes,sipType_QString,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QString, sipName_copy, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QString_arg(PyObject *, PyObject *);}
static PyObject *meth_QString_arg(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        int a0;
        int a1 = 0;
        int a2 = 10;
        QString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BXi|ii", &sipSelf, sipType_QString, &sipCpp, &a0, &a1, &a2))
        {
            QString *sipRes;

            sipRes = new QString(sipCpp->arg(a0,a1,a2));

            return sipConvertFromNewType(sipRes,sipType_QString,NULL);
        }
    }

    {
        double a0;
        int a1 = 0;
        char a2 = 'g';
        int a3 = -1;
        QString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BXd|ici", &sipSelf, sipType_QString, &sipCpp, &a0, &a1, &a2, &a3))
        {
            QString *sipRes;

            sipRes = new QString(sipCpp->arg(a0,a1,a2,a3));

            return sipConvertFromNewType(sipRes,sipType_QString,NULL);
        }
    }

    {
        long a0;
        int a1 = 0;
        int a2 = 10;
        QString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bl|ii", &sipSelf, sipType_QString, &sipCpp, &a0, &a1, &a2))
        {
            QString *sipRes;

            sipRes = new QString(sipCpp->arg(a0,a1,a2));

            return sipConvertFromNewType(sipRes,sipType_QString,NULL);
        }
    }

    {
        ulong a0;
        int a1 = 0;
        int a2 = 10;
        QString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bm|ii", &sipSelf, sipType_QString, &sipCpp, &a0, &a1, &a2))
        {
            QString *sipRes;

            sipRes = new QString(sipCpp->arg(a0,a1,a2));

            return sipConvertFromNewType(sipRes,sipType_QString,NULL);
        }
    }

    {
        char a0;
        int a1 = 0;
        QString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bc|i", &sipSelf, sipType_QString, &sipCpp, &a0, &a1))
        {
            QString *sipRes;

            sipRes = new QString(sipCpp->arg(a0,a1));

            return sipConvertFromNewType(sipRes,sipType_QString,NULL);
        }
    }

    {
        QChar * a0;
        int a1 = 0;
        QString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ9|i", &sipSelf, sipType_QString, &sipCpp, sipType_QChar, &a0, &a1))
        {
            QString *sipRes;

            sipRes = new QString(sipCpp->arg(*a0,a1));

            return sipConvertFromNewType(sipRes,sipType_QString,NULL);
        }
    }

    {
        const QString * a0;
        int a0State = 0;
        int a1 = 0;
        QString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ1|i", &sipSelf, sipType_QString, &sipCpp, sipType_QString, &a0, &a0State, &a1))
        {
            QString *sipRes;

            sipRes = new QString(sipCpp->arg(*a0,a1));
            sipReleaseType(const_cast<QString *>(a0),sipType_QString,a0State);

            return sipConvertFromNewType(sipRes,sipType_QString,NULL);
        }
    }

    {
        const QString * a0;
        int a0State = 0;
        const QString * a1;
        int a1State = 0;
        QString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ1J1", &sipSelf, sipType_QString, &sipCpp, sipType_QString, &a0, &a0State, sipType_QString, &a1, &a1State))
        {
            QString *sipRes;

            sipRes = new QString(sipCpp->arg(*a0,*a1));
            sipReleaseType(const_cast<QString *>(a0),sipType_QString,a0State);
            sipReleaseType(const_cast<QString *>(a1),sipType_QString,a1State);

            return sipConvertFromNewType(sipRes,sipType_QString,NULL);
        }
    }

    {
        const QString * a0;
        int a0State = 0;
        const QString * a1;
        int a1State = 0;
        const QString * a2;
        int a2State = 0;
        QString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ1J1J1", &sipSelf, sipType_QString, &sipCpp, sipType_QString, &a0, &a0State, sipType_QString, &a1, &a1State, sipType_QString, &a2, &a2State))
        {
            QString *sipRes;

            sipRes = new QString(sipCpp->arg(*a0,*a1,*a2));
            sipReleaseType(const_cast<QString *>(a0),sipType_QString,a0State);
            sipReleaseType(const_cast<QString *>(a1),sipType_QString,a1State);
            sipReleaseType(const_cast<QString *>(a2),sipType_QString,a2State);

            return sipConvertFromNewType(sipRes,sipType_QString,NULL);
        }
    }

    {
        const QString * a0;
        int a0State = 0;
        const QString * a1;
        int a1State = 0;
        const QString * a2;
        int a2State = 0;
        const QString * a3;
        int a3State = 0;
        QString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ1J1J1J1", &sipSelf, sipType_QString, &sipCpp, sipType_QString, &a0, &a0State, sipType_QString, &a1, &a1State, sipType_QString, &a2, &a2State, sipType_QString, &a3, &a3State))
        {
            QString *sipRes;

            sipRes = new QString(sipCpp->arg(*a0,*a1,*a2,*a3));
            sipReleaseType(const_cast<QString *>(a0),sipType_QString,a0State);
            sipReleaseType(const_cast<QString *>(a1),sipType_QString,a1State);
            sipReleaseType(const_cast<QString *>(a2),sipType_QString,a2State);
            sipReleaseType(const_cast<QString *>(a3),sipType_QString,a3State);

            return sipConvertFromNewType(sipRes,sipType_QString,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QString, sipName_arg, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QString_find(PyObject *, PyObject *);}
static PyObject *meth_QString_find(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QChar * a0;
        int a1 = 0;
        bool a2 = 1;
        QString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ9|ib", &sipSelf, sipType_QString, &sipCpp, sipType_QChar, &a0, &a1, &a2))
        {
            int sipRes;

            sipRes = sipCpp->find(*a0,a1,a2);

            return SIPLong_FromLong(sipRes);
        }
    }

    {
        char a0;
        int a1 = 0;
        bool a2 = 1;
        QString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bc|ib", &sipSelf, sipType_QString, &sipCpp, &a0, &a1, &a2))
        {
            int sipRes;

            sipRes = sipCpp->find(a0,a1,a2);

            return SIPLong_FromLong(sipRes);
        }
    }

    {
        const QString * a0;
        int a0State = 0;
        int a1 = 0;
        bool a2 = 1;
        QString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ1|ib", &sipSelf, sipType_QString, &sipCpp, sipType_QString, &a0, &a0State, &a1, &a2))
        {
            int sipRes;

            sipRes = sipCpp->find(*a0,a1,a2);
            sipReleaseType(const_cast<QString *>(a0),sipType_QString,a0State);

            return SIPLong_FromLong(sipRes);
        }
    }

    {
        const QRegExp * a0;
        int a1 = 0;
        QString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ9|i", &sipSelf, sipType_QString, &sipCpp, sipType_QRegExp, &a0, &a1))
        {
            int sipRes;

            sipRes = sipCpp->find(*a0,a1);

            return SIPLong_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QString, sipName_find, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QString_findRev(PyObject *, PyObject *);}
static PyObject *meth_QString_findRev(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QChar * a0;
        int a1 = -1;
        bool a2 = 1;
        QString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ9|ib", &sipSelf, sipType_QString, &sipCpp, sipType_QChar, &a0, &a1, &a2))
        {
            int sipRes;

            sipRes = sipCpp->findRev(*a0,a1,a2);

            return SIPLong_FromLong(sipRes);
        }
    }

    {
        char a0;
        int a1 = -1;
        bool a2 = 1;
        QString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bc|ib", &sipSelf, sipType_QString, &sipCpp, &a0, &a1, &a2))
        {
            int sipRes;

            sipRes = sipCpp->findRev(a0,a1,a2);

            return SIPLong_FromLong(sipRes);
        }
    }

    {
        const QString * a0;
        int a0State = 0;
        int a1 = -1;
        bool a2 = 1;
        QString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ1|ib", &sipSelf, sipType_QString, &sipCpp, sipType_QString, &a0, &a0State, &a1, &a2))
        {
            int sipRes;

            sipRes = sipCpp->findRev(*a0,a1,a2);
            sipReleaseType(const_cast<QString *>(a0),sipType_QString,a0State);

            return SIPLong_FromLong(sipRes);
        }
    }

    {
        const QRegExp * a0;
        int a1 = -1;
        QString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ9|i", &sipSelf, sipType_QString, &sipCpp, sipType_QRegExp, &a0, &a1))
        {
            int sipRes;

            sipRes = sipCpp->findRev(*a0,a1);

            return SIPLong_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QString, sipName_findRev, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QString_contains(PyObject *, PyObject *);}
static PyObject *meth_QString_contains(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QChar * a0;
        bool a1 = 1;
        QString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ9|b", &sipSelf, sipType_QString, &sipCpp, sipType_QChar, &a0, &a1))
        {
            int sipRes;

            sipRes = sipCpp->contains(*a0,a1);

            return SIPLong_FromLong(sipRes);
        }
    }

    {
        char a0;
        bool a1 = 1;
        QString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bc|b", &sipSelf, sipType_QString, &sipCpp, &a0, &a1))
        {
            int sipRes;

            sipRes = sipCpp->contains(a0,a1);

            return SIPLong_FromLong(sipRes);
        }
    }

    {
        const QString * a0;
        int a0State = 0;
        bool a1 = 1;
        QString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ1|b", &sipSelf, sipType_QString, &sipCpp, sipType_QString, &a0, &a0State, &a1))
        {
            int sipRes;

            sipRes = sipCpp->contains(*a0,a1);
            sipReleaseType(const_cast<QString *>(a0),sipType_QString,a0State);

            return SIPLong_FromLong(sipRes);
        }
    }

    {
        const QRegExp * a0;
        QString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ9", &sipSelf, sipType_QString, &sipCpp, sipType_QRegExp, &a0))
        {
            int sipRes;

            sipRes = sipCpp->contains(*a0);

            return SIPLong_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QString, sipName_contains, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QString_section(PyObject *, PyObject *);}
static PyObject *meth_QString_section(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QChar * a0;
        int a1;
        int a2 = 4294967295;
        int a3 = QString::SectionDefault;
        QString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ9i|ii", &sipSelf, sipType_QString, &sipCpp, sipType_QChar, &a0, &a1, &a2, &a3))
        {
            QString *sipRes;

            sipRes = new QString(sipCpp->section(*a0,a1,a2,a3));

            return sipConvertFromNewType(sipRes,sipType_QString,NULL);
        }
    }

    {
        const QString * a0;
        int a0State = 0;
        int a1;
        int a2 = 4294967295;
        int a3 = QString::SectionDefault;
        QString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ1i|ii", &sipSelf, sipType_QString, &sipCpp, sipType_QString, &a0, &a0State, &a1, &a2, &a3))
        {
            QString *sipRes;

            sipRes = new QString(sipCpp->section(*a0,a1,a2,a3));
            sipReleaseType(const_cast<QString *>(a0),sipType_QString,a0State);

            return sipConvertFromNewType(sipRes,sipType_QString,NULL);
        }
    }

    {
        const QRegExp * a0;
        int a1;
        int a2 = 4294967295;
        int a3 = QString::SectionDefault;
        QString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ9i|ii", &sipSelf, sipType_QString, &sipCpp, sipType_QRegExp, &a0, &a1, &a2, &a3))
        {
            QString *sipRes;

            sipRes = new QString(sipCpp->section(*a0,a1,a2,a3));

            return sipConvertFromNewType(sipRes,sipType_QString,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QString, sipName_section, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QString_left(PyObject *, PyObject *);}
static PyObject *meth_QString_left(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        uint a0;
        QString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bu", &sipSelf, sipType_QString, &sipCpp, &a0))
        {
            QString *sipRes;

            sipRes = new QString(sipCpp->left(a0));

            return sipConvertFromNewType(sipRes,sipType_QString,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QString, sipName_left, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QString_right(PyObject *, PyObject *);}
static PyObject *meth_QString_right(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        uint a0;
        QString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bu", &sipSelf, sipType_QString, &sipCpp, &a0))
        {
            QString *sipRes;

            sipRes = new QString(sipCpp->right(a0));

            return sipConvertFromNewType(sipRes,sipType_QString,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QString, sipName_right, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QString_mid(PyObject *, PyObject *);}
static PyObject *meth_QString_mid(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        uint a0;
        uint a1 = 4294967295;
        QString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bu|u", &sipSelf, sipType_QString, &sipCpp, &a0, &a1))
        {
            QString *sipRes;

            sipRes = new QString(sipCpp->mid(a0,a1));

            return sipConvertFromNewType(sipRes,sipType_QString,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QString, sipName_mid, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QString_leftJustify(PyObject *, PyObject *);}
static PyObject *meth_QString_leftJustify(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        uint a0;
        QChar a1def = ' ';
        QChar * a1 = &a1def;
        bool a2 = 0;
        QString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bu|J9b", &sipSelf, sipType_QString, &sipCpp, &a0, sipType_QChar, &a1, &a2))
        {
            QString *sipRes;

            sipRes = new QString(sipCpp->leftJustify(a0,*a1,a2));

            return sipConvertFromNewType(sipRes,sipType_QString,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QString, sipName_leftJustify, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QString_rightJustify(PyObject *, PyObject *);}
static PyObject *meth_QString_rightJustify(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        uint a0;
        QChar a1def = ' ';
        QChar * a1 = &a1def;
        bool a2 = 0;
        QString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bu|J9b", &sipSelf, sipType_QString, &sipCpp, &a0, sipType_QChar, &a1, &a2))
        {
            QString *sipRes;

            sipRes = new QString(sipCpp->rightJustify(a0,*a1,a2));

            return sipConvertFromNewType(sipRes,sipType_QString,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QString, sipName_rightJustify, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QString_lower(PyObject *, PyObject *);}
static PyObject *meth_QString_lower(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QString, &sipCpp))
        {
            QString *sipRes;

            sipRes = new QString(sipCpp->lower());

            return sipConvertFromNewType(sipRes,sipType_QString,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QString, sipName_lower, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QString_upper(PyObject *, PyObject *);}
static PyObject *meth_QString_upper(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QString, &sipCpp))
        {
            QString *sipRes;

            sipRes = new QString(sipCpp->upper());

            return sipConvertFromNewType(sipRes,sipType_QString,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QString, sipName_upper, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QString_stripWhiteSpace(PyObject *, PyObject *);}
static PyObject *meth_QString_stripWhiteSpace(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QString, &sipCpp))
        {
            QString *sipRes;

            sipRes = new QString(sipCpp->stripWhiteSpace());

            return sipConvertFromNewType(sipRes,sipType_QString,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QString, sipName_stripWhiteSpace, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QString_simplifyWhiteSpace(PyObject *, PyObject *);}
static PyObject *meth_QString_simplifyWhiteSpace(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QString, &sipCpp))
        {
            QString *sipRes;

            sipRes = new QString(sipCpp->simplifyWhiteSpace());

            return sipConvertFromNewType(sipRes,sipType_QString,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QString, sipName_simplifyWhiteSpace, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QString_insert(PyObject *, PyObject *);}
static PyObject *meth_QString_insert(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        uint a0;
        const QString * a1;
        int a1State = 0;
        QString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BuJ1", &sipSelf, sipType_QString, &sipCpp, &a0, sipType_QString, &a1, &a1State))
        {
            QString *sipRes;

            sipRes = &sipCpp->insert(a0,*a1);
            sipReleaseType(const_cast<QString *>(a1),sipType_QString,a1State);

            return sipConvertFromType(sipRes,sipType_QString,NULL);
        }
    }

    {
        uint a0;
        const QByteArray * a1;
        int a1State = 0;
        QString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BuJ1", &sipSelf, sipType_QString, &sipCpp, &a0, sipType_QByteArray, &a1, &a1State))
        {
            QString *sipRes;

            sipRes = &sipCpp->insert(a0,*a1);
            sipReleaseType(const_cast<QByteArray *>(a1),sipType_QByteArray,a1State);

            return sipConvertFromType(sipRes,sipType_QString,NULL);
        }
    }

    {
        uint a0;
        QChar * a1;
        uint a2;
        QString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BuJ8u", &sipSelf, sipType_QString, &sipCpp, &a0, sipType_QChar, &a1, &a2))
        {
            QString *sipRes;

            sipRes = &sipCpp->insert(a0,a1,a2);

            return sipConvertFromType(sipRes,sipType_QString,NULL);
        }
    }

    {
        uint a0;
        QChar * a1;
        QString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BuJ9", &sipSelf, sipType_QString, &sipCpp, &a0, sipType_QChar, &a1))
        {
            QString *sipRes;

            sipRes = &sipCpp->insert(a0,*a1);

            return sipConvertFromType(sipRes,sipType_QString,NULL);
        }
    }

    {
        uint a0;
        char a1;
        QString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Buc", &sipSelf, sipType_QString, &sipCpp, &a0, &a1))
        {
            QString *sipRes;

            sipRes = &sipCpp->insert(a0,a1);

            return sipConvertFromType(sipRes,sipType_QString,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QString, sipName_insert, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QString_append(PyObject *, PyObject *);}
static PyObject *meth_QString_append(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        char a0;
        QString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bc", &sipSelf, sipType_QString, &sipCpp, &a0))
        {
            QString *sipRes;

            sipRes = &sipCpp->append(a0);

            return sipConvertFromType(sipRes,sipType_QString,NULL);
        }
    }

    {
        QChar * a0;
        QString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ9", &sipSelf, sipType_QString, &sipCpp, sipType_QChar, &a0))
        {
            QString *sipRes;

            sipRes = &sipCpp->append(*a0);

            return sipConvertFromType(sipRes,sipType_QString,NULL);
        }
    }

    {
        const QString * a0;
        int a0State = 0;
        QString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ1", &sipSelf, sipType_QString, &sipCpp, sipType_QString, &a0, &a0State))
        {
            QString *sipRes;

            sipRes = &sipCpp->append(*a0);
            sipReleaseType(const_cast<QString *>(a0),sipType_QString,a0State);

            return sipConvertFromType(sipRes,sipType_QString,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QString, sipName_append, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QString_prepend(PyObject *, PyObject *);}
static PyObject *meth_QString_prepend(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        char a0;
        QString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bc", &sipSelf, sipType_QString, &sipCpp, &a0))
        {
            QString *sipRes;

            sipRes = &sipCpp->prepend(a0);

            return sipConvertFromType(sipRes,sipType_QString,NULL);
        }
    }

    {
        QChar * a0;
        QString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ9", &sipSelf, sipType_QString, &sipCpp, sipType_QChar, &a0))
        {
            QString *sipRes;

            sipRes = &sipCpp->prepend(*a0);

            return sipConvertFromType(sipRes,sipType_QString,NULL);
        }
    }

    {
        const QString * a0;
        int a0State = 0;
        QString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ1", &sipSelf, sipType_QString, &sipCpp, sipType_QString, &a0, &a0State))
        {
            QString *sipRes;

            sipRes = &sipCpp->prepend(*a0);
            sipReleaseType(const_cast<QString *>(a0),sipType_QString,a0State);

            return sipConvertFromType(sipRes,sipType_QString,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QString, sipName_prepend, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QString_remove(PyObject *, PyObject *);}
static PyObject *meth_QString_remove(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        uint a0;
        uint a1;
        QString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Buu", &sipSelf, sipType_QString, &sipCpp, &a0, &a1))
        {
            QString *sipRes;

            sipRes = &sipCpp->remove(a0,a1);

            return sipConvertFromType(sipRes,sipType_QString,NULL);
        }
    }

    {
        const QString * a0;
        int a0State = 0;
        QString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ1", &sipSelf, sipType_QString, &sipCpp, sipType_QString, &a0, &a0State))
        {
            QString *sipRes;

            sipRes = &sipCpp->remove(*a0);
            sipReleaseType(const_cast<QString *>(a0),sipType_QString,a0State);

            return sipConvertFromType(sipRes,sipType_QString,NULL);
        }
    }

    {
        const QString * a0;
        int a0State = 0;
        bool a1;
        QString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ1b", &sipSelf, sipType_QString, &sipCpp, sipType_QString, &a0, &a0State, &a1))
        {
            QString *sipRes;

            sipRes = &sipCpp->remove(*a0,a1);
            sipReleaseType(const_cast<QString *>(a0),sipType_QString,a0State);

            return sipConvertFromType(sipRes,sipType_QString,NULL);
        }
    }

    {
        QChar * a0;
        QString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ9", &sipSelf, sipType_QString, &sipCpp, sipType_QChar, &a0))
        {
            QString *sipRes;

            sipRes = &sipCpp->remove(*a0);

            return sipConvertFromType(sipRes,sipType_QString,NULL);
        }
    }

    {
        char a0;
        QString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bc", &sipSelf, sipType_QString, &sipCpp, &a0))
        {
            QString *sipRes;

            sipRes = &sipCpp->remove(a0);

            return sipConvertFromType(sipRes,sipType_QString,NULL);
        }
    }

    {
        const QRegExp * a0;
        QString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ9", &sipSelf, sipType_QString, &sipCpp, sipType_QRegExp, &a0))
        {
            QString *sipRes;

            sipRes = &sipCpp->remove(*a0);

            return sipConvertFromType(sipRes,sipType_QString,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QString, sipName_remove, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QString_replace(PyObject *, PyObject *);}
static PyObject *meth_QString_replace(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        uint a0;
        uint a1;
        const QString * a2;
        int a2State = 0;
        QString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BuuJ1", &sipSelf, sipType_QString, &sipCpp, &a0, &a1, sipType_QString, &a2, &a2State))
        {
            QString *sipRes;

            sipRes = &sipCpp->replace(a0,a1,*a2);
            sipReleaseType(const_cast<QString *>(a2),sipType_QString,a2State);

            return sipConvertFromType(sipRes,sipType_QString,NULL);
        }
    }

    {
        uint a0;
        uint a1;
        const QChar * a2;
        uint a3;
        QString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BuuJ8u", &sipSelf, sipType_QString, &sipCpp, &a0, &a1, sipType_QChar, &a2, &a3))
        {
            QString *sipRes;

            sipRes = &sipCpp->replace(a0,a1,a2,a3);

            return sipConvertFromType(sipRes,sipType_QString,NULL);
        }
    }

    {
        uint a0;
        uint a1;
        QChar * a2;
        QString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BuuJ9", &sipSelf, sipType_QString, &sipCpp, &a0, &a1, sipType_QChar, &a2))
        {
            QString *sipRes;

            sipRes = &sipCpp->replace(a0,a1,*a2);

            return sipConvertFromType(sipRes,sipType_QString,NULL);
        }
    }

    {
        uint a0;
        uint a1;
        char a2;
        QString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Buuc", &sipSelf, sipType_QString, &sipCpp, &a0, &a1, &a2))
        {
            QString *sipRes;

            sipRes = &sipCpp->replace(a0,a1,a2);

            return sipConvertFromType(sipRes,sipType_QString,NULL);
        }
    }

    {
        QChar * a0;
        const QString * a1;
        int a1State = 0;
        QString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ9J1", &sipSelf, sipType_QString, &sipCpp, sipType_QChar, &a0, sipType_QString, &a1, &a1State))
        {
            QString *sipRes;

            sipRes = &sipCpp->replace(*a0,*a1);
            sipReleaseType(const_cast<QString *>(a1),sipType_QString,a1State);

            return sipConvertFromType(sipRes,sipType_QString,NULL);
        }
    }

    {
        QChar * a0;
        const QString * a1;
        int a1State = 0;
        bool a2;
        QString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ9J1b", &sipSelf, sipType_QString, &sipCpp, sipType_QChar, &a0, sipType_QString, &a1, &a1State, &a2))
        {
            QString *sipRes;

            sipRes = &sipCpp->replace(*a0,*a1,a2);
            sipReleaseType(const_cast<QString *>(a1),sipType_QString,a1State);

            return sipConvertFromType(sipRes,sipType_QString,NULL);
        }
    }

    {
        char a0;
        const QString * a1;
        int a1State = 0;
        QString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BcJ1", &sipSelf, sipType_QString, &sipCpp, &a0, sipType_QString, &a1, &a1State))
        {
            QString *sipRes;

            sipRes = &sipCpp->replace(a0,*a1);
            sipReleaseType(const_cast<QString *>(a1),sipType_QString,a1State);

            return sipConvertFromType(sipRes,sipType_QString,NULL);
        }
    }

    {
        char a0;
        const QString * a1;
        int a1State = 0;
        bool a2;
        QString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BcJ1b", &sipSelf, sipType_QString, &sipCpp, &a0, sipType_QString, &a1, &a1State, &a2))
        {
            QString *sipRes;

            sipRes = &sipCpp->replace(a0,*a1,a2);
            sipReleaseType(const_cast<QString *>(a1),sipType_QString,a1State);

            return sipConvertFromType(sipRes,sipType_QString,NULL);
        }
    }

    {
        const QString * a0;
        int a0State = 0;
        const QString * a1;
        int a1State = 0;
        QString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ1J1", &sipSelf, sipType_QString, &sipCpp, sipType_QString, &a0, &a0State, sipType_QString, &a1, &a1State))
        {
            QString *sipRes;

            sipRes = &sipCpp->replace(*a0,*a1);
            sipReleaseType(const_cast<QString *>(a0),sipType_QString,a0State);
            sipReleaseType(const_cast<QString *>(a1),sipType_QString,a1State);

            return sipConvertFromType(sipRes,sipType_QString,NULL);
        }
    }

    {
        const QString * a0;
        int a0State = 0;
        const QString * a1;
        int a1State = 0;
        bool a2;
        QString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ1J1b", &sipSelf, sipType_QString, &sipCpp, sipType_QString, &a0, &a0State, sipType_QString, &a1, &a1State, &a2))
        {
            QString *sipRes;

            sipRes = &sipCpp->replace(*a0,*a1,a2);
            sipReleaseType(const_cast<QString *>(a0),sipType_QString,a0State);
            sipReleaseType(const_cast<QString *>(a1),sipType_QString,a1State);

            return sipConvertFromType(sipRes,sipType_QString,NULL);
        }
    }

    {
        const QRegExp * a0;
        const QString * a1;
        int a1State = 0;
        QString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ9J1", &sipSelf, sipType_QString, &sipCpp, sipType_QRegExp, &a0, sipType_QString, &a1, &a1State))
        {
            QString *sipRes;

            sipRes = &sipCpp->replace(*a0,*a1);
            sipReleaseType(const_cast<QString *>(a1),sipType_QString,a1State);

            return sipConvertFromType(sipRes,sipType_QString,NULL);
        }
    }

    {
        QChar * a0;
        QChar * a1;
        QString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ9J9", &sipSelf, sipType_QString, &sipCpp, sipType_QChar, &a0, sipType_QChar, &a1))
        {
            QString *sipRes;

            sipRes = &sipCpp->replace(*a0,*a1);

            return sipConvertFromType(sipRes,sipType_QString,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QString, sipName_replace, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QString_toShort(PyObject *, PyObject *);}
static PyObject *meth_QString_toShort(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        bool a0;
        int a1 = 10;
        QString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B|i", &sipSelf, sipType_QString, &sipCpp, &a1))
        {
            short sipRes;

            sipRes = sipCpp->toShort(&a0,a1);

            return sipBuildResult(0,"(hb)",sipRes,a0);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QString, sipName_toShort, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QString_toUShort(PyObject *, PyObject *);}
static PyObject *meth_QString_toUShort(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        bool a0;
        int a1 = 10;
        QString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B|i", &sipSelf, sipType_QString, &sipCpp, &a1))
        {
            ushort sipRes;

            sipRes = sipCpp->toUShort(&a0,a1);

            return sipBuildResult(0,"(tb)",sipRes,a0);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QString, sipName_toUShort, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QString_toInt(PyObject *, PyObject *);}
static PyObject *meth_QString_toInt(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        bool a0;
        int a1 = 10;
        QString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B|i", &sipSelf, sipType_QString, &sipCpp, &a1))
        {
            int sipRes;

            sipRes = sipCpp->toInt(&a0,a1);

            return sipBuildResult(0,"(ib)",sipRes,a0);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QString, sipName_toInt, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QString_toUInt(PyObject *, PyObject *);}
static PyObject *meth_QString_toUInt(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        bool a0;
        int a1 = 10;
        QString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B|i", &sipSelf, sipType_QString, &sipCpp, &a1))
        {
            uint sipRes;

            sipRes = sipCpp->toUInt(&a0,a1);

            return sipBuildResult(0,"(ub)",sipRes,a0);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QString, sipName_toUInt, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QString_toLong(PyObject *, PyObject *);}
static PyObject *meth_QString_toLong(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        bool a0;
        int a1 = 10;
        QString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B|i", &sipSelf, sipType_QString, &sipCpp, &a1))
        {
            long sipRes;

            sipRes = sipCpp->toLong(&a0,a1);

            return sipBuildResult(0,"(lb)",sipRes,a0);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QString, sipName_toLong, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QString_toULong(PyObject *, PyObject *);}
static PyObject *meth_QString_toULong(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        bool a0;
        int a1 = 10;
        QString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B|i", &sipSelf, sipType_QString, &sipCpp, &a1))
        {
            ulong sipRes;

            sipRes = sipCpp->toULong(&a0,a1);

            return sipBuildResult(0,"(mb)",sipRes,a0);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QString, sipName_toULong, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QString_toFloat(PyObject *, PyObject *);}
static PyObject *meth_QString_toFloat(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        bool a0;
        QString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QString, &sipCpp))
        {
            float sipRes;

            sipRes = sipCpp->toFloat(&a0);

            return sipBuildResult(0,"(fb)",sipRes,a0);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QString, sipName_toFloat, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QString_toDouble(PyObject *, PyObject *);}
static PyObject *meth_QString_toDouble(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        bool a0;
        QString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QString, &sipCpp))
        {
            double sipRes;

            sipRes = sipCpp->toDouble(&a0);

            return sipBuildResult(0,"(db)",sipRes,a0);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QString, sipName_toDouble, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QString_setNum(PyObject *, PyObject *);}
static PyObject *meth_QString_setNum(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        int a0;
        int a1 = 10;
        QString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BXi|i", &sipSelf, sipType_QString, &sipCpp, &a0, &a1))
        {
            QString *sipRes;

            sipRes = &sipCpp->setNum(a0,a1);

            return sipConvertFromType(sipRes,sipType_QString,NULL);
        }
    }

    {
        double a0;
        char a1 = 'g';
        int a2 = 6;
        QString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BXd|ci", &sipSelf, sipType_QString, &sipCpp, &a0, &a1, &a2))
        {
            QString *sipRes;

            sipRes = &sipCpp->setNum(a0,a1,a2);

            return sipConvertFromType(sipRes,sipType_QString,NULL);
        }
    }

    {
        long a0;
        int a1 = 10;
        QString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bl|i", &sipSelf, sipType_QString, &sipCpp, &a0, &a1))
        {
            QString *sipRes;

            sipRes = &sipCpp->setNum(a0,a1);

            return sipConvertFromType(sipRes,sipType_QString,NULL);
        }
    }

    {
        ulong a0;
        int a1 = 10;
        QString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bm|i", &sipSelf, sipType_QString, &sipCpp, &a0, &a1))
        {
            QString *sipRes;

            sipRes = &sipCpp->setNum(a0,a1);

            return sipConvertFromType(sipRes,sipType_QString,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QString, sipName_setNum, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QString_number(PyObject *, PyObject *);}
static PyObject *meth_QString_number(PyObject *, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        int a0;
        int a1 = 10;

        if (sipParseArgs(&sipParseErr, sipArgs, "Xi|i", &a0, &a1))
        {
            QString *sipRes;

            sipRes = new QString(QString::number(a0,a1));

            return sipConvertFromNewType(sipRes,sipType_QString,NULL);
        }
    }

    {
        double a0;
        char a1 = 'g';
        int a2 = 6;

        if (sipParseArgs(&sipParseErr, sipArgs, "Xd|ci", &a0, &a1, &a2))
        {
            QString *sipRes;

            sipRes = new QString(QString::number(a0,a1,a2));

            return sipConvertFromNewType(sipRes,sipType_QString,NULL);
        }
    }

    {
        long a0;
        int a1 = 10;

        if (sipParseArgs(&sipParseErr, sipArgs, "l|i", &a0, &a1))
        {
            QString *sipRes;

            sipRes = new QString(QString::number(a0,a1));

            return sipConvertFromNewType(sipRes,sipType_QString,NULL);
        }
    }

    {
        ulong a0;
        int a1 = 10;

        if (sipParseArgs(&sipParseErr, sipArgs, "m|i", &a0, &a1))
        {
            QString *sipRes;

            sipRes = new QString(QString::number(a0,a1));

            return sipConvertFromNewType(sipRes,sipType_QString,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QString, sipName_number, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QString_setExpand(PyObject *, PyObject *);}
static PyObject *meth_QString_setExpand(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        uint a0;
        QChar * a1;
        QString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BuJ9", &sipSelf, sipType_QString, &sipCpp, &a0, sipType_QChar, &a1))
        {
            sipCpp->setExpand(a0,*a1);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QString, sipName_setExpand, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QString_at(PyObject *, PyObject *);}
static PyObject *meth_QString_at(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        uint a0;
        QString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bu", &sipSelf, sipType_QString, &sipCpp, &a0))
        {
            QChar *sipRes;

            sipRes = new QChar(sipCpp->at(a0));

            return sipConvertFromNewType(sipRes,sipType_QChar,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QString, sipName_at, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QString_ascii(PyObject *, PyObject *);}
static PyObject *meth_QString_ascii(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QString, &sipCpp))
        {
            const char *sipRes;

            sipRes = sipCpp->ascii();

            if (sipRes == NULL)
            {
                Py_INCREF(Py_None);
                return Py_None;
            }

            return SIPBytes_FromString(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QString, sipName_ascii, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QString_fromAscii(PyObject *, PyObject *);}
static PyObject *meth_QString_fromAscii(PyObject *, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const char * a0;
        int a1 = -1;

        if (sipParseArgs(&sipParseErr, sipArgs, "s|i", &a0, &a1))
        {
            QString *sipRes;

            sipRes = new QString(QString::fromAscii(a0,a1));

            return sipConvertFromNewType(sipRes,sipType_QString,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QString, sipName_fromAscii, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QString_latin1(PyObject *, PyObject *);}
static PyObject *meth_QString_latin1(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QString, &sipCpp))
        {
            const char *sipRes;

            sipRes = sipCpp->latin1();

            if (sipRes == NULL)
            {
                Py_INCREF(Py_None);
                return Py_None;
            }

            return SIPBytes_FromString(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QString, sipName_latin1, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QString_fromLatin1(PyObject *, PyObject *);}
static PyObject *meth_QString_fromLatin1(PyObject *, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const char * a0;
        int a1 = -1;

        if (sipParseArgs(&sipParseErr, sipArgs, "s|i", &a0, &a1))
        {
            QString *sipRes;

            sipRes = new QString(QString::fromLatin1(a0,a1));

            return sipConvertFromNewType(sipRes,sipType_QString,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QString, sipName_fromLatin1, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QString_utf8(PyObject *, PyObject *);}
static PyObject *meth_QString_utf8(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QString, &sipCpp))
        {
            QCString *sipRes;

            sipRes = new QCString(sipCpp->utf8());

            return sipConvertFromNewType(sipRes,sipType_QCString,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QString, sipName_utf8, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QString_fromUtf8(PyObject *, PyObject *);}
static PyObject *meth_QString_fromUtf8(PyObject *, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const char * a0;
        int a1 = -1;

        if (sipParseArgs(&sipParseErr, sipArgs, "s|i", &a0, &a1))
        {
            QString *sipRes;

            sipRes = new QString(QString::fromUtf8(a0,a1));

            return sipConvertFromNewType(sipRes,sipType_QString,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QString, sipName_fromUtf8, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QString_local8Bit(PyObject *, PyObject *);}
static PyObject *meth_QString_local8Bit(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QString, &sipCpp))
        {
            QCString *sipRes;

            sipRes = new QCString(sipCpp->local8Bit());

            return sipConvertFromNewType(sipRes,sipType_QCString,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QString, sipName_local8Bit, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QString_fromLocal8Bit(PyObject *, PyObject *);}
static PyObject *meth_QString_fromLocal8Bit(PyObject *, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const char * a0;
        int a1 = -1;

        if (sipParseArgs(&sipParseErr, sipArgs, "s|i", &a0, &a1))
        {
            QString *sipRes;

            sipRes = new QString(QString::fromLocal8Bit(a0,a1));

            return sipConvertFromNewType(sipRes,sipType_QString,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QString, sipName_fromLocal8Bit, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QString_setAscii(PyObject *, PyObject *);}
static PyObject *meth_QString_setAscii(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const char * a0;
        int a1 = -1;
        QString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bs|i", &sipSelf, sipType_QString, &sipCpp, &a0, &a1))
        {
            QString *sipRes;

            sipRes = &sipCpp->setAscii(a0,a1);

            return sipConvertFromType(sipRes,sipType_QString,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QString, sipName_setAscii, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QString_setLatin1(PyObject *, PyObject *);}
static PyObject *meth_QString_setLatin1(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const char * a0;
        int a1 = -1;
        QString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bs|i", &sipSelf, sipType_QString, &sipCpp, &a0, &a1))
        {
            QString *sipRes;

            sipRes = &sipCpp->setLatin1(a0,a1);

            return sipConvertFromType(sipRes,sipType_QString,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QString, sipName_setLatin1, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QString_compare(PyObject *, PyObject *);}
static PyObject *meth_QString_compare(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const QString * a0;
        int a0State = 0;
        QString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ1", &sipSelf, sipType_QString, &sipCpp, sipType_QString, &a0, &a0State))
        {
            int sipRes;

            sipRes = sipCpp->compare(*a0);
            sipReleaseType(const_cast<QString *>(a0),sipType_QString,a0State);

            return SIPLong_FromLong(sipRes);
        }
    }

    {
        const QString * a0;
        int a0State = 0;
        const QString * a1;
        int a1State = 0;

        if (sipParseArgs(&sipParseErr, sipArgs, "J1J1", sipType_QString, &a0, &a0State, sipType_QString, &a1, &a1State))
        {
            int sipRes;

            sipRes = QString::compare(*a0,*a1);
            sipReleaseType(const_cast<QString *>(a0),sipType_QString,a0State);
            sipReleaseType(const_cast<QString *>(a1),sipType_QString,a1State);

            return SIPLong_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QString, sipName_compare, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QString_localeAwareCompare(PyObject *, PyObject *);}
static PyObject *meth_QString_localeAwareCompare(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const QString * a0;
        int a0State = 0;
        QString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ1", &sipSelf, sipType_QString, &sipCpp, sipType_QString, &a0, &a0State))
        {
            int sipRes;

            sipRes = sipCpp->localeAwareCompare(*a0);
            sipReleaseType(const_cast<QString *>(a0),sipType_QString,a0State);

            return SIPLong_FromLong(sipRes);
        }
    }

    {
        const QString * a0;
        int a0State = 0;
        const QString * a1;
        int a1State = 0;

        if (sipParseArgs(&sipParseErr, sipArgs, "J1J1", sipType_QString, &a0, &a0State, sipType_QString, &a1, &a1State))
        {
            int sipRes;

            sipRes = QString::localeAwareCompare(*a0,*a1);
            sipReleaseType(const_cast<QString *>(a0),sipType_QString,a0State);
            sipReleaseType(const_cast<QString *>(a1),sipType_QString,a1State);

            return SIPLong_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QString, sipName_localeAwareCompare, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QString_compose(PyObject *, PyObject *);}
static PyObject *meth_QString_compose(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QString, &sipCpp))
        {
            sipCpp->compose();

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QString, sipName_compose, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QString_startsWith(PyObject *, PyObject *);}
static PyObject *meth_QString_startsWith(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const QString * a0;
        int a0State = 0;
        QString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ1", &sipSelf, sipType_QString, &sipCpp, sipType_QString, &a0, &a0State))
        {
            bool sipRes;

            sipRes = sipCpp->startsWith(*a0);
            sipReleaseType(const_cast<QString *>(a0),sipType_QString,a0State);

            return PyBool_FromLong(sipRes);
        }
    }

    {
        const QString * a0;
        int a0State = 0;
        bool a1;
        QString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ1b", &sipSelf, sipType_QString, &sipCpp, sipType_QString, &a0, &a0State, &a1))
        {
            bool sipRes;

            sipRes = sipCpp->startsWith(*a0,a1);
            sipReleaseType(const_cast<QString *>(a0),sipType_QString,a0State);

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QString, sipName_startsWith, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QString_endsWith(PyObject *, PyObject *);}
static PyObject *meth_QString_endsWith(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const QString * a0;
        int a0State = 0;
        QString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ1", &sipSelf, sipType_QString, &sipCpp, sipType_QString, &a0, &a0State))
        {
            bool sipRes;

            sipRes = sipCpp->endsWith(*a0);
            sipReleaseType(const_cast<QString *>(a0),sipType_QString,a0State);

            return PyBool_FromLong(sipRes);
        }
    }

    {
        const QString * a0;
        int a0State = 0;
        bool a1;
        QString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ1b", &sipSelf, sipType_QString, &sipCpp, sipType_QString, &a0, &a0State, &a1))
        {
            bool sipRes;

            sipRes = sipCpp->endsWith(*a0,a1);
            sipReleaseType(const_cast<QString *>(a0),sipType_QString,a0State);

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QString, sipName_endsWith, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QString_setLength(PyObject *, PyObject *);}
static PyObject *meth_QString_setLength(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        uint a0;
        QString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bu", &sipSelf, sipType_QString, &sipCpp, &a0))
        {
            sipCpp->setLength(a0);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QString, sipName_setLength, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QString_capacity(PyObject *, PyObject *);}
static PyObject *meth_QString_capacity(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QString, &sipCpp))
        {
            uint sipRes;

            sipRes = sipCpp->capacity();

            return PyLong_FromUnsignedLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QString, sipName_capacity, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QString_reserve(PyObject *, PyObject *);}
static PyObject *meth_QString_reserve(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        uint a0;
        QString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bu", &sipSelf, sipType_QString, &sipCpp, &a0))
        {
            sipCpp->reserve(a0);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QString, sipName_reserve, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QString_squeeze(PyObject *, PyObject *);}
static PyObject *meth_QString_squeeze(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QString, &sipCpp))
        {
            sipCpp->squeeze();

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QString, sipName_squeeze, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QString_simpleText(PyObject *, PyObject *);}
static PyObject *meth_QString_simpleText(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QString, &sipCpp))
        {
            bool sipRes;

            sipRes = sipCpp->simpleText();

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QString, sipName_simpleText, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QString_isRightToLeft(PyObject *, PyObject *);}
static PyObject *meth_QString_isRightToLeft(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QString, &sipCpp))
        {
            bool sipRes;

            sipRes = sipCpp->isRightToLeft();

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QString, sipName_isRightToLeft, NULL);

    return NULL;
}


extern "C" {static PyObject *slot_QString___eq__(PyObject *sipSelf,PyObject *sipArg);}
static PyObject *slot_QString___eq__(PyObject *sipSelf,PyObject *sipArg)
{
    QString *sipCpp = reinterpret_cast<QString *>(sipGetCppPtr((sipSimpleWrapper *)sipSelf,sipType_QString));

    if (!sipCpp)
        return 0;

    PyObject *sipParseErr = NULL;

    {
        const QString * a0;
        int a0State = 0;

        if (sipParseArgs(&sipParseErr, sipArg, "1J1", sipType_QString, &a0, &a0State))
        {
            bool sipRes;

            sipRes = operator==((*sipCpp), *a0);
            sipReleaseType(const_cast<QString *>(a0),sipType_QString,a0State);

            return PyBool_FromLong(sipRes);
        }
    }

    Py_XDECREF(sipParseErr);

    if (sipParseErr == Py_None)
        return NULL;

    return sipPySlotExtend(&sipModuleAPI_qt,eq_slot,sipType_QString,sipSelf,sipArg);
}


extern "C" {static PyObject *slot_QString___ne__(PyObject *sipSelf,PyObject *sipArg);}
static PyObject *slot_QString___ne__(PyObject *sipSelf,PyObject *sipArg)
{
    QString *sipCpp = reinterpret_cast<QString *>(sipGetCppPtr((sipSimpleWrapper *)sipSelf,sipType_QString));

    if (!sipCpp)
        return 0;

    PyObject *sipParseErr = NULL;

    {
        const QString * a0;
        int a0State = 0;

        if (sipParseArgs(&sipParseErr, sipArg, "1J1", sipType_QString, &a0, &a0State))
        {
            bool sipRes;

            sipRes = operator!=((*sipCpp), *a0);
            sipReleaseType(const_cast<QString *>(a0),sipType_QString,a0State);

            return PyBool_FromLong(sipRes);
        }
    }

    Py_XDECREF(sipParseErr);

    if (sipParseErr == Py_None)
        return NULL;

    return sipPySlotExtend(&sipModuleAPI_qt,ne_slot,sipType_QString,sipSelf,sipArg);
}


extern "C" {static PyObject *slot_QString___le__(PyObject *sipSelf,PyObject *sipArg);}
static PyObject *slot_QString___le__(PyObject *sipSelf,PyObject *sipArg)
{
    QString *sipCpp = reinterpret_cast<QString *>(sipGetCppPtr((sipSimpleWrapper *)sipSelf,sipType_QString));

    if (!sipCpp)
        return 0;

    PyObject *sipParseErr = NULL;

    {
        const QString * a0;
        int a0State = 0;

        if (sipParseArgs(&sipParseErr, sipArg, "1J1", sipType_QString, &a0, &a0State))
        {
            bool sipRes;

            sipRes = operator<=((*sipCpp), *a0);
            sipReleaseType(const_cast<QString *>(a0),sipType_QString,a0State);

            return PyBool_FromLong(sipRes);
        }
    }

    Py_XDECREF(sipParseErr);

    if (sipParseErr == Py_None)
        return NULL;

    return sipPySlotExtend(&sipModuleAPI_qt,le_slot,sipType_QString,sipSelf,sipArg);
}


extern "C" {static PyObject *slot_QString___ge__(PyObject *sipSelf,PyObject *sipArg);}
static PyObject *slot_QString___ge__(PyObject *sipSelf,PyObject *sipArg)
{
    QString *sipCpp = reinterpret_cast<QString *>(sipGetCppPtr((sipSimpleWrapper *)sipSelf,sipType_QString));

    if (!sipCpp)
        return 0;

    PyObject *sipParseErr = NULL;

    {
        const QString * a0;
        int a0State = 0;

        if (sipParseArgs(&sipParseErr, sipArg, "1J1", sipType_QString, &a0, &a0State))
        {
            bool sipRes;

            sipRes = operator>=((*sipCpp), *a0);
            sipReleaseType(const_cast<QString *>(a0),sipType_QString,a0State);

            return PyBool_FromLong(sipRes);
        }
    }

    Py_XDECREF(sipParseErr);

    if (sipParseErr == Py_None)
        return NULL;

    return sipPySlotExtend(&sipModuleAPI_qt,ge_slot,sipType_QString,sipSelf,sipArg);
}


extern "C" {static PyObject *slot_QString___lt__(PyObject *sipSelf,PyObject *sipArg);}
static PyObject *slot_QString___lt__(PyObject *sipSelf,PyObject *sipArg)
{
    QString *sipCpp = reinterpret_cast<QString *>(sipGetCppPtr((sipSimpleWrapper *)sipSelf,sipType_QString));

    if (!sipCpp)
        return 0;

    PyObject *sipParseErr = NULL;

    {
        const QString * a0;
        int a0State = 0;

        if (sipParseArgs(&sipParseErr, sipArg, "1J1", sipType_QString, &a0, &a0State))
        {
            bool sipRes;

            sipRes = operator<((*sipCpp), *a0);
            sipReleaseType(const_cast<QString *>(a0),sipType_QString,a0State);

            return PyBool_FromLong(sipRes);
        }
    }

    Py_XDECREF(sipParseErr);

    if (sipParseErr == Py_None)
        return NULL;

    return sipPySlotExtend(&sipModuleAPI_qt,lt_slot,sipType_QString,sipSelf,sipArg);
}


extern "C" {static PyObject *slot_QString___gt__(PyObject *sipSelf,PyObject *sipArg);}
static PyObject *slot_QString___gt__(PyObject *sipSelf,PyObject *sipArg)
{
    QString *sipCpp = reinterpret_cast<QString *>(sipGetCppPtr((sipSimpleWrapper *)sipSelf,sipType_QString));

    if (!sipCpp)
        return 0;

    PyObject *sipParseErr = NULL;

    {
        const QString * a0;
        int a0State = 0;

        if (sipParseArgs(&sipParseErr, sipArg, "1J1", sipType_QString, &a0, &a0State))
        {
            bool sipRes;

            sipRes = operator>((*sipCpp), *a0);
            sipReleaseType(const_cast<QString *>(a0),sipType_QString,a0State);

            return PyBool_FromLong(sipRes);
        }
    }

    Py_XDECREF(sipParseErr);

    if (sipParseErr == Py_None)
        return NULL;

    return sipPySlotExtend(&sipModuleAPI_qt,gt_slot,sipType_QString,sipSelf,sipArg);
}


extern "C" {static PyObject *slot_QString___str__(PyObject *sipSelf);}
static PyObject *slot_QString___str__(PyObject *sipSelf)
{
    QString *sipCpp = reinterpret_cast<QString *>(sipGetCppPtr((sipSimpleWrapper *)sipSelf,sipType_QString));

    if (!sipCpp)
        return 0;


    {
        {
            PyObject * sipRes = 0;

#line 805 "/usr/share/sip/qt/qstring.sip"
#if PY_VERSION_HEX >= 0x01060000
		sipRes = QStringToPyUnicode(sipCpp);
#else
		const char *s;

		Py_BEGIN_ALLOW_THREADS
		s = *sipCpp;
		Py_END_ALLOW_THREADS

		if (s == NULL)
			s = "";

		sipRes = PyString_FromString(s);
#endif
#line 2768 "sipqtQString.cc"

            return sipRes;
        }
    }
}


extern "C" {static int slot_QString___contains__(PyObject *sipSelf,PyObject *sipArg);}
static int slot_QString___contains__(PyObject *sipSelf,PyObject *sipArg)
{
    QString *sipCpp = reinterpret_cast<QString *>(sipGetCppPtr((sipSimpleWrapper *)sipSelf,sipType_QString));

    if (!sipCpp)
        return -1;

    PyObject *sipParseErr = NULL;

    {
        const QString * a0;
        int a0State = 0;

        if (sipParseArgs(&sipParseErr, sipArg, "1J1", sipType_QString, &a0, &a0State))
        {
            int sipRes = 0;

#line 790 "/usr/share/sip/qt/qstring.sip"
		sipRes = (sipCpp -> contains(*a0) > 0);
#line 2796 "sipqtQString.cc"
            sipReleaseType(const_cast<QString *>(a0),sipType_QString,a0State);

            return sipRes;
        }
    }

    Py_XDECREF(sipParseErr);

    if (sipParseErr == Py_None)
        return NULL;

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QString, sipName___contains__, NULL);

    return -1;
}


extern "C" {static int slot_QString___len__(PyObject *sipSelf);}
static int slot_QString___len__(PyObject *sipSelf)
{
    QString *sipCpp = reinterpret_cast<QString *>(sipGetCppPtr((sipSimpleWrapper *)sipSelf,sipType_QString));

    if (!sipCpp)
        return -1;


    {
        {
            int sipRes = 0;

#line 785 "/usr/share/sip/qt/qstring.sip"
		sipRes = sipCpp -> length();
#line 2830 "sipqtQString.cc"

            return sipRes;
        }
    }
}


extern "C" {static PyObject *slot_QString___getitem__(PyObject *sipSelf,PyObject *sipArg);}
static PyObject *slot_QString___getitem__(PyObject *sipSelf,PyObject *sipArg)
{
    QString *sipCpp = reinterpret_cast<QString *>(sipGetCppPtr((sipSimpleWrapper *)sipSelf,sipType_QString));

    if (!sipCpp)
        return 0;

    PyObject *sipParseErr = NULL;

    {
        int a0;

        if (sipParseArgs(&sipParseErr, sipArg, "1i", &a0))
        {
            QString *sipRes = 0;
            int sipIsErr = 0;

#line 749 "/usr/share/sip/qt/qstring.sip"
		int len;

		len = sipCpp -> length();

		if ((a0 = (int)sipConvertFromSequenceIndex(a0,len)) < 0)
			sipIsErr = 1;
		else
			sipRes = new QString(sipCpp -> at(a0));
#line 2865 "sipqtQString.cc"

            if (sipIsErr)
                return 0;

            return sipConvertFromNewType(sipRes,sipType_QString,NULL);
        }
    }

    {
        PyObject * a0;

        if (sipParseArgs(&sipParseErr, sipArg, "1T", &PySlice_Type, &a0))
        {
            QString *sipRes = 0;
            int sipIsErr = 0;

#line 761 "/usr/share/sip/qt/qstring.sip"
#if PY_VERSION_HEX >= 0x02050000
		Py_ssize_t len, start, stop, step, slicelength, i;
#else
		int len, start, stop, step, slicelength, i;
#endif

		len = sipCpp -> length();

		if (sipConvertFromSliceObject(a0,len,&start,&stop,&step,&slicelength) < 0)
			sipIsErr = 1;
		else
		{
			sipRes = new QString();

			for (i = 0; i < slicelength; ++i)
			{
				sipRes -> append(sipCpp -> at(start));
				start += step;
			}
		}
#line 2903 "sipqtQString.cc"

            if (sipIsErr)
                return 0;

            return sipConvertFromNewType(sipRes,sipType_QString,NULL);
        }
    }

    Py_XDECREF(sipParseErr);

    if (sipParseErr == Py_None)
        return NULL;

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QString, sipName___getitem__, NULL);

    return 0;
}


extern "C" {static PyObject *slot_QString___add__(PyObject *sipArg0,PyObject *sipArg1);}
static PyObject *slot_QString___add__(PyObject *sipArg0,PyObject *sipArg1)
{
    PyObject *sipParseErr = NULL;

    {
        QString * a0;
        int a0State = 0;
        const QString * a1;
        int a1State = 0;

        if (sipParsePair(&sipParseErr, sipArg0, sipArg1, "J1J1", sipType_QString, &a0, &a0State, sipType_QString, &a1, &a1State))
        {
            QString *sipRes;

            sipRes = new QString((*a0 + *a1));
            sipReleaseType(a0,sipType_QString,a0State);
            sipReleaseType(const_cast<QString *>(a1),sipType_QString,a1State);

            return sipConvertFromNewType(sipRes,sipType_QString,NULL);
        }
    }

    Py_XDECREF(sipParseErr);

    if (sipParseErr == Py_None)
        return NULL;

    return sipPySlotExtend(&sipModuleAPI_qt,add_slot,NULL,sipArg0,sipArg1);
}


extern "C" {static PyObject *slot_QString___imul__(PyObject *sipSelf,int a0);}
static PyObject *slot_QString___imul__(PyObject *sipSelf,int a0)
{
    QString *sipCpp = reinterpret_cast<QString *>(sipGetCppPtr((sipSimpleWrapper *)sipSelf,sipType_QString));

    if (!sipCpp)
        return 0;


    {
        {
#line 662 "/usr/share/sip/qt/qstring.sip"
		QString orig(*sipCpp);

		sipCpp -> truncate(0);

		while (a0-- > 0)
			*sipCpp += orig;
#line 2974 "sipqtQString.cc"

            Py_INCREF(sipSelf);
            return sipSelf;
        }
    }
}


extern "C" {static PyObject *slot_QString___mul__(PyObject *sipSelf,int a0);}
static PyObject *slot_QString___mul__(PyObject *sipSelf,int a0)
{
    QString *sipCpp = reinterpret_cast<QString *>(sipGetCppPtr((sipSimpleWrapper *)sipSelf,sipType_QString));

    if (!sipCpp)
        return 0;


    {
        {
            QString *sipRes = 0;

#line 654 "/usr/share/sip/qt/qstring.sip"
		sipRes = new QString();

		while (a0-- > 0)
			*sipRes += *sipCpp;
#line 3001 "sipqtQString.cc"

            return sipConvertFromNewType(sipRes,sipType_QString,NULL);
        }
    }
}


extern "C" {static PyObject *slot_QString___iadd__(PyObject *sipSelf,PyObject *sipArg);}
static PyObject *slot_QString___iadd__(PyObject *sipSelf,PyObject *sipArg)
{
    QString *sipCpp = reinterpret_cast<QString *>(sipGetCppPtr((sipSimpleWrapper *)sipSelf,sipType_QString));

    if (!sipCpp)
        return 0;

    PyObject *sipParseErr = NULL;

    {
        const QString * a0;
        int a0State = 0;

        if (sipParseArgs(&sipParseErr, sipArg, "1J1", sipType_QString, &a0, &a0State))
        {
            sipCpp->QString::operator+=(*a0);
            sipReleaseType(const_cast<QString *>(a0),sipType_QString,a0State);

            Py_INCREF(sipSelf);
            return sipSelf;
        }
    }

    {
        const QByteArray * a0;
        int a0State = 0;

        if (sipParseArgs(&sipParseErr, sipArg, "1J1", sipType_QByteArray, &a0, &a0State))
        {
            sipCpp->QString::operator+=(*a0);
            sipReleaseType(const_cast<QByteArray *>(a0),sipType_QByteArray,a0State);

            Py_INCREF(sipSelf);
            return sipSelf;
        }
    }

    {
        QChar * a0;

        if (sipParseArgs(&sipParseErr, sipArg, "1J9", sipType_QChar, &a0))
        {
            sipCpp->QString::operator+=(*a0);

            Py_INCREF(sipSelf);
            return sipSelf;
        }
    }

    /* Raise an exception if the argument couldn't be parsed. */
    sipBadOperatorArg(sipSelf,sipArg,iconcat_slot);

    return NULL;
}


/* Cast a pointer to a type somewhere in its superclass hierarchy. */
extern "C" {static void *cast_QString(void *, const sipTypeDef *);}
static void *cast_QString(void *ptr, const sipTypeDef *targetType)
{
    if (targetType == sipType_QString)
        return ptr;

    return NULL;
}


/* Call the instance's destructor. */
extern "C" {static void release_QString(void *, int);}
static void release_QString(void *sipCppV,int)
{
    delete reinterpret_cast<QString *>(sipCppV);
}


#if PY_MAJOR_VERSION < 3
extern "C" {static SIP_SSIZE_T getreadbuffer_QString(PyObject *, void *, SIP_SSIZE_T, void **);}
static SIP_SSIZE_T getreadbuffer_QString(PyObject *, void *sipCppV, SIP_SSIZE_T sipSegment, void **sipPtrPtr)
{
    QString *sipCpp = reinterpret_cast<QString *>(sipCppV);
    SIP_SSIZE_T sipRes;

#line 894 "/usr/share/sip/qt/qstring.sip"
	if (sipSegment != 0)
	{
		PyErr_SetString(PyExc_SystemError, "accessing non-existent QString segment");
		sipRes = -1;
	}
	else
	{
		*sipPtrPtr = (void *)sipCpp->ucs2();
		sipRes = sipCpp->length() * sizeof (ushort);
	}
#line 3103 "sipqtQString.cc"

    return sipRes;
}
#endif


#if PY_MAJOR_VERSION < 3
extern "C" {static SIP_SSIZE_T getsegcount_QString(PyObject *, void *, SIP_SSIZE_T *);}
static SIP_SSIZE_T getsegcount_QString(PyObject *, void *sipCppV, SIP_SSIZE_T *sipLenPtr)
{
    QString *sipCpp = reinterpret_cast<QString *>(sipCppV);
    SIP_SSIZE_T sipRes;

#line 907 "/usr/share/sip/qt/qstring.sip"
	if (sipLenPtr)
		*sipLenPtr = sipCpp->length() * sizeof (ushort);

	sipRes = 1;
#line 3122 "sipqtQString.cc"

    return sipRes;
}
#endif


#if PY_MAJOR_VERSION < 3
extern "C" {static SIP_SSIZE_T getcharbuffer_QString(PyObject *, void *, SIP_SSIZE_T, void **);}
static SIP_SSIZE_T getcharbuffer_QString(PyObject *sipSelf, void *sipCppV, SIP_SSIZE_T sipSegment, void **sipPtrPtr)
{
    QString *sipCpp = reinterpret_cast<QString *>(sipCppV);
    SIP_SSIZE_T sipRes;

#line 914 "/usr/share/sip/qt/qstring.sip"
	if (sipSegment != 0)
	{
		PyErr_SetString(PyExc_SystemError, "accessing non-existent QString segment");
		sipRes = -1;
	}
	else
	{
		static QTextCodec *codec = 0;
		static bool check_codec = TRUE;

		// For the first time only, try and find a Qt codec that
		// corresponds to the default Python codec.  If one wasn't
		// found then fall back to ASCII (which is actually the codec
		// returned by QTextCodec::codecForCStrings()).
		if (check_codec)
		{
			codec = QTextCodec::codecForName(PyUnicode_GetDefaultEncoding());
			check_codec = FALSE;
		}

		if (codec)
		{
			// A Python string is the most convenient method to
			// save the encoded version on the heap.
			PyObject *encobj = ((sipSimpleWrapper *)sipSelf)->user;
			QCString enc;

			Py_XDECREF(encobj);

			enc = codec->fromUnicode(*sipCpp);

			if ((encobj = PyString_FromString(enc.data())) != NULL)
    			{
				*sipPtrPtr = (void *)PyString_AS_STRING(encobj);
				sipRes = PyString_GET_SIZE(encobj);

				((sipSimpleWrapper *)sipSelf)->user = encobj;
			}
			else
				sipRes = -1;
		}
		else
		{
			const char *asc = sipCpp->ascii();

			*sipPtrPtr = (void *)asc;
			sipRes = qstrlen(asc);
		}
	}
#line 3186 "sipqtQString.cc"

    return sipRes;
}
#endif


extern "C" {static void assign_QString(void *, SIP_SSIZE_T, const void *);}
static void assign_QString(void *sipDst, SIP_SSIZE_T sipDstIdx, const void *sipSrc)
{
    reinterpret_cast<QString *>(sipDst)[sipDstIdx] = *reinterpret_cast<const QString *>(sipSrc);
}


extern "C" {static void *array_QString(SIP_SSIZE_T);}
static void *array_QString(SIP_SSIZE_T sipNrElem)
{
    return new QString[sipNrElem];
}


extern "C" {static void *copy_QString(const void *, SIP_SSIZE_T);}
static void *copy_QString(const void *sipSrc, SIP_SSIZE_T sipSrcIdx)
{
    return new QString(reinterpret_cast<const QString *>(sipSrc)[sipSrcIdx]);
}


extern "C" {static void dealloc_QString(sipSimpleWrapper *);}
static void dealloc_QString(sipSimpleWrapper *sipSelf)
{
    if (sipIsPyOwned(sipSelf))
    {
        release_QString(sipSelf->u.cppPtr,0);
    }
}


extern "C" {static void *init_QString(sipSimpleWrapper *, PyObject *, PyObject *, PyObject **, PyObject **, PyObject **);}
static void *init_QString(sipSimpleWrapper *, PyObject *sipArgs, PyObject *sipKwds, PyObject **sipUnused, PyObject **, PyObject **sipParseErr)
{
    QString *sipCpp = 0;

    {
        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, NULL, sipUnused, ""))
        {
            sipCpp = new QString();

            return sipCpp;
        }
    }

    {
        QChar * a0;

        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, NULL, sipUnused, "J9", sipType_QChar, &a0))
        {
            sipCpp = new QString(*a0);

            return sipCpp;
        }
    }

    {
        const QString * a0;
        int a0State = 0;

        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, NULL, sipUnused, "J1", sipType_QString, &a0, &a0State))
        {
            sipCpp = new QString(*a0);
            sipReleaseType(const_cast<QString *>(a0),sipType_QString,a0State);

            return sipCpp;
        }
    }

    {
        const QByteArray * a0;
        int a0State = 0;

        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, NULL, sipUnused, "J1", sipType_QByteArray, &a0, &a0State))
        {
            sipCpp = new QString(*a0);
            sipReleaseType(const_cast<QByteArray *>(a0),sipType_QByteArray,a0State);

            return sipCpp;
        }
    }

    {
        const QUrl * a0;

        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, NULL, sipUnused, "J9", sipType_QUrl, &a0))
        {
            sipCpp = new QString(*a0);

            return sipCpp;
        }
    }

    {
        const QKeySequence * a0;
        int a0State = 0;

        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, NULL, sipUnused, "J1", sipType_QKeySequence, &a0, &a0State))
        {
            sipCpp = new QString(*a0);
            sipReleaseType(const_cast<QKeySequence *>(a0),sipType_QKeySequence,a0State);

            return sipCpp;
        }
    }

    {
        const QUuid * a0;

        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, NULL, sipUnused, "J9", sipType_QUuid, &a0))
        {
            sipCpp = new QString(*a0);

            return sipCpp;
        }
    }

    return NULL;
}


extern "C" {static int convertTo_QString(PyObject *, void **, int *, PyObject *);}
static int convertTo_QString(PyObject *sipPy,void **sipCppPtrV,int *sipIsErr,PyObject *sipTransferObj)
{
    QString **sipCppPtr = reinterpret_cast<QString **>(sipCppPtrV);

#line 873 "/usr/share/sip/qt/qstring.sip"
	// Allow a Python string (or a unicode string) whenever a QString is
	// expected.

	if (sipIsErr == NULL)
		return (PyString_Check(sipPy) ||
#if PY_VERSION_HEX >= 0x01060000
			PyUnicode_Check(sipPy) ||
#endif
			sipCanConvertToInstance(sipPy,sipClass_QString,SIP_NO_CONVERTORS));

	*sipCppPtr = PyUnicodeStringToQString(sipPy);

	if (*sipCppPtr)
		return sipGetState(sipTransferObj);

	*sipCppPtr = reinterpret_cast<QString *>(sipConvertToInstance(sipPy,sipClass_QString,sipTransferObj,SIP_NO_CONVERTORS,0,sipIsErr));

	return 0;
#line 3338 "sipqtQString.cc"
}


/* Define this type's Python slots. */
static sipPySlotDef slots_QString[] = {
    {(void *)slot_QString___eq__, eq_slot},
    {(void *)slot_QString___ne__, ne_slot},
    {(void *)slot_QString___le__, le_slot},
    {(void *)slot_QString___ge__, ge_slot},
    {(void *)slot_QString___lt__, lt_slot},
    {(void *)slot_QString___gt__, gt_slot},
    {(void *)slot_QString___str__, str_slot},
    {(void *)slot_QString___contains__, contains_slot},
    {(void *)slot_QString___len__, len_slot},
    {(void *)slot_QString___getitem__, getitem_slot},
    {(void *)slot_QString___add__, add_slot},
    {(void *)slot_QString___imul__, irepeat_slot},
    {(void *)slot_QString___mul__, repeat_slot},
    {(void *)slot_QString___iadd__, iconcat_slot},
    {0, (sipPySlotType)0}
};


static PyMethodDef methods_QString[] = {
    {SIP_MLNAME_CAST(sipName_append), meth_QString_append, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_arg), meth_QString_arg, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_ascii), meth_QString_ascii, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_at), meth_QString_at, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_capacity), meth_QString_capacity, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_compare), meth_QString_compare, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_compose), meth_QString_compose, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_contains), meth_QString_contains, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_copy), meth_QString_copy, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_endsWith), meth_QString_endsWith, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_fill), meth_QString_fill, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_find), meth_QString_find, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_findRev), meth_QString_findRev, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_fromAscii), meth_QString_fromAscii, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_fromLatin1), meth_QString_fromLatin1, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_fromLocal8Bit), meth_QString_fromLocal8Bit, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_fromUtf8), meth_QString_fromUtf8, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_insert), meth_QString_insert, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_isEmpty), meth_QString_isEmpty, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_isNull), meth_QString_isNull, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_isRightToLeft), meth_QString_isRightToLeft, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_latin1), meth_QString_latin1, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_left), meth_QString_left, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_leftJustify), meth_QString_leftJustify, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_length), meth_QString_length, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_local8Bit), meth_QString_local8Bit, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_localeAwareCompare), meth_QString_localeAwareCompare, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_lower), meth_QString_lower, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_mid), meth_QString_mid, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_number), meth_QString_number, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_prepend), meth_QString_prepend, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_remove), meth_QString_remove, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_replace), meth_QString_replace, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_reserve), meth_QString_reserve, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_right), meth_QString_right, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_rightJustify), meth_QString_rightJustify, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_section), meth_QString_section, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_setAscii), meth_QString_setAscii, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_setExpand), meth_QString_setExpand, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_setLatin1), meth_QString_setLatin1, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_setLength), meth_QString_setLength, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_setNum), meth_QString_setNum, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_simpleText), meth_QString_simpleText, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_simplifyWhiteSpace), meth_QString_simplifyWhiteSpace, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_squeeze), meth_QString_squeeze, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_startsWith), meth_QString_startsWith, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_stripWhiteSpace), meth_QString_stripWhiteSpace, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_toDouble), meth_QString_toDouble, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_toFloat), meth_QString_toFloat, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_toInt), meth_QString_toInt, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_toLong), meth_QString_toLong, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_toShort), meth_QString_toShort, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_toUInt), meth_QString_toUInt, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_toULong), meth_QString_toULong, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_toUShort), meth_QString_toUShort, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_truncate), meth_QString_truncate, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_upper), meth_QString_upper, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_utf8), meth_QString_utf8, METH_VARARGS, NULL}
};

static sipEnumMemberDef enummembers_QString[] = {
    {sipName_SectionCaseInsensitiveSeps, QString::SectionCaseInsensitiveSeps, 288},
    {sipName_SectionDefault, QString::SectionDefault, 288},
    {sipName_SectionIncludeLeadingSep, QString::SectionIncludeLeadingSep, 288},
    {sipName_SectionIncludeTrailingSep, QString::SectionIncludeTrailingSep, 288},
    {sipName_SectionSkipEmpty, QString::SectionSkipEmpty, 288},
};


extern "C" {static PyObject *varget_QString_null(void *, PyObject *);}
static PyObject *varget_QString_null(void *, PyObject *)
{
    const QString *sipVal;
    sipVal = new QString(QString::null);

    return sipConvertFromNewType(const_cast<QString *>(sipVal),sipType_QString, NULL);
}

sipVariableDef variables_QString[] = {
    {sipName_null, varget_QString_null, NULL, 1},
};


pyqt3ClassTypeDef sipTypeDef_qt_QString = {
{
    {
        -1,
        0,
        0,
        SIP_TYPE_CLASS,
        sipNameNr_QString,
        {0}
    },
    {
        sipNameNr_QString,
        {0, 0, 1},
        58, methods_QString,
        5, enummembers_QString,
        1, variables_QString,
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    },
    0,
    sipNameNr_qt_pyqtWrapperType,
    sipNameNr_qt_pyqtWrapper,
    0,
    slots_QString,
    init_QString,
    0,
    0,
#if PY_MAJOR_VERSION >= 3
    0,
    0,
#else
    getreadbuffer_QString,
    0,
    getsegcount_QString,
    getcharbuffer_QString,
#endif
    dealloc_QString,
    assign_QString,
    array_QString,
    copy_QString,
    release_QString,
    cast_QString,
    convertTo_QString,
    0,
    0
},
    0
};
