/*
 * Interface wrapper code.
 *
 * Generated by SIP 4.10.2 on Mon Mar 28 16:23:17 2011
 *
 * Copyright (c) 2007
 * 	Riverbank Computing Limited <info@riverbankcomputing.co.uk>
 * 
 * This file is part of PyQt.
 * 
 * This copy of PyQt is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the Free
 * Software Foundation; either version 2, or (at your option) any later
 * version.
 * 
 * PyQt is supplied in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
 * details.
 * 
 * You should have received a copy of the GNU General Public License along with
 * PyQt; see the file LICENSE.  If not, write to the Free Software Foundation,
 * Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 */

#include "sipAPIqt.h"

#line 147 "/usr/share/sip/qt/qaction.sip"
#include <qaction.h>
#line 31 "sipqtQActionGroup.cc"

#line 66 "/usr/share/sip/qt/qobject.sip"
#include <qobject.h>
#include <qapplication.h>
#line 36 "sipqtQActionGroup.cc"
#line 53 "/usr/share/sip/qt/qmetaobject.sip"
#include <qmetaobject.h>
#line 39 "sipqtQActionGroup.cc"
#line 44 "/usr/share/sip/qt/qaction.sip"
#include <qaction.h>
#line 42 "sipqtQActionGroup.cc"
#line 63 "/usr/share/sip/qt/qwidget.sip"
#include <qwidget.h>
#line 45 "sipqtQActionGroup.cc"
#line 153 "/usr/share/sip/qt/qpopupmenu.sip"
#include <qpopupmenu.h>
#line 48 "sipqtQActionGroup.cc"
#line 1138 "/usr/share/sip/qt/qevent.sip"
#include <qevent.h>
#line 51 "sipqtQActionGroup.cc"
#line 449 "/usr/share/sip/qt/qstring.sip"
#include <qstring.h>
#line 54 "sipqtQActionGroup.cc"
#line 41 "/usr/share/sip/qt/qiconset.sip"
#include <qiconset.h>
#line 57 "sipqtQActionGroup.cc"
#line 40 "/usr/share/sip/qt/qkeysequence.sip"
#include <qkeysequence.h>
#line 60 "sipqtQActionGroup.cc"
#line 1163 "/usr/share/sip/qt/qevent.sip"
#include <qevent.h>
#line 63 "sipqtQActionGroup.cc"
#line 582 "/usr/share/sip/qt/qevent.sip"
#include <qevent.h>
#line 66 "sipqtQActionGroup.cc"
#line 201 "/usr/share/sip/qt/qvariant.sip"
#include <qvariant.h>
#line 69 "sipqtQActionGroup.cc"
#line 37 "/usr/share/sip/qt/qobjectlist.sip"
#include <qobjectlist.h>
#line 72 "sipqtQActionGroup.cc"
#line 324 "/usr/share/sip/qt/qevent.sip"
#include <qevent.h>
#line 75 "sipqtQActionGroup.cc"


class sipQActionGroup : public QActionGroup
{
public:
    sipQActionGroup(QObject *,const char *);
    sipQActionGroup(QObject *,const char *,bool);
    virtual ~sipQActionGroup();

    /*
     * There is a public method for every protected method visible from
     * this class.
     */
    void sipProtectVirt_timerEvent(bool,QTimerEvent *);
    void sipProtectVirt_customEvent(bool,QCustomEvent *);
    void sipProtectVirt_childEvent(bool,QChildEvent *);
    void sipProtectVirt_addedTo(bool,QWidget *,QWidget *,QAction *);
    void sipProtectVirt_addedTo(bool,int,QPopupMenu *,QAction *);
    void sipProtectVirt_addedTo(bool,QWidget *,QWidget *);
    void sipProtectVirt_addedTo(bool,int,QPopupMenu *);

    /*
     * There is a public method for every Qt signal that can be emitted
     * by this object.  This function is called by Python to emit the
     * signal.
     */
    int sipEmit_destroyed(PyObject *);
    int sipEmit_activated(PyObject *);
    int sipEmit_toggled(PyObject *);
    int sipEmit_selected(PyObject *);

    /*
     * There is a protected method for every virtual method visible from
     * this class.
     */
protected:
    QMetaObject * metaObject() const;
    void addedTo(QWidget *,QWidget *,QAction *);
    void addedTo(int,QPopupMenu *,QAction *);
    void addedTo(QWidget *,QWidget *);
    void addedTo(int,QPopupMenu *);
    void setIconSet(const QIconSet&);
    void setText(const QString&);
    void setMenuText(const QString&);
    void setToolTip(const QString&);
    void setStatusTip(const QString&);
    void setWhatsThis(const QString&);
    void setAccel(const QKeySequence&);
    void setToggleAction(bool);
    bool addTo(QWidget *);
    bool removeFrom(QWidget *);
    void setOn(bool);
    void setEnabled(bool);
    bool event(QEvent *);
    bool eventFilter(QObject *,QEvent *);
    void setName(const char *);
    void insertChild(QObject *);
    void removeChild(QObject *);
    bool setProperty(const char *,const QVariant&);
    QVariant property(const char *) const;
    void timerEvent(QTimerEvent *);
    void childEvent(QChildEvent *);
    void customEvent(QCustomEvent *);

public:
    sipSimpleWrapper *sipPySelf;

private:
    sipQActionGroup(const sipQActionGroup &);
    sipQActionGroup &operator = (const sipQActionGroup &);

    char sipPyMethods[27];
};

sipQActionGroup::sipQActionGroup(QObject *a0,const char *a1): QActionGroup(a0,a1), sipPySelf(0)
{
    memset(sipPyMethods, 0, sizeof (sipPyMethods));
}

sipQActionGroup::sipQActionGroup(QObject *a0,const char *a1,bool a2): QActionGroup(a0,a1,a2), sipPySelf(0)
{
    memset(sipPyMethods, 0, sizeof (sipPyMethods));
}

sipQActionGroup::~sipQActionGroup()
{
    sipCommonDtor(sipPySelf);
}

QMetaObject * sipQActionGroup::metaObject() const
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[0]),sipPySelf,NULL,sipName_metaObject);

    if (!meth)
        return QActionGroup::metaObject();

    extern QMetaObject * sipVH_qt_179(sip_gilstate_t,PyObject *);

    return sipVH_qt_179(sipGILState,meth);
}

void sipQActionGroup::addedTo(QWidget *a0,QWidget *a1,QAction *a2)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[1],sipPySelf,NULL,sipName_addedTo);

    if (!meth)
    {
        QActionGroup::addedTo(a0,a1,a2);
        return;
    }

    extern void sipVH_qt_313(sip_gilstate_t,PyObject *,QWidget *,QWidget *,QAction *);

    sipVH_qt_313(sipGILState,meth,a0,a1,a2);
}

void sipQActionGroup::addedTo(int a0,QPopupMenu *a1,QAction *a2)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[2],sipPySelf,NULL,sipName_addedTo);

    if (!meth)
    {
        QActionGroup::addedTo(a0,a1,a2);
        return;
    }

    extern void sipVH_qt_312(sip_gilstate_t,PyObject *,int,QPopupMenu *,QAction *);

    sipVH_qt_312(sipGILState,meth,a0,a1,a2);
}

void sipQActionGroup::addedTo(QWidget *a0,QWidget *a1)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[3],sipPySelf,NULL,sipName_addedTo);

    if (!meth)
    {
        QActionGroup::addedTo(a0,a1);
        return;
    }

    extern void sipVH_qt_311(sip_gilstate_t,PyObject *,QWidget *,QWidget *);

    sipVH_qt_311(sipGILState,meth,a0,a1);
}

void sipQActionGroup::addedTo(int a0,QPopupMenu *a1)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[4],sipPySelf,NULL,sipName_addedTo);

    if (!meth)
    {
        QActionGroup::addedTo(a0,a1);
        return;
    }

    extern void sipVH_qt_310(sip_gilstate_t,PyObject *,int,QPopupMenu *);

    sipVH_qt_310(sipGILState,meth,a0,a1);
}

void sipQActionGroup::setIconSet(const QIconSet& a0)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[5],sipPySelf,NULL,sipName_setIconSet);

    if (!meth)
    {
        QActionGroup::setIconSet(a0);
        return;
    }

    extern void sipVH_qt_73(sip_gilstate_t,PyObject *,const QIconSet&);

    sipVH_qt_73(sipGILState,meth,a0);
}

void sipQActionGroup::setText(const QString& a0)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[6],sipPySelf,NULL,sipName_setText);

    if (!meth)
    {
        QActionGroup::setText(a0);
        return;
    }

    extern void sipVH_qt_37(sip_gilstate_t,PyObject *,const QString&);

    sipVH_qt_37(sipGILState,meth,a0);
}

void sipQActionGroup::setMenuText(const QString& a0)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[7],sipPySelf,NULL,sipName_setMenuText);

    if (!meth)
    {
        QActionGroup::setMenuText(a0);
        return;
    }

    extern void sipVH_qt_37(sip_gilstate_t,PyObject *,const QString&);

    sipVH_qt_37(sipGILState,meth,a0);
}

void sipQActionGroup::setToolTip(const QString& a0)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[8],sipPySelf,NULL,sipName_setToolTip);

    if (!meth)
    {
        QActionGroup::setToolTip(a0);
        return;
    }

    extern void sipVH_qt_37(sip_gilstate_t,PyObject *,const QString&);

    sipVH_qt_37(sipGILState,meth,a0);
}

void sipQActionGroup::setStatusTip(const QString& a0)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[9],sipPySelf,NULL,sipName_setStatusTip);

    if (!meth)
    {
        QAction::setStatusTip(a0);
        return;
    }

    extern void sipVH_qt_37(sip_gilstate_t,PyObject *,const QString&);

    sipVH_qt_37(sipGILState,meth,a0);
}

void sipQActionGroup::setWhatsThis(const QString& a0)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[10],sipPySelf,NULL,sipName_setWhatsThis);

    if (!meth)
    {
        QActionGroup::setWhatsThis(a0);
        return;
    }

    extern void sipVH_qt_37(sip_gilstate_t,PyObject *,const QString&);

    sipVH_qt_37(sipGILState,meth,a0);
}

void sipQActionGroup::setAccel(const QKeySequence& a0)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[11],sipPySelf,NULL,sipName_setAccel);

    if (!meth)
    {
        QAction::setAccel(a0);
        return;
    }

    extern void sipVH_qt_308(sip_gilstate_t,PyObject *,const QKeySequence&);

    sipVH_qt_308(sipGILState,meth,a0);
}

void sipQActionGroup::setToggleAction(bool a0)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[12],sipPySelf,NULL,sipName_setToggleAction);

    if (!meth)
    {
        QActionGroup::setToggleAction(a0);
        return;
    }

    extern void sipVH_qt_10(sip_gilstate_t,PyObject *,bool);

    sipVH_qt_10(sipGILState,meth,a0);
}

bool sipQActionGroup::addTo(QWidget *a0)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[13],sipPySelf,NULL,sipName_addTo);

    if (!meth)
        return QActionGroup::addTo(a0);

    extern bool sipVH_qt_4(sip_gilstate_t,PyObject *,QWidget *);

    return sipVH_qt_4(sipGILState,meth,a0);
}

bool sipQActionGroup::removeFrom(QWidget *a0)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[14],sipPySelf,NULL,sipName_removeFrom);

    if (!meth)
        return QActionGroup::removeFrom(a0);

    extern bool sipVH_qt_4(sip_gilstate_t,PyObject *,QWidget *);

    return sipVH_qt_4(sipGILState,meth,a0);
}

void sipQActionGroup::setOn(bool a0)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[15],sipPySelf,NULL,sipName_setOn);

    if (!meth)
    {
        QActionGroup::setOn(a0);
        return;
    }

    extern void sipVH_qt_10(sip_gilstate_t,PyObject *,bool);

    sipVH_qt_10(sipGILState,meth,a0);
}

void sipQActionGroup::setEnabled(bool a0)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[16],sipPySelf,NULL,sipName_setEnabled);

    if (!meth)
    {
        QActionGroup::setEnabled(a0);
        return;
    }

    extern void sipVH_qt_10(sip_gilstate_t,PyObject *,bool);

    sipVH_qt_10(sipGILState,meth,a0);
}

bool sipQActionGroup::event(QEvent *a0)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[17],sipPySelf,NULL,sipName_event);

    if (!meth)
        return QObject::event(a0);

    extern bool sipVH_qt_178(sip_gilstate_t,PyObject *,QEvent *);

    return sipVH_qt_178(sipGILState,meth,a0);
}

bool sipQActionGroup::eventFilter(QObject *a0,QEvent *a1)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[18],sipPySelf,NULL,sipName_eventFilter);

    if (!meth)
        return QObject::eventFilter(a0,a1);

    extern bool sipVH_qt_177(sip_gilstate_t,PyObject *,QObject *,QEvent *);

    return sipVH_qt_177(sipGILState,meth,a0,a1);
}

void sipQActionGroup::setName(const char *a0)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[19],sipPySelf,NULL,sipName_setName);

    if (!meth)
    {
        QObject::setName(a0);
        return;
    }

    extern void sipVH_qt_176(sip_gilstate_t,PyObject *,const char *);

    sipVH_qt_176(sipGILState,meth,a0);
}

void sipQActionGroup::insertChild(QObject *a0)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[20],sipPySelf,NULL,sipName_insertChild);

    if (!meth)
    {
        QObject::insertChild(a0);
        return;
    }

    extern void sipVH_qt_175(sip_gilstate_t,PyObject *,QObject *);

    sipVH_qt_175(sipGILState,meth,a0);
}

void sipQActionGroup::removeChild(QObject *a0)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[21],sipPySelf,NULL,sipName_removeChild);

    if (!meth)
    {
        QObject::removeChild(a0);
        return;
    }

    extern void sipVH_qt_175(sip_gilstate_t,PyObject *,QObject *);

    sipVH_qt_175(sipGILState,meth,a0);
}

bool sipQActionGroup::setProperty(const char *a0,const QVariant& a1)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[22],sipPySelf,NULL,sipName_setProperty);

    if (!meth)
        return QObject::setProperty(a0,a1);

    extern bool sipVH_qt_174(sip_gilstate_t,PyObject *,const char *,const QVariant&);

    return sipVH_qt_174(sipGILState,meth,a0,a1);
}

QVariant sipQActionGroup::property(const char *a0) const
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[23]),sipPySelf,NULL,sipName_property);

    if (!meth)
        return QObject::property(a0);

    extern QVariant sipVH_qt_173(sip_gilstate_t,PyObject *,const char *);

    return sipVH_qt_173(sipGILState,meth,a0);
}

void sipQActionGroup::timerEvent(QTimerEvent *a0)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[24],sipPySelf,NULL,sipName_timerEvent);

    if (!meth)
    {
        QObject::timerEvent(a0);
        return;
    }

    extern void sipVH_qt_172(sip_gilstate_t,PyObject *,QTimerEvent *);

    sipVH_qt_172(sipGILState,meth,a0);
}

void sipQActionGroup::childEvent(QChildEvent *a0)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[25],sipPySelf,NULL,sipName_childEvent);

    if (!meth)
    {
        QActionGroup::childEvent(a0);
        return;
    }

    extern void sipVH_qt_171(sip_gilstate_t,PyObject *,QChildEvent *);

    sipVH_qt_171(sipGILState,meth,a0);
}

void sipQActionGroup::customEvent(QCustomEvent *a0)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[26],sipPySelf,NULL,sipName_customEvent);

    if (!meth)
    {
        QObject::customEvent(a0);
        return;
    }

    extern void sipVH_qt_170(sip_gilstate_t,PyObject *,QCustomEvent *);

    sipVH_qt_170(sipGILState,meth,a0);
}

void sipQActionGroup::sipProtectVirt_timerEvent(bool sipSelfWasArg,QTimerEvent *a0)
{
    (sipSelfWasArg ? QObject::timerEvent(a0) : timerEvent(a0));
}

void sipQActionGroup::sipProtectVirt_customEvent(bool sipSelfWasArg,QCustomEvent *a0)
{
    (sipSelfWasArg ? QObject::customEvent(a0) : customEvent(a0));
}

void sipQActionGroup::sipProtectVirt_childEvent(bool sipSelfWasArg,QChildEvent *a0)
{
    (sipSelfWasArg ? QActionGroup::childEvent(a0) : childEvent(a0));
}

void sipQActionGroup::sipProtectVirt_addedTo(bool sipSelfWasArg,QWidget *a0,QWidget *a1,QAction *a2)
{
    (sipSelfWasArg ? QActionGroup::addedTo(a0,a1,a2) : addedTo(a0,a1,a2));
}

void sipQActionGroup::sipProtectVirt_addedTo(bool sipSelfWasArg,int a0,QPopupMenu *a1,QAction *a2)
{
    (sipSelfWasArg ? QActionGroup::addedTo(a0,a1,a2) : addedTo(a0,a1,a2));
}

void sipQActionGroup::sipProtectVirt_addedTo(bool sipSelfWasArg,QWidget *a0,QWidget *a1)
{
    (sipSelfWasArg ? QActionGroup::addedTo(a0,a1) : addedTo(a0,a1));
}

void sipQActionGroup::sipProtectVirt_addedTo(bool sipSelfWasArg,int a0,QPopupMenu *a1)
{
    (sipSelfWasArg ? QActionGroup::addedTo(a0,a1) : addedTo(a0,a1));
}

int sipQActionGroup::sipEmit_destroyed(PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        if (sipParseArgs(&sipParseErr, sipArgs, ""))
        {
            emit destroyed();

            return 0;
        }
    }

    {
        QObject * a0;

        if (sipParseArgs(&sipParseErr, sipArgs, "J8", sipType_QObject, &a0))
        {
            emit destroyed(a0);

            return 0;
        }
    }

    sipNoMethod(sipParseErr, sipName_QActionGroup, sipName_destroyed, NULL);

    return -1;
}

extern "C" {static int QActionGroup_emit_destroyed(sipSimpleWrapper *, PyObject *);}
static int QActionGroup_emit_destroyed(sipSimpleWrapper *sw,PyObject *sipArgs)
{
    sipQActionGroup *ptr = reinterpret_cast<sipQActionGroup *>(sipGetComplexCppPtr(sw));

    return (ptr ? ptr->sipEmit_destroyed(sipArgs) : -1);
}

int sipQActionGroup::sipEmit_activated(PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        if (sipParseArgs(&sipParseErr, sipArgs, ""))
        {
            emit activated();

            return 0;
        }
    }

    sipNoMethod(sipParseErr, sipName_QActionGroup, sipName_activated, NULL);

    return -1;
}

extern "C" {static int QActionGroup_emit_activated(sipSimpleWrapper *, PyObject *);}
static int QActionGroup_emit_activated(sipSimpleWrapper *sw,PyObject *sipArgs)
{
    sipQActionGroup *ptr = reinterpret_cast<sipQActionGroup *>(sipGetComplexCppPtr(sw));

    return (ptr ? ptr->sipEmit_activated(sipArgs) : -1);
}

int sipQActionGroup::sipEmit_toggled(PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        bool a0;

        if (sipParseArgs(&sipParseErr, sipArgs, "b", &a0))
        {
            emit toggled(a0);

            return 0;
        }
    }

    sipNoMethod(sipParseErr, sipName_QActionGroup, sipName_toggled, NULL);

    return -1;
}

extern "C" {static int QActionGroup_emit_toggled(sipSimpleWrapper *, PyObject *);}
static int QActionGroup_emit_toggled(sipSimpleWrapper *sw,PyObject *sipArgs)
{
    sipQActionGroup *ptr = reinterpret_cast<sipQActionGroup *>(sipGetComplexCppPtr(sw));

    return (ptr ? ptr->sipEmit_toggled(sipArgs) : -1);
}

int sipQActionGroup::sipEmit_selected(PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QAction * a0;

        if (sipParseArgs(&sipParseErr, sipArgs, "J8", sipType_QAction, &a0))
        {
            emit selected(a0);

            return 0;
        }
    }

    sipNoMethod(sipParseErr, sipName_QActionGroup, sipName_selected, NULL);

    return -1;
}

extern "C" {static int QActionGroup_emit_selected(sipSimpleWrapper *, PyObject *);}
static int QActionGroup_emit_selected(sipSimpleWrapper *sw,PyObject *sipArgs)
{
    sipQActionGroup *ptr = reinterpret_cast<sipQActionGroup *>(sipGetComplexCppPtr(sw));

    return (ptr ? ptr->sipEmit_selected(sipArgs) : -1);
}

static pyqt3QtSignal signals_QActionGroup[] = {
    {sipName_destroyed, QActionGroup_emit_destroyed},
    {sipName_activated, QActionGroup_emit_activated},
    {sipName_toggled, QActionGroup_emit_toggled},
    {sipName_selected, QActionGroup_emit_selected},
    {NULL, NULL}
};


extern "C" {static PyObject *meth_QActionGroup_timerEvent(PyObject *, PyObject *);}
static PyObject *meth_QActionGroup_timerEvent(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        QTimerEvent * a0;
        sipQActionGroup *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ8", &sipSelf, sipType_QActionGroup, &sipCpp, sipType_QTimerEvent, &a0))
        {
            sipCpp->sipProtectVirt_timerEvent(sipSelfWasArg,a0);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QActionGroup, sipName_timerEvent, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QActionGroup_customEvent(PyObject *, PyObject *);}
static PyObject *meth_QActionGroup_customEvent(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        QCustomEvent * a0;
        sipQActionGroup *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ8", &sipSelf, sipType_QActionGroup, &sipCpp, sipType_QCustomEvent, &a0))
        {
            sipCpp->sipProtectVirt_customEvent(sipSelfWasArg,a0);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QActionGroup, sipName_customEvent, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QActionGroup_setExclusive(PyObject *, PyObject *);}
static PyObject *meth_QActionGroup_setExclusive(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        bool a0;
        QActionGroup *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bb", &sipSelf, sipType_QActionGroup, &sipCpp, &a0))
        {
            sipCpp->setExclusive(a0);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QActionGroup, sipName_setExclusive, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QActionGroup_isExclusive(PyObject *, PyObject *);}
static PyObject *meth_QActionGroup_isExclusive(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QActionGroup *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QActionGroup, &sipCpp))
        {
            bool sipRes;

            sipRes = sipCpp->isExclusive();

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QActionGroup, sipName_isExclusive, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QActionGroup_add(PyObject *, PyObject *);}
static PyObject *meth_QActionGroup_add(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QAction * a0;
        QActionGroup *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ8", &sipSelf, sipType_QActionGroup, &sipCpp, sipType_QAction, &a0))
        {
            sipCpp->add(a0);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QActionGroup, sipName_add, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QActionGroup_addSeparator(PyObject *, PyObject *);}
static PyObject *meth_QActionGroup_addSeparator(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QActionGroup *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QActionGroup, &sipCpp))
        {
            sipCpp->addSeparator();

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QActionGroup, sipName_addSeparator, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QActionGroup_addTo(PyObject *, PyObject *);}
static PyObject *meth_QActionGroup_addTo(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        QWidget * a0;
        QActionGroup *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ8", &sipSelf, sipType_QActionGroup, &sipCpp, sipType_QWidget, &a0))
        {
            bool sipRes;

            sipRes = (sipSelfWasArg ? sipCpp->QActionGroup::addTo(a0) : sipCpp->addTo(a0));

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QActionGroup, sipName_addTo, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QActionGroup_removeFrom(PyObject *, PyObject *);}
static PyObject *meth_QActionGroup_removeFrom(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        QWidget * a0;
        QActionGroup *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ8", &sipSelf, sipType_QActionGroup, &sipCpp, sipType_QWidget, &a0))
        {
            bool sipRes;

            sipRes = (sipSelfWasArg ? sipCpp->QActionGroup::removeFrom(a0) : sipCpp->removeFrom(a0));

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QActionGroup, sipName_removeFrom, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QActionGroup_setEnabled(PyObject *, PyObject *);}
static PyObject *meth_QActionGroup_setEnabled(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        bool a0;
        QActionGroup *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bb", &sipSelf, sipType_QActionGroup, &sipCpp, &a0))
        {
            (sipSelfWasArg ? sipCpp->QActionGroup::setEnabled(a0) : sipCpp->setEnabled(a0));

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QActionGroup, sipName_setEnabled, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QActionGroup_setToggleAction(PyObject *, PyObject *);}
static PyObject *meth_QActionGroup_setToggleAction(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        bool a0;
        QActionGroup *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bb", &sipSelf, sipType_QActionGroup, &sipCpp, &a0))
        {
            (sipSelfWasArg ? sipCpp->QActionGroup::setToggleAction(a0) : sipCpp->setToggleAction(a0));

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QActionGroup, sipName_setToggleAction, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QActionGroup_setOn(PyObject *, PyObject *);}
static PyObject *meth_QActionGroup_setOn(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        bool a0;
        QActionGroup *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bb", &sipSelf, sipType_QActionGroup, &sipCpp, &a0))
        {
            (sipSelfWasArg ? sipCpp->QActionGroup::setOn(a0) : sipCpp->setOn(a0));

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QActionGroup, sipName_setOn, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QActionGroup_setUsesDropDown(PyObject *, PyObject *);}
static PyObject *meth_QActionGroup_setUsesDropDown(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        bool a0;
        QActionGroup *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bb", &sipSelf, sipType_QActionGroup, &sipCpp, &a0))
        {
            sipCpp->setUsesDropDown(a0);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QActionGroup, sipName_setUsesDropDown, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QActionGroup_usesDropDown(PyObject *, PyObject *);}
static PyObject *meth_QActionGroup_usesDropDown(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QActionGroup *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QActionGroup, &sipCpp))
        {
            bool sipRes;

            sipRes = sipCpp->usesDropDown();

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QActionGroup, sipName_usesDropDown, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QActionGroup_setIconSet(PyObject *, PyObject *);}
static PyObject *meth_QActionGroup_setIconSet(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        const QIconSet * a0;
        QActionGroup *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ9", &sipSelf, sipType_QActionGroup, &sipCpp, sipType_QIconSet, &a0))
        {
            (sipSelfWasArg ? sipCpp->QActionGroup::setIconSet(*a0) : sipCpp->setIconSet(*a0));

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QActionGroup, sipName_setIconSet, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QActionGroup_setText(PyObject *, PyObject *);}
static PyObject *meth_QActionGroup_setText(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        const QString * a0;
        int a0State = 0;
        QActionGroup *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ1", &sipSelf, sipType_QActionGroup, &sipCpp, sipType_QString, &a0, &a0State))
        {
            (sipSelfWasArg ? sipCpp->QActionGroup::setText(*a0) : sipCpp->setText(*a0));
            sipReleaseType(const_cast<QString *>(a0),sipType_QString,a0State);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QActionGroup, sipName_setText, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QActionGroup_setMenuText(PyObject *, PyObject *);}
static PyObject *meth_QActionGroup_setMenuText(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        const QString * a0;
        int a0State = 0;
        QActionGroup *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ1", &sipSelf, sipType_QActionGroup, &sipCpp, sipType_QString, &a0, &a0State))
        {
            (sipSelfWasArg ? sipCpp->QActionGroup::setMenuText(*a0) : sipCpp->setMenuText(*a0));
            sipReleaseType(const_cast<QString *>(a0),sipType_QString,a0State);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QActionGroup, sipName_setMenuText, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QActionGroup_setToolTip(PyObject *, PyObject *);}
static PyObject *meth_QActionGroup_setToolTip(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        const QString * a0;
        int a0State = 0;
        QActionGroup *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ1", &sipSelf, sipType_QActionGroup, &sipCpp, sipType_QString, &a0, &a0State))
        {
            (sipSelfWasArg ? sipCpp->QActionGroup::setToolTip(*a0) : sipCpp->setToolTip(*a0));
            sipReleaseType(const_cast<QString *>(a0),sipType_QString,a0State);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QActionGroup, sipName_setToolTip, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QActionGroup_setWhatsThis(PyObject *, PyObject *);}
static PyObject *meth_QActionGroup_setWhatsThis(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        const QString * a0;
        int a0State = 0;
        QActionGroup *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ1", &sipSelf, sipType_QActionGroup, &sipCpp, sipType_QString, &a0, &a0State))
        {
            (sipSelfWasArg ? sipCpp->QActionGroup::setWhatsThis(*a0) : sipCpp->setWhatsThis(*a0));
            sipReleaseType(const_cast<QString *>(a0),sipType_QString,a0State);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QActionGroup, sipName_setWhatsThis, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QActionGroup_childEvent(PyObject *, PyObject *);}
static PyObject *meth_QActionGroup_childEvent(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        QChildEvent * a0;
        sipQActionGroup *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ8", &sipSelf, sipType_QActionGroup, &sipCpp, sipType_QChildEvent, &a0))
        {
            sipCpp->sipProtectVirt_childEvent(sipSelfWasArg,a0);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QActionGroup, sipName_childEvent, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QActionGroup_addedTo(PyObject *, PyObject *);}
static PyObject *meth_QActionGroup_addedTo(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        QWidget * a0;
        QWidget * a1;
        QAction * a2;
        sipQActionGroup *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ8J8J8", &sipSelf, sipType_QActionGroup, &sipCpp, sipType_QWidget, &a0, sipType_QWidget, &a1, sipType_QAction, &a2))
        {
            sipCpp->sipProtectVirt_addedTo(sipSelfWasArg,a0,a1,a2);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    {
        int a0;
        QPopupMenu * a1;
        QAction * a2;
        sipQActionGroup *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BiJ8J8", &sipSelf, sipType_QActionGroup, &sipCpp, &a0, sipType_QPopupMenu, &a1, sipType_QAction, &a2))
        {
            sipCpp->sipProtectVirt_addedTo(sipSelfWasArg,a0,a1,a2);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    {
        QWidget * a0;
        QWidget * a1;
        sipQActionGroup *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ8J8", &sipSelf, sipType_QActionGroup, &sipCpp, sipType_QWidget, &a0, sipType_QWidget, &a1))
        {
            sipCpp->sipProtectVirt_addedTo(sipSelfWasArg,a0,a1);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    {
        int a0;
        QPopupMenu * a1;
        sipQActionGroup *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BiJ8", &sipSelf, sipType_QActionGroup, &sipCpp, &a0, sipType_QPopupMenu, &a1))
        {
            sipCpp->sipProtectVirt_addedTo(sipSelfWasArg,a0,a1);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QActionGroup, sipName_addedTo, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QActionGroup_metaObject(PyObject *, PyObject *);}
static PyObject *meth_QActionGroup_metaObject(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        QActionGroup *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QActionGroup, &sipCpp))
        {
            QMetaObject *sipRes;

            sipRes = (sipSelfWasArg ? sipCpp->QActionGroup::metaObject() : sipCpp->metaObject());

            return sipConvertFromType(sipRes,sipType_QMetaObject,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QActionGroup, sipName_metaObject, NULL);

    return NULL;
}


/* Cast a pointer to a type somewhere in its superclass hierarchy. */
extern "C" {static void *cast_QActionGroup(void *, const sipTypeDef *);}
static void *cast_QActionGroup(void *ptr, const sipTypeDef *targetType)
{
    void *res;

    if (targetType == sipType_QActionGroup)
        return ptr;

    if ((res = ((const sipClassTypeDef *)sipType_QAction)->ctd_cast((QAction *)(QActionGroup *)ptr,targetType)) != NULL)
        return res;

    return NULL;
}


/* Call the instance's destructor. */
extern "C" {static void release_QActionGroup(void *, int);}
static void release_QActionGroup(void *sipCppV,int sipState)
{
    if (sipState & SIP_DERIVED_CLASS)
        delete reinterpret_cast<sipQActionGroup *>(sipCppV);
    else
        delete reinterpret_cast<QActionGroup *>(sipCppV);
}


extern "C" {static void dealloc_QActionGroup(sipSimpleWrapper *);}
static void dealloc_QActionGroup(sipSimpleWrapper *sipSelf)
{
    if (sipIsDerived(sipSelf))
        reinterpret_cast<sipQActionGroup *>(sipSelf->u.cppPtr)->sipPySelf = NULL;

    if (sipIsPyOwned(sipSelf))
    {
        release_QActionGroup(sipSelf->u.cppPtr,sipSelf->flags);
    }
}


extern "C" {static void *init_QActionGroup(sipSimpleWrapper *, PyObject *, PyObject *, PyObject **, PyObject **, PyObject **);}
static void *init_QActionGroup(sipSimpleWrapper *sipSelf, PyObject *sipArgs, PyObject *sipKwds, PyObject **sipUnused, PyObject **sipOwner, PyObject **sipParseErr)
{
    sipQActionGroup *sipCpp = 0;

    {
        QObject * a0;
        const char * a1 = 0;

        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, NULL, sipUnused, "JH|s", sipType_QObject, &a0, sipOwner, &a1))
        {
            sipCpp = new sipQActionGroup(a0,a1);

            sipCpp->sipPySelf = sipSelf;

            return sipCpp;
        }
    }

    {
        QObject * a0;
        const char * a1;
        bool a2;

        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, NULL, sipUnused, "JHsb", sipType_QObject, &a0, sipOwner, &a1, &a2))
        {
            sipCpp = new sipQActionGroup(a0,a1,a2);

            sipCpp->sipPySelf = sipSelf;

            return sipCpp;
        }
    }

    return NULL;
}


/* Define this type's super-types. */
static sipEncodedTypeDef supers_QActionGroup[] = {{1, 255, 1}};


static PyMethodDef methods_QActionGroup[] = {
    {SIP_MLNAME_CAST(sipName_add), meth_QActionGroup_add, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_addSeparator), meth_QActionGroup_addSeparator, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_addTo), meth_QActionGroup_addTo, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_addedTo), meth_QActionGroup_addedTo, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_childEvent), meth_QActionGroup_childEvent, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_customEvent), meth_QActionGroup_customEvent, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_isExclusive), meth_QActionGroup_isExclusive, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_metaObject), meth_QActionGroup_metaObject, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_removeFrom), meth_QActionGroup_removeFrom, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_setEnabled), meth_QActionGroup_setEnabled, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_setExclusive), meth_QActionGroup_setExclusive, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_setIconSet), meth_QActionGroup_setIconSet, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_setMenuText), meth_QActionGroup_setMenuText, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_setOn), meth_QActionGroup_setOn, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_setText), meth_QActionGroup_setText, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_setToggleAction), meth_QActionGroup_setToggleAction, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_setToolTip), meth_QActionGroup_setToolTip, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_setUsesDropDown), meth_QActionGroup_setUsesDropDown, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_setWhatsThis), meth_QActionGroup_setWhatsThis, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_timerEvent), meth_QActionGroup_timerEvent, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_usesDropDown), meth_QActionGroup_usesDropDown, METH_VARARGS, NULL}
};


pyqt3ClassTypeDef sipTypeDef_qt_QActionGroup = {
{
    {
        -1,
        0,
        0,
        SIP_TYPE_SCC|SIP_TYPE_CLASS,
        sipNameNr_QActionGroup,
        {0}
    },
    {
        sipNameNr_QActionGroup,
        {0, 0, 1},
        21, methods_QActionGroup,
        0, 0,
        0, 0,
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    },
    0,
    -1,
    -1,
    supers_QActionGroup,
    0,
    init_QActionGroup,
    0,
    0,
#if PY_MAJOR_VERSION >= 3
    0,
    0,
#else
    0,
    0,
    0,
    0,
#endif
    dealloc_QActionGroup,
    0,
    0,
    0,
    release_QActionGroup,
    cast_QActionGroup,
    0,
    0,
    0
},
    signals_QActionGroup
};
