/*
 * Interface wrapper code.
 *
 * Generated by SIP 4.10.2 on Mon Mar 28 16:23:17 2011
 *
 * Copyright (c) 2007
 * 	Riverbank Computing Limited <info@riverbankcomputing.co.uk>
 * 
 * This file is part of PyQt.
 * 
 * This copy of PyQt is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the Free
 * Software Foundation; either version 2, or (at your option) any later
 * version.
 * 
 * PyQt is supplied in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
 * details.
 * 
 * You should have received a copy of the GNU General Public License along with
 * PyQt; see the file LICENSE.  If not, write to the Free Software Foundation,
 * Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 */

#include "sipAPIqt.h"

#line 120 "/usr/share/sip/qt/qcstring.sip"
#include <qcstring.h>
#line 31 "sipqtQCString.cc"

#line 60 "/usr/share/sip/qt/qregexp.sip"
#include <qregexp.h>
#line 35 "sipqtQCString.cc"
#line 98 "/usr/share/sip/qt/qbytearray.sip"
#include <qstring.h>
#line 38 "sipqtQCString.cc"


extern "C" {static PyObject *meth_QCString_isNull(PyObject *, PyObject *);}
static PyObject *meth_QCString_isNull(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QCString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QCString, &sipCpp))
        {
            bool sipRes;

            sipRes = sipCpp->isNull();

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QCString, sipName_isNull, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QCString_isEmpty(PyObject *, PyObject *);}
static PyObject *meth_QCString_isEmpty(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QCString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QCString, &sipCpp))
        {
            bool sipRes;

            sipRes = sipCpp->isEmpty();

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QCString, sipName_isEmpty, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QCString_length(PyObject *, PyObject *);}
static PyObject *meth_QCString_length(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QCString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QCString, &sipCpp))
        {
            uint sipRes;

            sipRes = sipCpp->length();

            return PyLong_FromUnsignedLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QCString, sipName_length, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QCString_resize(PyObject *, PyObject *);}
static PyObject *meth_QCString_resize(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        uint a0;
        QCString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bu", &sipSelf, sipType_QCString, &sipCpp, &a0))
        {
            bool sipRes;

            sipRes = sipCpp->resize(a0);

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QCString, sipName_resize, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QCString_truncate(PyObject *, PyObject *);}
static PyObject *meth_QCString_truncate(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        uint a0;
        QCString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bu", &sipSelf, sipType_QCString, &sipCpp, &a0))
        {
            bool sipRes;

            sipRes = sipCpp->truncate(a0);

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QCString, sipName_truncate, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QCString_fill(PyObject *, PyObject *);}
static PyObject *meth_QCString_fill(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        char a0;
        int a1 = -1;
        QCString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bc|i", &sipSelf, sipType_QCString, &sipCpp, &a0, &a1))
        {
            bool sipRes;

            sipRes = sipCpp->fill(a0,a1);

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QCString, sipName_fill, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QCString_copy(PyObject *, PyObject *);}
static PyObject *meth_QCString_copy(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QCString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QCString, &sipCpp))
        {
            QCString *sipRes;

            sipRes = new QCString(sipCpp->copy());

            return sipConvertFromNewType(sipRes,sipType_QCString,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QCString, sipName_copy, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QCString_find(PyObject *, PyObject *);}
static PyObject *meth_QCString_find(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const char * a0;
        int a1 = 0;
        bool a2 = 1;
        QCString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bs|ib", &sipSelf, sipType_QCString, &sipCpp, &a0, &a1, &a2))
        {
            int sipRes;

            sipRes = sipCpp->find(a0,a1,a2);

            return SIPLong_FromLong(sipRes);
        }
    }

    {
        const QRegExp * a0;
        int a1 = 0;
        QCString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ9|i", &sipSelf, sipType_QCString, &sipCpp, sipType_QRegExp, &a0, &a1))
        {
            int sipRes;

            sipRes = sipCpp->find(*a0,a1);

            return SIPLong_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QCString, sipName_find, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QCString_findRev(PyObject *, PyObject *);}
static PyObject *meth_QCString_findRev(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const char * a0;
        int a1 = -1;
        bool a2 = 1;
        QCString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bs|ib", &sipSelf, sipType_QCString, &sipCpp, &a0, &a1, &a2))
        {
            int sipRes;

            sipRes = sipCpp->findRev(a0,a1,a2);

            return SIPLong_FromLong(sipRes);
        }
    }

    {
        const QRegExp * a0;
        int a1 = -1;
        QCString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ9|i", &sipSelf, sipType_QCString, &sipCpp, sipType_QRegExp, &a0, &a1))
        {
            int sipRes;

            sipRes = sipCpp->findRev(*a0,a1);

            return SIPLong_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QCString, sipName_findRev, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QCString_contains(PyObject *, PyObject *);}
static PyObject *meth_QCString_contains(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const char * a0;
        bool a1 = 1;
        QCString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bs|b", &sipSelf, sipType_QCString, &sipCpp, &a0, &a1))
        {
            int sipRes;

            sipRes = sipCpp->contains(a0,a1);

            return SIPLong_FromLong(sipRes);
        }
    }

    {
        const QRegExp * a0;
        QCString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ9", &sipSelf, sipType_QCString, &sipCpp, sipType_QRegExp, &a0))
        {
            int sipRes;

            sipRes = sipCpp->contains(*a0);

            return SIPLong_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QCString, sipName_contains, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QCString_left(PyObject *, PyObject *);}
static PyObject *meth_QCString_left(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        uint a0;
        QCString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bu", &sipSelf, sipType_QCString, &sipCpp, &a0))
        {
            QCString *sipRes;

            sipRes = new QCString(sipCpp->left(a0));

            return sipConvertFromNewType(sipRes,sipType_QCString,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QCString, sipName_left, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QCString_right(PyObject *, PyObject *);}
static PyObject *meth_QCString_right(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        uint a0;
        QCString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bu", &sipSelf, sipType_QCString, &sipCpp, &a0))
        {
            QCString *sipRes;

            sipRes = new QCString(sipCpp->right(a0));

            return sipConvertFromNewType(sipRes,sipType_QCString,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QCString, sipName_right, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QCString_mid(PyObject *, PyObject *);}
static PyObject *meth_QCString_mid(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        uint a0;
        uint a1 = 4294967295;
        QCString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bu|u", &sipSelf, sipType_QCString, &sipCpp, &a0, &a1))
        {
            QCString *sipRes;

            sipRes = new QCString(sipCpp->mid(a0,a1));

            return sipConvertFromNewType(sipRes,sipType_QCString,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QCString, sipName_mid, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QCString_leftJustify(PyObject *, PyObject *);}
static PyObject *meth_QCString_leftJustify(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        uint a0;
        char a1 = ' ';
        bool a2 = 0;
        QCString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bu|cb", &sipSelf, sipType_QCString, &sipCpp, &a0, &a1, &a2))
        {
            QCString *sipRes;

            sipRes = new QCString(sipCpp->leftJustify(a0,a1,a2));

            return sipConvertFromNewType(sipRes,sipType_QCString,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QCString, sipName_leftJustify, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QCString_rightJustify(PyObject *, PyObject *);}
static PyObject *meth_QCString_rightJustify(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        uint a0;
        char a1 = ' ';
        bool a2 = 0;
        QCString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bu|cb", &sipSelf, sipType_QCString, &sipCpp, &a0, &a1, &a2))
        {
            QCString *sipRes;

            sipRes = new QCString(sipCpp->rightJustify(a0,a1,a2));

            return sipConvertFromNewType(sipRes,sipType_QCString,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QCString, sipName_rightJustify, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QCString_lower(PyObject *, PyObject *);}
static PyObject *meth_QCString_lower(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QCString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QCString, &sipCpp))
        {
            QCString *sipRes;

            sipRes = new QCString(sipCpp->lower());

            return sipConvertFromNewType(sipRes,sipType_QCString,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QCString, sipName_lower, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QCString_upper(PyObject *, PyObject *);}
static PyObject *meth_QCString_upper(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QCString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QCString, &sipCpp))
        {
            QCString *sipRes;

            sipRes = new QCString(sipCpp->upper());

            return sipConvertFromNewType(sipRes,sipType_QCString,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QCString, sipName_upper, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QCString_stripWhiteSpace(PyObject *, PyObject *);}
static PyObject *meth_QCString_stripWhiteSpace(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QCString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QCString, &sipCpp))
        {
            QCString *sipRes;

            sipRes = new QCString(sipCpp->stripWhiteSpace());

            return sipConvertFromNewType(sipRes,sipType_QCString,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QCString, sipName_stripWhiteSpace, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QCString_simplifyWhiteSpace(PyObject *, PyObject *);}
static PyObject *meth_QCString_simplifyWhiteSpace(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QCString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QCString, &sipCpp))
        {
            QCString *sipRes;

            sipRes = new QCString(sipCpp->simplifyWhiteSpace());

            return sipConvertFromNewType(sipRes,sipType_QCString,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QCString, sipName_simplifyWhiteSpace, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QCString_insert(PyObject *, PyObject *);}
static PyObject *meth_QCString_insert(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        uint a0;
        const char * a1;
        QCString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bus", &sipSelf, sipType_QCString, &sipCpp, &a0, &a1))
        {
            QCString *sipRes;

            sipRes = &sipCpp->insert(a0,a1);

            return sipConvertFromType(sipRes,sipType_QCString,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QCString, sipName_insert, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QCString_append(PyObject *, PyObject *);}
static PyObject *meth_QCString_append(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const char * a0;
        QCString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bs", &sipSelf, sipType_QCString, &sipCpp, &a0))
        {
            QCString *sipRes;

            sipRes = &sipCpp->append(a0);

            return sipConvertFromType(sipRes,sipType_QCString,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QCString, sipName_append, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QCString_prepend(PyObject *, PyObject *);}
static PyObject *meth_QCString_prepend(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const char * a0;
        QCString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bs", &sipSelf, sipType_QCString, &sipCpp, &a0))
        {
            QCString *sipRes;

            sipRes = &sipCpp->prepend(a0);

            return sipConvertFromType(sipRes,sipType_QCString,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QCString, sipName_prepend, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QCString_remove(PyObject *, PyObject *);}
static PyObject *meth_QCString_remove(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        uint a0;
        uint a1;
        QCString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Buu", &sipSelf, sipType_QCString, &sipCpp, &a0, &a1))
        {
            QCString *sipRes;

            sipRes = &sipCpp->remove(a0,a1);

            return sipConvertFromType(sipRes,sipType_QCString,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QCString, sipName_remove, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QCString_replace(PyObject *, PyObject *);}
static PyObject *meth_QCString_replace(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        uint a0;
        uint a1;
        const char * a2;
        QCString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Buus", &sipSelf, sipType_QCString, &sipCpp, &a0, &a1, &a2))
        {
            QCString *sipRes;

            sipRes = &sipCpp->replace(a0,a1,a2);

            return sipConvertFromType(sipRes,sipType_QCString,NULL);
        }
    }

    {
        const QRegExp * a0;
        const char * a1;
        QCString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ9s", &sipSelf, sipType_QCString, &sipCpp, sipType_QRegExp, &a0, &a1))
        {
            QCString *sipRes;

            sipRes = &sipCpp->replace(*a0,a1);

            return sipConvertFromType(sipRes,sipType_QCString,NULL);
        }
    }

    {
        const char * a0;
        const char * a1;
        QCString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bss", &sipSelf, sipType_QCString, &sipCpp, &a0, &a1))
        {
            QCString *sipRes;

            sipRes = &sipCpp->replace(a0,a1);

            return sipConvertFromType(sipRes,sipType_QCString,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QCString, sipName_replace, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QCString_toShort(PyObject *, PyObject *);}
static PyObject *meth_QCString_toShort(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        bool a0;
        QCString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QCString, &sipCpp))
        {
            short sipRes;

            sipRes = sipCpp->toShort(&a0);

            return sipBuildResult(0,"(hb)",sipRes,a0);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QCString, sipName_toShort, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QCString_toUShort(PyObject *, PyObject *);}
static PyObject *meth_QCString_toUShort(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        bool a0;
        QCString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QCString, &sipCpp))
        {
            ushort sipRes;

            sipRes = sipCpp->toUShort(&a0);

            return sipBuildResult(0,"(tb)",sipRes,a0);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QCString, sipName_toUShort, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QCString_toInt(PyObject *, PyObject *);}
static PyObject *meth_QCString_toInt(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        bool a0;
        QCString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QCString, &sipCpp))
        {
            int sipRes;

            sipRes = sipCpp->toInt(&a0);

            return sipBuildResult(0,"(ib)",sipRes,a0);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QCString, sipName_toInt, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QCString_toUInt(PyObject *, PyObject *);}
static PyObject *meth_QCString_toUInt(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        bool a0;
        QCString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QCString, &sipCpp))
        {
            uint sipRes;

            sipRes = sipCpp->toUInt(&a0);

            return sipBuildResult(0,"(ub)",sipRes,a0);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QCString, sipName_toUInt, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QCString_toLong(PyObject *, PyObject *);}
static PyObject *meth_QCString_toLong(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        bool a0;
        QCString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QCString, &sipCpp))
        {
            long sipRes;

            sipRes = sipCpp->toLong(&a0);

            return sipBuildResult(0,"(lb)",sipRes,a0);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QCString, sipName_toLong, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QCString_toULong(PyObject *, PyObject *);}
static PyObject *meth_QCString_toULong(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        bool a0;
        QCString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QCString, &sipCpp))
        {
            ulong sipRes;

            sipRes = sipCpp->toULong(&a0);

            return sipBuildResult(0,"(mb)",sipRes,a0);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QCString, sipName_toULong, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QCString_toFloat(PyObject *, PyObject *);}
static PyObject *meth_QCString_toFloat(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        bool a0;
        QCString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QCString, &sipCpp))
        {
            float sipRes;

            sipRes = sipCpp->toFloat(&a0);

            return sipBuildResult(0,"(fb)",sipRes,a0);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QCString, sipName_toFloat, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QCString_toDouble(PyObject *, PyObject *);}
static PyObject *meth_QCString_toDouble(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        bool a0;
        QCString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QCString, &sipCpp))
        {
            double sipRes;

            sipRes = sipCpp->toDouble(&a0);

            return sipBuildResult(0,"(db)",sipRes,a0);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QCString, sipName_toDouble, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QCString_setStr(PyObject *, PyObject *);}
static PyObject *meth_QCString_setStr(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const char * a0;
        QCString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bs", &sipSelf, sipType_QCString, &sipCpp, &a0))
        {
            QCString *sipRes;

            sipRes = &sipCpp->setStr(a0);

            return sipConvertFromType(sipRes,sipType_QCString,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QCString, sipName_setStr, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QCString_setNum(PyObject *, PyObject *);}
static PyObject *meth_QCString_setNum(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        int a0;
        QCString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BXi", &sipSelf, sipType_QCString, &sipCpp, &a0))
        {
            QCString *sipRes;

            sipRes = &sipCpp->setNum(a0);

            return sipConvertFromType(sipRes,sipType_QCString,NULL);
        }
    }

    {
        double a0;
        char a1 = 'g';
        int a2 = 6;
        QCString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bd|ci", &sipSelf, sipType_QCString, &sipCpp, &a0, &a1, &a2))
        {
            QCString *sipRes;

            sipRes = &sipCpp->setNum(a0,a1,a2);

            return sipConvertFromType(sipRes,sipType_QCString,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QCString, sipName_setNum, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QCString_setExpand(PyObject *, PyObject *);}
static PyObject *meth_QCString_setExpand(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        uint a0;
        char a1;
        QCString *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Buc", &sipSelf, sipType_QCString, &sipCpp, &a0, &a1))
        {
            bool sipRes;

            sipRes = sipCpp->setExpand(a0,a1);

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QCString, sipName_setExpand, NULL);

    return NULL;
}


extern "C" {static PyObject *slot_QCString___str__(PyObject *sipSelf);}
static PyObject *slot_QCString___str__(PyObject *sipSelf)
{
    QCString *sipCpp = reinterpret_cast<QCString *>(sipGetCppPtr((sipSimpleWrapper *)sipSelf,sipType_QCString));

    if (!sipCpp)
        return 0;


    {
        {
            PyObject * sipRes = 0;

#line 191 "/usr/share/sip/qt/qcstring.sip"
		const char *s;
 
		Py_BEGIN_ALLOW_THREADS
		s = *sipCpp;
		Py_END_ALLOW_THREADS

		if (s == NULL)
			s = "";
 
		sipRes = PyString_FromString(s);
#line 1073 "sipqtQCString.cc"

            return sipRes;
        }
    }
}


/* Cast a pointer to a type somewhere in its superclass hierarchy. */
extern "C" {static void *cast_QCString(void *, const sipTypeDef *);}
static void *cast_QCString(void *ptr, const sipTypeDef *targetType)
{
    void *res;

    if (targetType == sipType_QCString)
        return ptr;

    if ((res = ((const sipClassTypeDef *)sipType_QByteArray)->ctd_cast((QByteArray *)(QCString *)ptr,targetType)) != NULL)
        return res;

    return NULL;
}


/* Call the instance's destructor. */
extern "C" {static void release_QCString(void *, int);}
static void release_QCString(void *sipCppV,int)
{
    delete reinterpret_cast<QCString *>(sipCppV);
}


extern "C" {static void assign_QCString(void *, SIP_SSIZE_T, const void *);}
static void assign_QCString(void *sipDst, SIP_SSIZE_T sipDstIdx, const void *sipSrc)
{
    reinterpret_cast<QCString *>(sipDst)[sipDstIdx] = *reinterpret_cast<const QCString *>(sipSrc);
}


extern "C" {static void *array_QCString(SIP_SSIZE_T);}
static void *array_QCString(SIP_SSIZE_T sipNrElem)
{
    return new QCString[sipNrElem];
}


extern "C" {static void *copy_QCString(const void *, SIP_SSIZE_T);}
static void *copy_QCString(const void *sipSrc, SIP_SSIZE_T sipSrcIdx)
{
    return new QCString(reinterpret_cast<const QCString *>(sipSrc)[sipSrcIdx]);
}


extern "C" {static void dealloc_QCString(sipSimpleWrapper *);}
static void dealloc_QCString(sipSimpleWrapper *sipSelf)
{
    if (sipIsPyOwned(sipSelf))
    {
        release_QCString(sipSelf->u.cppPtr,0);
    }
}


extern "C" {static void *init_QCString(sipSimpleWrapper *, PyObject *, PyObject *, PyObject **, PyObject **, PyObject **);}
static void *init_QCString(sipSimpleWrapper *, PyObject *sipArgs, PyObject *sipKwds, PyObject **sipUnused, PyObject **, PyObject **sipParseErr)
{
    QCString *sipCpp = 0;

    {
        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, NULL, sipUnused, ""))
        {
            sipCpp = new QCString();

            return sipCpp;
        }
    }

    {
        int a0;

        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, NULL, sipUnused, "i", &a0))
        {
            sipCpp = new QCString(a0);

            return sipCpp;
        }
    }

    {
        const QCString * a0;
        int a0State = 0;

        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, NULL, sipUnused, "J1", sipType_QCString, &a0, &a0State))
        {
            sipCpp = new QCString(*a0);
            sipReleaseType(const_cast<QCString *>(a0),sipType_QCString,a0State);

            return sipCpp;
        }
    }

    {
        const char * a0;

        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, NULL, sipUnused, "s", &a0))
        {
            sipCpp = new QCString(a0);

            return sipCpp;
        }
    }

    {
        const char * a0;
        uint a1;

        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, NULL, sipUnused, "su", &a0, &a1))
        {
            sipCpp = new QCString(a0,a1);

            return sipCpp;
        }
    }

    return NULL;
}


extern "C" {static int convertTo_QCString(PyObject *, void **, int *, PyObject *);}
static int convertTo_QCString(PyObject *sipPy,void **sipCppPtrV,int *sipIsErr,PyObject *sipTransferObj)
{
    QCString **sipCppPtr = reinterpret_cast<QCString **>(sipCppPtrV);

#line 204 "/usr/share/sip/qt/qcstring.sip"
	// Allow a Python string whenever a QCString is expected.

	if (sipIsErr == NULL)
		return (PyString_Check(sipPy) ||
			sipCanConvertToInstance(sipPy,sipClass_QCString,SIP_NO_CONVERTORS));

	if (PyString_Check(sipPy))
	{
		*sipCppPtr = new QCString(PyString_AS_STRING(sipPy));

		return sipGetState(sipTransferObj);
	}

	*sipCppPtr = reinterpret_cast<QCString *>(sipConvertToInstance(sipPy,sipClass_QCString,sipTransferObj,SIP_NO_CONVERTORS,0,sipIsErr));

	return 0;
#line 1223 "sipqtQCString.cc"
}


/* Define this type's super-types. */
static sipEncodedTypeDef supers_QCString[] = {{16, 255, 1}};


/* Define this type's Python slots. */
static sipPySlotDef slots_QCString[] = {
    {(void *)slot_QCString___str__, str_slot},
    {0, (sipPySlotType)0}
};


static PyMethodDef methods_QCString[] = {
    {SIP_MLNAME_CAST(sipName_append), meth_QCString_append, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_contains), meth_QCString_contains, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_copy), meth_QCString_copy, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_fill), meth_QCString_fill, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_find), meth_QCString_find, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_findRev), meth_QCString_findRev, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_insert), meth_QCString_insert, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_isEmpty), meth_QCString_isEmpty, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_isNull), meth_QCString_isNull, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_left), meth_QCString_left, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_leftJustify), meth_QCString_leftJustify, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_length), meth_QCString_length, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_lower), meth_QCString_lower, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_mid), meth_QCString_mid, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_prepend), meth_QCString_prepend, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_remove), meth_QCString_remove, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_replace), meth_QCString_replace, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_resize), meth_QCString_resize, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_right), meth_QCString_right, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_rightJustify), meth_QCString_rightJustify, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_setExpand), meth_QCString_setExpand, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_setNum), meth_QCString_setNum, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_setStr), meth_QCString_setStr, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_simplifyWhiteSpace), meth_QCString_simplifyWhiteSpace, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_stripWhiteSpace), meth_QCString_stripWhiteSpace, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_toDouble), meth_QCString_toDouble, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_toFloat), meth_QCString_toFloat, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_toInt), meth_QCString_toInt, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_toLong), meth_QCString_toLong, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_toShort), meth_QCString_toShort, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_toUInt), meth_QCString_toUInt, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_toULong), meth_QCString_toULong, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_toUShort), meth_QCString_toUShort, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_truncate), meth_QCString_truncate, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_upper), meth_QCString_upper, METH_VARARGS, NULL}
};


pyqt3ClassTypeDef sipTypeDef_qt_QCString = {
{
    {
        -1,
        0,
        0,
        SIP_TYPE_CLASS,
        sipNameNr_QCString,
        {0}
    },
    {
        sipNameNr_QCString,
        {0, 0, 1},
        35, methods_QCString,
        0, 0,
        0, 0,
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    },
    0,
    -1,
    -1,
    supers_QCString,
    slots_QCString,
    init_QCString,
    0,
    0,
#if PY_MAJOR_VERSION >= 3
    0,
    0,
#else
    0,
    0,
    0,
    0,
#endif
    dealloc_QCString,
    assign_QCString,
    array_QCString,
    copy_QCString,
    release_QCString,
    cast_QCString,
    convertTo_QCString,
    0,
    0
},
    0
};
