/*
 * Interface wrapper code.
 *
 * Generated by SIP 4.10.2 on Mon Mar 28 16:23:15 2011
 *
 * Copyright (c) 2007
 * 	Riverbank Computing Limited <info@riverbankcomputing.co.uk>
 * 
 * This file is part of PyQt.
 * 
 * This copy of PyQt is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the Free
 * Software Foundation; either version 2, or (at your option) any later
 * version.
 * 
 * PyQt is supplied in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
 * details.
 * 
 * You should have received a copy of the GNU General Public License along with
 * PyQt; see the file LICENSE.  If not, write to the Free Software Foundation,
 * Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 */

#include "sipAPIqt.h"

#line 37 "/usr/share/sip/qt/qprocess.sip"
#include <qprocess.h>
#line 31 "sipqtQProcess.cc"

#line 66 "/usr/share/sip/qt/qobject.sip"
#include <qobject.h>
#include <qapplication.h>
#line 36 "sipqtQProcess.cc"
#line 449 "/usr/share/sip/qt/qstring.sip"
#include <qstring.h>
#line 39 "sipqtQProcess.cc"
#line 57 "/usr/share/sip/qt/qstringlist.sip"
#include <qstringlist.h>
#line 42 "sipqtQProcess.cc"
#line 53 "/usr/share/sip/qt/qmetaobject.sip"
#include <qmetaobject.h>
#line 45 "sipqtQProcess.cc"
#line 98 "/usr/share/sip/qt/qbytearray.sip"
#include <qstring.h>
#line 48 "sipqtQProcess.cc"
#line 122 "/usr/share/sip/qt/qdir.sip"
#include <qdir.h>
#line 51 "sipqtQProcess.cc"
#line 1163 "/usr/share/sip/qt/qevent.sip"
#include <qevent.h>
#line 54 "sipqtQProcess.cc"
#line 1138 "/usr/share/sip/qt/qevent.sip"
#include <qevent.h>
#line 57 "sipqtQProcess.cc"
#line 582 "/usr/share/sip/qt/qevent.sip"
#include <qevent.h>
#line 60 "sipqtQProcess.cc"
#line 201 "/usr/share/sip/qt/qvariant.sip"
#include <qvariant.h>
#line 63 "sipqtQProcess.cc"
#line 37 "/usr/share/sip/qt/qobjectlist.sip"
#include <qobjectlist.h>
#line 66 "sipqtQProcess.cc"
#line 324 "/usr/share/sip/qt/qevent.sip"
#include <qevent.h>
#line 69 "sipqtQProcess.cc"


class sipQProcess : public QProcess
{
public:
    sipQProcess(QObject *,const char *);
    sipQProcess(const QString&,QObject *,const char *);
    sipQProcess(const QStringList&,QObject *,const char *);
    virtual ~sipQProcess();

    /*
     * There is a public method for every protected method visible from
     * this class.
     */
    void sipProtectVirt_timerEvent(bool,QTimerEvent *);
    void sipProtectVirt_childEvent(bool,QChildEvent *);
    void sipProtectVirt_customEvent(bool,QCustomEvent *);
    void sipProtect_connectNotify(const char *);
    void sipProtect_disconnectNotify(const char *);

    /*
     * There is a public method for every Qt signal that can be emitted
     * by this object.  This function is called by Python to emit the
     * signal.
     */
    int sipEmit_destroyed(PyObject *);
    int sipEmit_readyReadStdout(PyObject *);
    int sipEmit_readyReadStderr(PyObject *);
    int sipEmit_processExited(PyObject *);
    int sipEmit_wroteToStdin(PyObject *);
    int sipEmit_launchFinished(PyObject *);

    /*
     * There is a protected method for every virtual method visible from
     * this class.
     */
protected:
    QMetaObject * metaObject() const;
    void setArguments(const QStringList&);
    void addArgument(const QString&);
    void setWorkingDirectory(const QDir&);
    bool start(QStringList *);
    bool launch(const QString&,QStringList *);
    bool launch(const QByteArray&,QStringList *);
    QByteArray readStdout();
    QByteArray readStderr();
    QString readLineStdout();
    QString readLineStderr();
    void writeToStdin(const QByteArray&);
    void writeToStdin(const QString&);
    void closeStdin();
    bool event(QEvent *);
    bool eventFilter(QObject *,QEvent *);
    void setName(const char *);
    void insertChild(QObject *);
    void removeChild(QObject *);
    bool setProperty(const char *,const QVariant&);
    QVariant property(const char *) const;
    void timerEvent(QTimerEvent *);
    void childEvent(QChildEvent *);
    void customEvent(QCustomEvent *);

public:
    sipSimpleWrapper *sipPySelf;

private:
    sipQProcess(const sipQProcess &);
    sipQProcess &operator = (const sipQProcess &);

    char sipPyMethods[24];
};

sipQProcess::sipQProcess(QObject *a0,const char *a1): QProcess(a0,a1), sipPySelf(0)
{
    memset(sipPyMethods, 0, sizeof (sipPyMethods));
}

sipQProcess::sipQProcess(const QString& a0,QObject *a1,const char *a2): QProcess(a0,a1,a2), sipPySelf(0)
{
    memset(sipPyMethods, 0, sizeof (sipPyMethods));
}

sipQProcess::sipQProcess(const QStringList& a0,QObject *a1,const char *a2): QProcess(a0,a1,a2), sipPySelf(0)
{
    memset(sipPyMethods, 0, sizeof (sipPyMethods));
}

sipQProcess::~sipQProcess()
{
    sipCommonDtor(sipPySelf);
}

QMetaObject * sipQProcess::metaObject() const
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[0]),sipPySelf,NULL,sipName_metaObject);

    if (!meth)
        return QProcess::metaObject();

    extern QMetaObject * sipVH_qt_179(sip_gilstate_t,PyObject *);

    return sipVH_qt_179(sipGILState,meth);
}

void sipQProcess::setArguments(const QStringList& a0)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[1],sipPySelf,NULL,sipName_setArguments);

    if (!meth)
    {
        QProcess::setArguments(a0);
        return;
    }

    extern void sipVH_qt_163(sip_gilstate_t,PyObject *,const QStringList&);

    sipVH_qt_163(sipGILState,meth,a0);
}

void sipQProcess::addArgument(const QString& a0)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[2],sipPySelf,NULL,sipName_addArgument);

    if (!meth)
    {
        QProcess::addArgument(a0);
        return;
    }

    extern void sipVH_qt_37(sip_gilstate_t,PyObject *,const QString&);

    sipVH_qt_37(sipGILState,meth,a0);
}

void sipQProcess::setWorkingDirectory(const QDir& a0)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[3],sipPySelf,NULL,sipName_setWorkingDirectory);

    if (!meth)
    {
        QProcess::setWorkingDirectory(a0);
        return;
    }

    extern void sipVH_qt_162(sip_gilstate_t,PyObject *,const QDir&);

    sipVH_qt_162(sipGILState,meth,a0);
}

bool sipQProcess::start(QStringList *a0)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[4],sipPySelf,NULL,sipName_start);

    if (!meth)
        return QProcess::start(a0);

    extern bool sipVH_qt_161(sip_gilstate_t,PyObject *,QStringList *);

    return sipVH_qt_161(sipGILState,meth,a0);
}

bool sipQProcess::launch(const QString& a0,QStringList *a1)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[5],sipPySelf,NULL,sipName_launch);

    if (!meth)
        return QProcess::launch(a0,a1);

    extern bool sipVH_qt_160(sip_gilstate_t,PyObject *,const QString&,QStringList *);

    return sipVH_qt_160(sipGILState,meth,a0,a1);
}

bool sipQProcess::launch(const QByteArray& a0,QStringList *a1)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[6],sipPySelf,NULL,sipName_launch);

    if (!meth)
        return QProcess::launch(a0,a1);

    extern bool sipVH_qt_159(sip_gilstate_t,PyObject *,const QByteArray&,QStringList *);

    return sipVH_qt_159(sipGILState,meth,a0,a1);
}

QByteArray sipQProcess::readStdout()
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[7],sipPySelf,NULL,sipName_readStdout);

    if (!meth)
        return QProcess::readStdout();

    extern QByteArray sipVH_qt_158(sip_gilstate_t,PyObject *);

    return sipVH_qt_158(sipGILState,meth);
}

QByteArray sipQProcess::readStderr()
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[8],sipPySelf,NULL,sipName_readStderr);

    if (!meth)
        return QProcess::readStderr();

    extern QByteArray sipVH_qt_158(sip_gilstate_t,PyObject *);

    return sipVH_qt_158(sipGILState,meth);
}

QString sipQProcess::readLineStdout()
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[9],sipPySelf,NULL,sipName_readLineStdout);

    if (!meth)
        return QProcess::readLineStdout();

    extern QString sipVH_qt_147(sip_gilstate_t,PyObject *);

    return sipVH_qt_147(sipGILState,meth);
}

QString sipQProcess::readLineStderr()
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[10],sipPySelf,NULL,sipName_readLineStderr);

    if (!meth)
        return QProcess::readLineStderr();

    extern QString sipVH_qt_147(sip_gilstate_t,PyObject *);

    return sipVH_qt_147(sipGILState,meth);
}

void sipQProcess::writeToStdin(const QByteArray& a0)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[11],sipPySelf,NULL,sipName_writeToStdin);

    if (!meth)
    {
        QProcess::writeToStdin(a0);
        return;
    }

    extern void sipVH_qt_157(sip_gilstate_t,PyObject *,const QByteArray&);

    sipVH_qt_157(sipGILState,meth,a0);
}

void sipQProcess::writeToStdin(const QString& a0)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[12],sipPySelf,NULL,sipName_writeToStdin);

    if (!meth)
    {
        QProcess::writeToStdin(a0);
        return;
    }

    extern void sipVH_qt_37(sip_gilstate_t,PyObject *,const QString&);

    sipVH_qt_37(sipGILState,meth,a0);
}

void sipQProcess::closeStdin()
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[13],sipPySelf,NULL,sipName_closeStdin);

    if (!meth)
    {
        QProcess::closeStdin();
        return;
    }

    extern void sipVH_qt_2(sip_gilstate_t,PyObject *);

    sipVH_qt_2(sipGILState,meth);
}

bool sipQProcess::event(QEvent *a0)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[14],sipPySelf,NULL,sipName_event);

    if (!meth)
        return QObject::event(a0);

    extern bool sipVH_qt_178(sip_gilstate_t,PyObject *,QEvent *);

    return sipVH_qt_178(sipGILState,meth,a0);
}

bool sipQProcess::eventFilter(QObject *a0,QEvent *a1)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[15],sipPySelf,NULL,sipName_eventFilter);

    if (!meth)
        return QObject::eventFilter(a0,a1);

    extern bool sipVH_qt_177(sip_gilstate_t,PyObject *,QObject *,QEvent *);

    return sipVH_qt_177(sipGILState,meth,a0,a1);
}

void sipQProcess::setName(const char *a0)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[16],sipPySelf,NULL,sipName_setName);

    if (!meth)
    {
        QObject::setName(a0);
        return;
    }

    extern void sipVH_qt_176(sip_gilstate_t,PyObject *,const char *);

    sipVH_qt_176(sipGILState,meth,a0);
}

void sipQProcess::insertChild(QObject *a0)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[17],sipPySelf,NULL,sipName_insertChild);

    if (!meth)
    {
        QObject::insertChild(a0);
        return;
    }

    extern void sipVH_qt_175(sip_gilstate_t,PyObject *,QObject *);

    sipVH_qt_175(sipGILState,meth,a0);
}

void sipQProcess::removeChild(QObject *a0)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[18],sipPySelf,NULL,sipName_removeChild);

    if (!meth)
    {
        QObject::removeChild(a0);
        return;
    }

    extern void sipVH_qt_175(sip_gilstate_t,PyObject *,QObject *);

    sipVH_qt_175(sipGILState,meth,a0);
}

bool sipQProcess::setProperty(const char *a0,const QVariant& a1)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[19],sipPySelf,NULL,sipName_setProperty);

    if (!meth)
        return QObject::setProperty(a0,a1);

    extern bool sipVH_qt_174(sip_gilstate_t,PyObject *,const char *,const QVariant&);

    return sipVH_qt_174(sipGILState,meth,a0,a1);
}

QVariant sipQProcess::property(const char *a0) const
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[20]),sipPySelf,NULL,sipName_property);

    if (!meth)
        return QObject::property(a0);

    extern QVariant sipVH_qt_173(sip_gilstate_t,PyObject *,const char *);

    return sipVH_qt_173(sipGILState,meth,a0);
}

void sipQProcess::timerEvent(QTimerEvent *a0)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[21],sipPySelf,NULL,sipName_timerEvent);

    if (!meth)
    {
        QObject::timerEvent(a0);
        return;
    }

    extern void sipVH_qt_172(sip_gilstate_t,PyObject *,QTimerEvent *);

    sipVH_qt_172(sipGILState,meth,a0);
}

void sipQProcess::childEvent(QChildEvent *a0)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[22],sipPySelf,NULL,sipName_childEvent);

    if (!meth)
    {
        QObject::childEvent(a0);
        return;
    }

    extern void sipVH_qt_171(sip_gilstate_t,PyObject *,QChildEvent *);

    sipVH_qt_171(sipGILState,meth,a0);
}

void sipQProcess::customEvent(QCustomEvent *a0)
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[23],sipPySelf,NULL,sipName_customEvent);

    if (!meth)
    {
        QObject::customEvent(a0);
        return;
    }

    extern void sipVH_qt_170(sip_gilstate_t,PyObject *,QCustomEvent *);

    sipVH_qt_170(sipGILState,meth,a0);
}

void sipQProcess::sipProtectVirt_timerEvent(bool sipSelfWasArg,QTimerEvent *a0)
{
    (sipSelfWasArg ? QObject::timerEvent(a0) : timerEvent(a0));
}

void sipQProcess::sipProtectVirt_childEvent(bool sipSelfWasArg,QChildEvent *a0)
{
    (sipSelfWasArg ? QObject::childEvent(a0) : childEvent(a0));
}

void sipQProcess::sipProtectVirt_customEvent(bool sipSelfWasArg,QCustomEvent *a0)
{
    (sipSelfWasArg ? QObject::customEvent(a0) : customEvent(a0));
}

void sipQProcess::sipProtect_connectNotify(const char *a0)
{
    QProcess::connectNotify(a0);
}

void sipQProcess::sipProtect_disconnectNotify(const char *a0)
{
    QProcess::disconnectNotify(a0);
}

int sipQProcess::sipEmit_destroyed(PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        if (sipParseArgs(&sipParseErr, sipArgs, ""))
        {
            emit destroyed();

            return 0;
        }
    }

    {
        QObject * a0;

        if (sipParseArgs(&sipParseErr, sipArgs, "J8", sipType_QObject, &a0))
        {
            emit destroyed(a0);

            return 0;
        }
    }

    sipNoMethod(sipParseErr, sipName_QProcess, sipName_destroyed, NULL);

    return -1;
}

extern "C" {static int QProcess_emit_destroyed(sipSimpleWrapper *, PyObject *);}
static int QProcess_emit_destroyed(sipSimpleWrapper *sw,PyObject *sipArgs)
{
    sipQProcess *ptr = reinterpret_cast<sipQProcess *>(sipGetComplexCppPtr(sw));

    return (ptr ? ptr->sipEmit_destroyed(sipArgs) : -1);
}

int sipQProcess::sipEmit_readyReadStdout(PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        if (sipParseArgs(&sipParseErr, sipArgs, ""))
        {
            emit readyReadStdout();

            return 0;
        }
    }

    sipNoMethod(sipParseErr, sipName_QProcess, sipName_readyReadStdout, NULL);

    return -1;
}

extern "C" {static int QProcess_emit_readyReadStdout(sipSimpleWrapper *, PyObject *);}
static int QProcess_emit_readyReadStdout(sipSimpleWrapper *sw,PyObject *sipArgs)
{
    sipQProcess *ptr = reinterpret_cast<sipQProcess *>(sipGetComplexCppPtr(sw));

    return (ptr ? ptr->sipEmit_readyReadStdout(sipArgs) : -1);
}

int sipQProcess::sipEmit_readyReadStderr(PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        if (sipParseArgs(&sipParseErr, sipArgs, ""))
        {
            emit readyReadStderr();

            return 0;
        }
    }

    sipNoMethod(sipParseErr, sipName_QProcess, sipName_readyReadStderr, NULL);

    return -1;
}

extern "C" {static int QProcess_emit_readyReadStderr(sipSimpleWrapper *, PyObject *);}
static int QProcess_emit_readyReadStderr(sipSimpleWrapper *sw,PyObject *sipArgs)
{
    sipQProcess *ptr = reinterpret_cast<sipQProcess *>(sipGetComplexCppPtr(sw));

    return (ptr ? ptr->sipEmit_readyReadStderr(sipArgs) : -1);
}

int sipQProcess::sipEmit_processExited(PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        if (sipParseArgs(&sipParseErr, sipArgs, ""))
        {
            emit processExited();

            return 0;
        }
    }

    sipNoMethod(sipParseErr, sipName_QProcess, sipName_processExited, NULL);

    return -1;
}

extern "C" {static int QProcess_emit_processExited(sipSimpleWrapper *, PyObject *);}
static int QProcess_emit_processExited(sipSimpleWrapper *sw,PyObject *sipArgs)
{
    sipQProcess *ptr = reinterpret_cast<sipQProcess *>(sipGetComplexCppPtr(sw));

    return (ptr ? ptr->sipEmit_processExited(sipArgs) : -1);
}

int sipQProcess::sipEmit_wroteToStdin(PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        if (sipParseArgs(&sipParseErr, sipArgs, ""))
        {
            emit wroteToStdin();

            return 0;
        }
    }

    sipNoMethod(sipParseErr, sipName_QProcess, sipName_wroteToStdin, NULL);

    return -1;
}

extern "C" {static int QProcess_emit_wroteToStdin(sipSimpleWrapper *, PyObject *);}
static int QProcess_emit_wroteToStdin(sipSimpleWrapper *sw,PyObject *sipArgs)
{
    sipQProcess *ptr = reinterpret_cast<sipQProcess *>(sipGetComplexCppPtr(sw));

    return (ptr ? ptr->sipEmit_wroteToStdin(sipArgs) : -1);
}

int sipQProcess::sipEmit_launchFinished(PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        if (sipParseArgs(&sipParseErr, sipArgs, ""))
        {
            emit launchFinished();

            return 0;
        }
    }

    sipNoMethod(sipParseErr, sipName_QProcess, sipName_launchFinished, NULL);

    return -1;
}

extern "C" {static int QProcess_emit_launchFinished(sipSimpleWrapper *, PyObject *);}
static int QProcess_emit_launchFinished(sipSimpleWrapper *sw,PyObject *sipArgs)
{
    sipQProcess *ptr = reinterpret_cast<sipQProcess *>(sipGetComplexCppPtr(sw));

    return (ptr ? ptr->sipEmit_launchFinished(sipArgs) : -1);
}

static pyqt3QtSignal signals_QProcess[] = {
    {sipName_destroyed, QProcess_emit_destroyed},
    {sipName_readyReadStdout, QProcess_emit_readyReadStdout},
    {sipName_readyReadStderr, QProcess_emit_readyReadStderr},
    {sipName_processExited, QProcess_emit_processExited},
    {sipName_wroteToStdin, QProcess_emit_wroteToStdin},
    {sipName_launchFinished, QProcess_emit_launchFinished},
    {NULL, NULL}
};


extern "C" {static PyObject *meth_QProcess_timerEvent(PyObject *, PyObject *);}
static PyObject *meth_QProcess_timerEvent(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        QTimerEvent * a0;
        sipQProcess *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ8", &sipSelf, sipType_QProcess, &sipCpp, sipType_QTimerEvent, &a0))
        {
            sipCpp->sipProtectVirt_timerEvent(sipSelfWasArg,a0);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QProcess, sipName_timerEvent, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QProcess_childEvent(PyObject *, PyObject *);}
static PyObject *meth_QProcess_childEvent(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        QChildEvent * a0;
        sipQProcess *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ8", &sipSelf, sipType_QProcess, &sipCpp, sipType_QChildEvent, &a0))
        {
            sipCpp->sipProtectVirt_childEvent(sipSelfWasArg,a0);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QProcess, sipName_childEvent, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QProcess_customEvent(PyObject *, PyObject *);}
static PyObject *meth_QProcess_customEvent(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        QCustomEvent * a0;
        sipQProcess *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ8", &sipSelf, sipType_QProcess, &sipCpp, sipType_QCustomEvent, &a0))
        {
            sipCpp->sipProtectVirt_customEvent(sipSelfWasArg,a0);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QProcess, sipName_customEvent, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QProcess_arguments(PyObject *, PyObject *);}
static PyObject *meth_QProcess_arguments(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QProcess *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QProcess, &sipCpp))
        {
            QStringList *sipRes;

            sipRes = new QStringList(sipCpp->arguments());

            return sipConvertFromNewType(sipRes,sipType_QStringList,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QProcess, sipName_arguments, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QProcess_clearArguments(PyObject *, PyObject *);}
static PyObject *meth_QProcess_clearArguments(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QProcess *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QProcess, &sipCpp))
        {
            sipCpp->clearArguments();

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QProcess, sipName_clearArguments, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QProcess_setArguments(PyObject *, PyObject *);}
static PyObject *meth_QProcess_setArguments(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        const QStringList * a0;
        QProcess *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ9", &sipSelf, sipType_QProcess, &sipCpp, sipType_QStringList, &a0))
        {
            (sipSelfWasArg ? sipCpp->QProcess::setArguments(*a0) : sipCpp->setArguments(*a0));

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QProcess, sipName_setArguments, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QProcess_addArgument(PyObject *, PyObject *);}
static PyObject *meth_QProcess_addArgument(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        const QString * a0;
        int a0State = 0;
        QProcess *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ1", &sipSelf, sipType_QProcess, &sipCpp, sipType_QString, &a0, &a0State))
        {
            (sipSelfWasArg ? sipCpp->QProcess::addArgument(*a0) : sipCpp->addArgument(*a0));
            sipReleaseType(const_cast<QString *>(a0),sipType_QString,a0State);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QProcess, sipName_addArgument, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QProcess_workingDirectory(PyObject *, PyObject *);}
static PyObject *meth_QProcess_workingDirectory(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QProcess *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QProcess, &sipCpp))
        {
            QDir *sipRes;

            sipRes = new QDir(sipCpp->workingDirectory());

            return sipConvertFromNewType(sipRes,sipType_QDir,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QProcess, sipName_workingDirectory, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QProcess_setWorkingDirectory(PyObject *, PyObject *);}
static PyObject *meth_QProcess_setWorkingDirectory(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        const QDir * a0;
        QProcess *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ9", &sipSelf, sipType_QProcess, &sipCpp, sipType_QDir, &a0))
        {
            (sipSelfWasArg ? sipCpp->QProcess::setWorkingDirectory(*a0) : sipCpp->setWorkingDirectory(*a0));

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QProcess, sipName_setWorkingDirectory, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QProcess_setCommunication(PyObject *, PyObject *);}
static PyObject *meth_QProcess_setCommunication(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        int a0;
        QProcess *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bi", &sipSelf, sipType_QProcess, &sipCpp, &a0))
        {
            sipCpp->setCommunication(a0);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QProcess, sipName_setCommunication, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QProcess_communication(PyObject *, PyObject *);}
static PyObject *meth_QProcess_communication(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QProcess *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QProcess, &sipCpp))
        {
            int sipRes;

            sipRes = sipCpp->communication();

            return SIPLong_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QProcess, sipName_communication, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QProcess_start(PyObject *, PyObject *);}
static PyObject *meth_QProcess_start(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        QStringList * a0 = 0;
        QProcess *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B|J8", &sipSelf, sipType_QProcess, &sipCpp, sipType_QStringList, &a0))
        {
            bool sipRes;

            sipRes = (sipSelfWasArg ? sipCpp->QProcess::start(a0) : sipCpp->start(a0));

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QProcess, sipName_start, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QProcess_launch(PyObject *, PyObject *);}
static PyObject *meth_QProcess_launch(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        const QString * a0;
        int a0State = 0;
        QStringList * a1 = 0;
        QProcess *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ1|J8", &sipSelf, sipType_QProcess, &sipCpp, sipType_QString, &a0, &a0State, sipType_QStringList, &a1))
        {
            bool sipRes;

            sipRes = (sipSelfWasArg ? sipCpp->QProcess::launch(*a0,a1) : sipCpp->launch(*a0,a1));
            sipReleaseType(const_cast<QString *>(a0),sipType_QString,a0State);

            return PyBool_FromLong(sipRes);
        }
    }

    {
        const QByteArray * a0;
        int a0State = 0;
        QStringList * a1 = 0;
        QProcess *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ1|J8", &sipSelf, sipType_QProcess, &sipCpp, sipType_QByteArray, &a0, &a0State, sipType_QStringList, &a1))
        {
            bool sipRes;

            sipRes = (sipSelfWasArg ? sipCpp->QProcess::launch(*a0,a1) : sipCpp->launch(*a0,a1));
            sipReleaseType(const_cast<QByteArray *>(a0),sipType_QByteArray,a0State);

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QProcess, sipName_launch, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QProcess_isRunning(PyObject *, PyObject *);}
static PyObject *meth_QProcess_isRunning(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QProcess *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QProcess, &sipCpp))
        {
            bool sipRes;

            sipRes = sipCpp->isRunning();

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QProcess, sipName_isRunning, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QProcess_normalExit(PyObject *, PyObject *);}
static PyObject *meth_QProcess_normalExit(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QProcess *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QProcess, &sipCpp))
        {
            bool sipRes;

            sipRes = sipCpp->normalExit();

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QProcess, sipName_normalExit, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QProcess_exitStatus(PyObject *, PyObject *);}
static PyObject *meth_QProcess_exitStatus(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QProcess *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QProcess, &sipCpp))
        {
            int sipRes;

            sipRes = sipCpp->exitStatus();

            return SIPLong_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QProcess, sipName_exitStatus, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QProcess_readStdout(PyObject *, PyObject *);}
static PyObject *meth_QProcess_readStdout(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        QProcess *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QProcess, &sipCpp))
        {
            QByteArray *sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = new QByteArray((sipSelfWasArg ? sipCpp->QProcess::readStdout() : sipCpp->readStdout()));
            Py_END_ALLOW_THREADS

            return sipConvertFromNewType(sipRes,sipType_QByteArray,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QProcess, sipName_readStdout, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QProcess_readStderr(PyObject *, PyObject *);}
static PyObject *meth_QProcess_readStderr(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        QProcess *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QProcess, &sipCpp))
        {
            QByteArray *sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = new QByteArray((sipSelfWasArg ? sipCpp->QProcess::readStderr() : sipCpp->readStderr()));
            Py_END_ALLOW_THREADS

            return sipConvertFromNewType(sipRes,sipType_QByteArray,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QProcess, sipName_readStderr, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QProcess_canReadLineStdout(PyObject *, PyObject *);}
static PyObject *meth_QProcess_canReadLineStdout(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QProcess *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QProcess, &sipCpp))
        {
            bool sipRes;

            sipRes = sipCpp->canReadLineStdout();

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QProcess, sipName_canReadLineStdout, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QProcess_canReadLineStderr(PyObject *, PyObject *);}
static PyObject *meth_QProcess_canReadLineStderr(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QProcess *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QProcess, &sipCpp))
        {
            bool sipRes;

            sipRes = sipCpp->canReadLineStderr();

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QProcess, sipName_canReadLineStderr, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QProcess_readLineStdout(PyObject *, PyObject *);}
static PyObject *meth_QProcess_readLineStdout(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        QProcess *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QProcess, &sipCpp))
        {
            QString *sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = new QString((sipSelfWasArg ? sipCpp->QProcess::readLineStdout() : sipCpp->readLineStdout()));
            Py_END_ALLOW_THREADS

            return sipConvertFromNewType(sipRes,sipType_QString,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QProcess, sipName_readLineStdout, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QProcess_readLineStderr(PyObject *, PyObject *);}
static PyObject *meth_QProcess_readLineStderr(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        QProcess *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QProcess, &sipCpp))
        {
            QString *sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = new QString((sipSelfWasArg ? sipCpp->QProcess::readLineStderr() : sipCpp->readLineStderr()));
            Py_END_ALLOW_THREADS

            return sipConvertFromNewType(sipRes,sipType_QString,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QProcess, sipName_readLineStderr, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QProcess_processIdentifier(PyObject *, PyObject *);}
static PyObject *meth_QProcess_processIdentifier(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QProcess *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QProcess, &sipCpp))
        {
            QProcess::PID sipRes;

            sipRes = sipCpp->processIdentifier();

            return PyLong_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QProcess, sipName_processIdentifier, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QProcess_flushStdin(PyObject *, PyObject *);}
static PyObject *meth_QProcess_flushStdin(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QProcess *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QProcess, &sipCpp))
        {
            sipCpp->flushStdin();

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QProcess, sipName_flushStdin, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QProcess_tryTerminate(PyObject *, PyObject *);}
static PyObject *meth_QProcess_tryTerminate(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QProcess *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QProcess, &sipCpp))
        {
            sipCpp->tryTerminate();

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QProcess, sipName_tryTerminate, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QProcess_kill(PyObject *, PyObject *);}
static PyObject *meth_QProcess_kill(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QProcess *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QProcess, &sipCpp))
        {
            sipCpp->kill();

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QProcess, sipName_kill, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QProcess_writeToStdin(PyObject *, PyObject *);}
static PyObject *meth_QProcess_writeToStdin(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        const QByteArray * a0;
        int a0State = 0;
        QProcess *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ1", &sipSelf, sipType_QProcess, &sipCpp, sipType_QByteArray, &a0, &a0State))
        {
            (sipSelfWasArg ? sipCpp->QProcess::writeToStdin(*a0) : sipCpp->writeToStdin(*a0));
            sipReleaseType(const_cast<QByteArray *>(a0),sipType_QByteArray,a0State);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    {
        const QString * a0;
        int a0State = 0;
        QProcess *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ1", &sipSelf, sipType_QProcess, &sipCpp, sipType_QString, &a0, &a0State))
        {
            (sipSelfWasArg ? sipCpp->QProcess::writeToStdin(*a0) : sipCpp->writeToStdin(*a0));
            sipReleaseType(const_cast<QString *>(a0),sipType_QString,a0State);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QProcess, sipName_writeToStdin, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QProcess_closeStdin(PyObject *, PyObject *);}
static PyObject *meth_QProcess_closeStdin(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        QProcess *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QProcess, &sipCpp))
        {
            (sipSelfWasArg ? sipCpp->QProcess::closeStdin() : sipCpp->closeStdin());

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QProcess, sipName_closeStdin, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QProcess_connectNotify(PyObject *, PyObject *);}
static PyObject *meth_QProcess_connectNotify(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const char * a0;
        sipQProcess *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bs", &sipSelf, sipType_QProcess, &sipCpp, &a0))
        {
            sipCpp->sipProtect_connectNotify(a0);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QProcess, sipName_connectNotify, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QProcess_disconnectNotify(PyObject *, PyObject *);}
static PyObject *meth_QProcess_disconnectNotify(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const char * a0;
        sipQProcess *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bs", &sipSelf, sipType_QProcess, &sipCpp, &a0))
        {
            sipCpp->sipProtect_disconnectNotify(a0);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QProcess, sipName_disconnectNotify, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QProcess_metaObject(PyObject *, PyObject *);}
static PyObject *meth_QProcess_metaObject(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        QProcess *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QProcess, &sipCpp))
        {
            QMetaObject *sipRes;

            sipRes = (sipSelfWasArg ? sipCpp->QProcess::metaObject() : sipCpp->metaObject());

            return sipConvertFromType(sipRes,sipType_QMetaObject,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QProcess, sipName_metaObject, NULL);

    return NULL;
}


/* Cast a pointer to a type somewhere in its superclass hierarchy. */
extern "C" {static void *cast_QProcess(void *, const sipTypeDef *);}
static void *cast_QProcess(void *ptr, const sipTypeDef *targetType)
{
    void *res;

    if (targetType == sipType_QProcess)
        return ptr;

    if ((res = ((const sipClassTypeDef *)sipType_QObject)->ctd_cast((QObject *)(QProcess *)ptr,targetType)) != NULL)
        return res;

    return NULL;
}


/* Call the instance's destructor. */
extern "C" {static void release_QProcess(void *, int);}
static void release_QProcess(void *sipCppV,int sipState)
{
    if (sipState & SIP_DERIVED_CLASS)
        delete reinterpret_cast<sipQProcess *>(sipCppV);
    else
        delete reinterpret_cast<QProcess *>(sipCppV);
}


extern "C" {static void dealloc_QProcess(sipSimpleWrapper *);}
static void dealloc_QProcess(sipSimpleWrapper *sipSelf)
{
    if (sipIsDerived(sipSelf))
        reinterpret_cast<sipQProcess *>(sipSelf->u.cppPtr)->sipPySelf = NULL;

    if (sipIsPyOwned(sipSelf))
    {
        release_QProcess(sipSelf->u.cppPtr,sipSelf->flags);
    }
}


extern "C" {static void *init_QProcess(sipSimpleWrapper *, PyObject *, PyObject *, PyObject **, PyObject **, PyObject **);}
static void *init_QProcess(sipSimpleWrapper *sipSelf, PyObject *sipArgs, PyObject *sipKwds, PyObject **sipUnused, PyObject **sipOwner, PyObject **sipParseErr)
{
    sipQProcess *sipCpp = 0;

    {
        QObject * a0 = 0;
        const char * a1 = 0;

        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, NULL, sipUnused, "|JHs", sipType_QObject, &a0, sipOwner, &a1))
        {
            sipCpp = new sipQProcess(a0,a1);

            sipCpp->sipPySelf = sipSelf;

            return sipCpp;
        }
    }

    {
        const QString * a0;
        int a0State = 0;
        QObject * a1 = 0;
        const char * a2 = 0;

        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, NULL, sipUnused, "J1|JHs", sipType_QString, &a0, &a0State, sipType_QObject, &a1, sipOwner, &a2))
        {
            sipCpp = new sipQProcess(*a0,a1,a2);
            sipReleaseType(const_cast<QString *>(a0),sipType_QString,a0State);

            sipCpp->sipPySelf = sipSelf;

            return sipCpp;
        }
    }

    {
        const QStringList * a0;
        QObject * a1 = 0;
        const char * a2 = 0;

        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, NULL, sipUnused, "J9|JHs", sipType_QStringList, &a0, sipType_QObject, &a1, sipOwner, &a2))
        {
            sipCpp = new sipQProcess(*a0,a1,a2);

            sipCpp->sipPySelf = sipSelf;

            return sipCpp;
        }
    }

    return NULL;
}


/* Define this type's super-types. */
static sipEncodedTypeDef supers_QProcess[] = {{202, 255, 1}};


static PyMethodDef methods_QProcess[] = {
    {SIP_MLNAME_CAST(sipName_addArgument), meth_QProcess_addArgument, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_arguments), meth_QProcess_arguments, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_canReadLineStderr), meth_QProcess_canReadLineStderr, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_canReadLineStdout), meth_QProcess_canReadLineStdout, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_childEvent), meth_QProcess_childEvent, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_clearArguments), meth_QProcess_clearArguments, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_closeStdin), meth_QProcess_closeStdin, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_communication), meth_QProcess_communication, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_connectNotify), meth_QProcess_connectNotify, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_customEvent), meth_QProcess_customEvent, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_disconnectNotify), meth_QProcess_disconnectNotify, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_exitStatus), meth_QProcess_exitStatus, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_flushStdin), meth_QProcess_flushStdin, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_isRunning), meth_QProcess_isRunning, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_kill), meth_QProcess_kill, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_launch), meth_QProcess_launch, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_metaObject), meth_QProcess_metaObject, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_normalExit), meth_QProcess_normalExit, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_processIdentifier), meth_QProcess_processIdentifier, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_readLineStderr), meth_QProcess_readLineStderr, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_readLineStdout), meth_QProcess_readLineStdout, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_readStderr), meth_QProcess_readStderr, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_readStdout), meth_QProcess_readStdout, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_setArguments), meth_QProcess_setArguments, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_setCommunication), meth_QProcess_setCommunication, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_setWorkingDirectory), meth_QProcess_setWorkingDirectory, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_start), meth_QProcess_start, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_timerEvent), meth_QProcess_timerEvent, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_tryTerminate), meth_QProcess_tryTerminate, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_workingDirectory), meth_QProcess_workingDirectory, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_writeToStdin), meth_QProcess_writeToStdin, METH_VARARGS, NULL}
};

static sipEnumMemberDef enummembers_QProcess[] = {
    {sipName_DupStderr, QProcess::DupStderr, 236},
    {sipName_Stderr, QProcess::Stderr, 236},
    {sipName_Stdin, QProcess::Stdin, 236},
    {sipName_Stdout, QProcess::Stdout, 236},
};


pyqt3ClassTypeDef sipTypeDef_qt_QProcess = {
{
    {
        -1,
        0,
        0,
        SIP_TYPE_SCC|SIP_TYPE_CLASS,
        sipNameNr_QProcess,
        {0}
    },
    {
        sipNameNr_QProcess,
        {0, 0, 1},
        31, methods_QProcess,
        4, enummembers_QProcess,
        0, 0,
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    },
    0,
    -1,
    -1,
    supers_QProcess,
    0,
    init_QProcess,
    0,
    0,
#if PY_MAJOR_VERSION >= 3
    0,
    0,
#else
    0,
    0,
    0,
    0,
#endif
    dealloc_QProcess,
    0,
    0,
    0,
    release_QProcess,
    cast_QProcess,
    0,
    0,
    0
},
    signals_QProcess
};
