#!/bin/sh -x

curl -X PUT ${COUCH_URI}/contacts/anniecordy -d '{"firstName": "Annie", "lastName":"Cordy","email":"annie@free.ie","phone":"659-555-5555","country":"USA","type":"contact"}'
curl -X PUT ${COUCH_URI}/contacts/totorector -d '{"firstName": "Toto", "lastName":"Rector","email":"toto@free.ie","phone":"555-555-5555","country":"USA","type":"contact"}'
curl -X PUT ${COUCH_URI}/contacts/jeanalliot -d '{"firstName": "Jean", "lastName":"Alliot","email":"jalliot@yahoo.com","country":"USA","type":"contact"}'
curl -X PUT ${COUCH_URI}/contacts/guybedos -d '{"firstName": "Guy", "lastName":"Bedos","email":"gb@bedos.uk","country":"UK","type":"contact"}'
curl -X PUT ${COUCH_URI}/contacts/johnlennon -d '{"firstName": "John", "lastName":"Lennon","email":"john@lennon.ie","country":"USA","type":"contact"}'
curl -X PUT ${COUCH_URI}/contacts/emptyvoid -d '{"firstName": "Empty", "lastName":"Void","country":"USA","type":"contact"}'

curl -X PUT ${COUCH_URI}/speeches/1 -d '{"content": "Il etait une fois, une marchande de foie, qui se dit ma foi, ... "}'

curl -X PUT ${COUCH_URI}/employees/a1 -d '{"name": "Jack Sawyer", "salary":30000,"department":"Sales","type":"employee","employee_no":1}'
curl -X PUT ${COUCH_URI}/employees/b2 -d '{"name": "Kate Lynch", "salary":45000,"department":"Management","type":"employee","employee_no":2}'
curl -X PUT ${COUCH_URI}/employees/c3 -d '{"name": "Patrick Wood", "salary":32000,"department":"Sales","type":"employee","employee_no":3}'
curl -X PUT ${COUCH_URI}/employees/d4 -d '{"name": "John McIntyre", "salary":19000,"department":"Administration","type":"employee","employee_no":4}'
curl -X PUT ${COUCH_URI}/employees/e5 -d '{"name": "Ann Hayes", "salary":60000,"department":"Management","type":"employee","employee_no":5}'
curl -X PUT ${COUCH_URI}/employees/f6 -d '{"name": "Lisa Liu", "salary":38000,"department":"Accounts","type":"employee","employee_no":6}'
curl -X PUT ${COUCH_URI}/employees/g7 -d '{"name": "David Harrington", "salary":31000,"department":"IT","type":"employee","employee_no":7}'

# for join
curl -X PUT ${COUCH_URI}/employees/p1 -d '{"amount": 2100,"date":"20090825","type":"payslip","employee_no":1}'
curl -X PUT ${COUCH_URI}/employees/p2 -d '{"amount": 2100,"date":"20090725","type":"payslip","employee_no":1}'
curl -X PUT ${COUCH_URI}/employees/p3 -d '{"amount": 2100,"date":"20090625","type":"payslip","employee_no":1}'
