all:  clean BasePlusCommissionEmployee572

BasePlusCommissionEmployee572:
	$(CXX) BasePlusCommissionEmployee572.cpp BasePlusCommissionEmployee572_main.cpp CommissionEmployee572.cpp Employee572.cpp SalariedEmployee572.cpp -o BasePlusCommissionEmployee572

clean:
	rm -f BasePlusCommissionEmployee572
