#!/bin/sh


ssh -i ~/ssh/awskey.pem -N -L 9000:localhost:5984 ubuntu@50.17.252.189

# Create a turnel on the machine this script is run.
# Every packet sent to 
# (local machine) 127.0.0.1:9000 
# are sent to the remote user
# ubuntu@50.17.252.189
# Whose in turn on the remote host try to connect itself at localhost:5984
#
# (local machine) 127.0.0.1:9000 ---> (remote) ubuntu@50.17.252.189 --> (remote) localhost:5984
#
# You will be prompted for the password of the ubuntu@50.17.252.189
# to make sure you can log in
