#!/bin/sh -x


printf "\nTEMPORARY VIEW (with common error)\n"
curl -X POST http://127.0.0.1:5984/contacts/_temp_view -d '{"map": "function(doc) { emit(doc._id, doc); }"}' 
# {"error":"bad_content_type","reason":"Content-Type must be application/json"}

printf "\nTEMPORARY VIEW (without error)\n"
curl -X POST http://127.0.0.1:5984/contacts/_temp_view -H "Content-Type: application/json" -d '{"map": "function(doc) { emit(doc._id, doc); }"}'

printf "\nTEMPORARY VIEW (json in external file)\n"
curl -X POST http://127.0.0.1:5984/contacts/_temp_view -H "Content-Type: application/json" -d @tempview1.json

printf "\nTEMPORARY VIEW (filter on existing fields)\n"
curl -X POST http://127.0.0.1:5984/contacts/_temp_view -H "Content-Type: application/json" -d @tempview2.json

printf "\nTEMPORARY VIEW (with ...?key=\"johnsmith\")                                   <-- doesn't work for id or _id or other?\n"
curl -X POST http://127.0.0.1:5984/contacts/_temp_view?key=\"johnsmith\" -d '{"map": "function(doc) { emit(doc._id, doc); }"}' -H "Content-Type: application/json"
#curl -X POST http://127.0.0.1:5984/contacts/_temp_view?keyy=\"johnsmith\" -d '{"map": "function(doc) { emit(doc.email, doc); }"}' -H "Content-Type: application/json"

printf "\nTEMPORARY VIEW (with netcat 'nc -l 3333')\n"
curl -X POST http://127.0.0.1:3333/contacts/_temp_view -d '{"map": "function(doc) { emit(doc._id, doc); }"}' -H "Content-Type: application/json"
# POST /contacts/_temp_view HTTP/1.1
# User-Agent: curl/7.21.7 (x86_64-redhat-linux-gnu) libcurl/7.21.7 NSS/3.13.3.0 zlib/1.2.5 libidn/1.22 libssh2/1.2.7
# Host: 127.0.0.1:3333
# Accept: */*
# Content-Type: application/json
# Content-Length: 48
# 
# {"map": "function(doc) { emit(doc._id, doc); }"}
